### ISSUE TITLE
PDF Table header broken when multiple consecutive header rows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#102]
This occurs in file mep-wgfs-nm532-I2.adoc:

ADoc and XML sources attached:
[Archive.zip](https://github.com/metanorma/metanorma-bipm/files/5774307/Archive.zip)

<img width="369" alt="Screen Shot 2021-01-06 at 3 05 06 PM" src="https://user-images.githubusercontent.com/11865/103739425-9269ed80-5030-11eb-858c-ce4e19913d95.png">
[mep-wgfs-nm532-I2.pdf](https://github.com/metanorma/metanorma-bipm/files/5774303/mep-wgfs-nm532-I2.pdf)

The specific encoding is:
```adoc
[cols="<,<,<,>,>"]
[%unnumbered]
|===
h| line no | transition | comp. 2+| stem:[f_("xy") = \[ f(y , x) – f(a_(10), R(56) 32-0) \] // rm(kHz)]
h| | stem:[x] | stem:[y] | stem:[f_("xy")] | stem:[u_c // rm(kHz)]

| stem:[1111] | P(53) 32-0 | stem:[a_1] | stem:[2599708.0] | stem:[5.0]
| stem:[1110] | R(56) 32-0 | stem:[a_(10)] | stem:[0.0] | -
| stem:[1109] | P(83) 33-0 | stem:[a_(21)] | stem:[–15682075.2] | stem:[5.0]
| | R(134) 36-0 | stem:[a_1] | stem:[–17173681.7] | stem:[5.0]
...
```

It seems that the layout breaks when there are consecutive header rows. However, when the header rows are sandwiched with non-header rows, the behavior is correct:
<img width="340" alt="Screen Shot 2021-01-06 at 3 08 07 PM" src="https://user-images.githubusercontent.com/11865/103739741-fc829280-5030-11eb-8c2c-fc4d2a212b61.png">

**Comment by Intelligent2013** [comment]
@ronaldtse I think that there is a mistake in adoc markup.

This adoc markup
```
|===
h| line no | transition | comp. 2+| stem:[f_("xy") = \[ f(y , x) – f(a_(10), R(56) 32-0) \] // rm(kHz)]
h| | stem:[x] | stem:[y] | stem:[f_("xy")] | stem:[u_c // rm(kHz)]
...
```
converts to xml:
```xml
<tbody>
<tr>
<th valign="top" align="left">line no</th>
<td valign="top" align="left">transition</td>
<td valign="top" align="left">comp.</td>
<td colspan="2" valign="top" align="right">...
```

It means that only first cell marks as 'header' cell (tag th). And please note, that `tr` in `tbody`, not in `thead`.

I've found two ways to mark first two rows as header rows:
1. add `h` prefix to each cell (i.e. `h|`):
```adoc
|===
h| line no h| transition h| comp. 2+h| stem:[f_("xy") = \[ f(y , x) – f(a_(10), R(56) 32-0) \] // rm(kHz)]
h| h| stem:[x] h| stem:[y] h| stem:[f_("xy")] h| stem:[u_c // rm(kHz)]
```
then resulted xml looks:
```xml
<tbody>
<tr>
<th valign="top" align="left">line no</th>
<th valign="top" align="left">transition</th>
<th valign="top" align="left">comp.</th>
<th colspan="2" valign="top" align="right">...
```

Also, `tr` in `tbody`, but all cells is `th`.

2. Remove `h` prefix and add `headerrows=2,`.
```adoc
[headerrows=2,cols="<,<,<,>,>"]
[%unnumbered]
|===
| line no | transition | comp. 2+| stem:[f_("xy") = \[ f(y , x) – f(a_(10), R(56) 32-0) \] // rm(kHz)]
| | stem:[x] | stem:[y] | stem:[f_("xy")] | stem:[u_c // rm(kHz)]
```
then resulted xml looks:

```xml
<table id="_79d6fbe2-65c4-4e37-984d-531547585639" unnumbered="true">
<thead>
<tr>
<th valign="top" align="left">line no</th>
<th valign="top" align="left">transition</th>
<th valign="top" align="left">comp.</th>
<th colspan="2" valign="top" align="right">...
```

`tr` in `thead` and each cell is `th`.

In both case resulted PDF looks as:
![изображение](https://user-images.githubusercontent.com/5559926/103763540-06a19280-502b-11eb-85b5-c2f46c4fdad9.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 you are correct in that the source is miscoded -- however I was trying to achieve this effect:

<img width="675" alt="Screen Shot 2021-01-07 at 11 08 10 AM" src="https://user-images.githubusercontent.com/11865/103846242-a23d0c80-50d8-11eb-977e-1a3fdaec18b1.png">

This doesn't seem to do it:
```adoc
[%unnumbered]
.stem:[ii(lambda) ~~ 10.3" "mu rm(m)" OsO"_4]
|===
| h| stem:[""^12 "C"^{16} "O"_2] h| stem:[rm(OsO)_4] h| | | | |
h| stem:[n] h| laser line h| line h| [isotope] h| [stem:[f_n − f {R(10)}] stem:[//rm(kHz)]] h| stem:[u_c] stem:[//rm(kHz)] h| [stem:[ f (rm(OsO)_{4})] stem:[−f (rm(CO)_{2}) //rm(kHz)]] h| stem:[u_c] stem:[//rm(kHz)]

| stem:[1] | P(22) | P(74)A1(5) | [192] | stem:[−802127930.98] | stem:[0.09] | stem:[−12149.5] | 0.2
| stem:[2] | P(20) | _not identified_ | | stem:[−747823325.30] | stem:[0.09] | stem:[9229.6] | 0.2
```

This generated:
<img width="619" alt="Screen Shot 2021-01-07 at 11 10 22 AM" src="https://user-images.githubusercontent.com/11865/103846394-f21bd380-50d8-11eb-87c4-0f9ace70371e.png">

[mep-wgfs-um10_3-OsO4.presentation.xml.zip](https://github.com/metanorma/metanorma-bipm/files/5779290/mep-wgfs-um10_3-OsO4.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
@ronaldtse I've fixed the issue. For `th` cell I've set both top and bottom borders, but need bottom only.

And in adoc you need to remove `h` in first line `h| stem:[""^12 "C"^{16} "O"_2]` to remove bottom border.

After that the resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/103904947-05e22c80-510f-11eb-83e6-c22a598e5dd6.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
> And in adoc you need to remove `h` in first line `h| stem:[""^12 "C"^{16} "O"_2]` to remove bottom border.

I have amended this in the adoc. While I can't verify let's close this for now and reopen when this issue re-appears.
