### ISSUE TITLE
JCGM PDF documents have wrong "subject"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#108]
<img width="366" alt="Screen Shot 2021-01-25 at 9 19 09 AM" src="https://user-images.githubusercontent.com/11865/105650313-64205500-5eee-11eb-94b4-04a73c372c18.png">

The "subject" field shows this:
> ISO 3534-1:2006 defines general statistical terms and terms used in probability which may be used in the drafting of other International Standards. In addition, it defines symbols for a limited number of these terms. ISO 3534-2:2006 defines applied statistics terms, and expresses them in a conceptual framework in accordance with ISO normative terminology practice. Term entries are arranged thematically. An alphabetical index is provided. Standardized symbols and abbreviations are defined.The two principal purposes of ISO 3534-2:2006 are, specifically, to establish a common vocabulary for use throughout ISO/TC 69 standards, together with the broader intent to enhance the preciseness, clarity and cohesiveness in the usage/application of applied statistics generally. The mathematical level has deliberately been kept to a low level in order for the content to be made readily comprehensible to the widest possible readership.

But this text actually comes from the abstract of the ISO 3534-2:2006 reference of this document.

<img width="523" alt="Screen Shot 2021-01-25 at 9 20 19 AM" src="https://user-images.githubusercontent.com/11865/105650369-8e721280-5eee-11eb-8cf5-233063a17e10.png">

Document attached:
[jcgm-104-2009.pdf](https://github.com/metanorma/metanorma-bipm/files/5863626/jcgm-104-2009.pdf)

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/105690391-fd5e6400-5f0c-11eb-994a-4188e0634461.png)

Also, this issue fixed for another xslt.
