### ISSUE TITLE
JCGM references to BIPM/JCGM documents are broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#109]
From this source:

```adoc
[bibliography]
== Normative references

The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

* [[[JCGM1002008,BIPM JCGM 100:2008]]], Evaluation of measurement data -- Guide to the expression of uncertainty in measurement (GUM). Joint Committee for Guides in Metrology.

* [[[JCGM1012008,BIPM JCGM 101:2008]]], Evaluation of measurement data -- Supplement 1 to the "`Guide to the expression of uncertainty in measurement`" -- Propagation of distributions using a Monte Carlo method. Joint Committee for Guides in Metrology.

* [[[JCGM2002008,BIPM JCGM 200:2008]]], International Vocabulary of Metrology -- Basic and general concepts and associated terms, 3rd Edition. Joint Committee for Guides in Metrology

* [[[ISO_3534-1,ISO 3534-1:2006]]], Statistics -- Vocabulary and symbols -- Part 1: General statistical terms and terms used in probability.

* [[[ISO_3534-2,ISO 3534-2:2006]]], Statistics -- Vocabulary and symbols -- Part 2: Applied statistics.

* [[[ISO_3534-3,ISO 3534-3:1999]]], Statistics -- Vocabulary and symbols -- Part 3: Design of experiments.
```

This got generated:
<img width="710" alt="Screen Shot 2021-01-25 at 3 31 42 PM" src="https://user-images.githubusercontent.com/11865/105674408-70bea080-5f22-11eb-8dc4-0ae43f186979.png">

The BIPM/JCGM references are missing. This may be due to an issue with relaton-bipm (ping @andrew2net ), but something may need to be done here, too.

**Comment by ronaldtse** [comment]
In addition, the JCGM boilerplate text differs:

Original:
> The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

Generated:
> The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

**Comment by Intelligent2013** [comment]
> The BIPM/JCGM references are missing.

Issue fixed in JCGM xslt. 
![изображение](https://user-images.githubusercontent.com/5559926/105691921-e456b280-5f0e-11eb-85e2-b0b3497ff4db.png)

But, exactly rendering of bibitem's refers to ticket 'Move citation rendering to Presentation XML' https://github.com/metanorma/metanorma-nist/issues/242

**Comment by opoudjis** [comment]
> In addition, the JCGM boilerplate text differs:

This has been inserted manually: there is no YAML boilerplate defined for normative references right now. There can be, but if there is going to be this level of confusion, I am not lifting a finger to realise it unless I have someone from JCGM swear on their baguette that this is the value of the normative reference prefix. There have been way too many instances of SDO inconsistency for me to do otherwise.

**Comment by ronaldtse** [comment]
JCGM 100: No normative references clause.

JCGM 101:
>  The following referenced documents are indispensable for the application of this document.

JCGM 102:
> The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

JCGM 104:
> The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

JCGM 106:
> The following referenced documents are indispensable for the application of this document.

JCGM 200: No normative reference clause.

**Comment by opoudjis** [comment]
So what do I do? If we're going to respect existing text, we can override a default boilerplate with a `[.boilerplate]` clause, but I'm not convinced that there is a point here, when the boilerplate is being altered at random.

**Comment by opoudjis** [comment]
I need a decision here, @ronaldtse. Putting on hold until I have one.

**Comment by ronaldtse** [comment]
I believe we use this boilerplate as default from JCGM 102 and 104: (is this identical to ISO?)
> The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

The rest we can encode as overrides.

**Comment by opoudjis** [comment]
The given text was identical to current ISO. (It is in fact a globally set template, since ISO is the only spec that defines one.) am overriding it with your suggested text.
