### ISSUE TITLE
indexsect sections

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#110]
As a result of refactoring triggered by https://github.com/metanorma/metanorma-bipm/issues/9, index clauses, which hitherto have been encoded as `<clause type="index">`, will be encoded as `<indexsect>`. Please parse `<indexsect>` for BIPM as you have been processing `<clause type="index">` until now.

**Comment by Intelligent2013** [comment]
mn2pdf and BIPM xslt updated. Done.

**Comment by Intelligent2013** [comment]
To do: parse `indexsect` for JCGM XSLT also.

**Comment by Intelligent2013** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
