### ISSUE TITLE
JCGM 100:2008 (English version): review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#112]
As requested in https://github.com/metanorma/metanorma-bipm/issues/9#issuecomment-779830475, this issue addresses the differences between the original and generated JCGM documents.

Correcting markup issues in this document is in progress (WIP PR #6 created).

1. Front page of the original document contains two additional details: "GUM 1995 with minor corrections" and "September 2008". Which additional document attributes should we use for these?

Original:
![image](https://user-images.githubusercontent.com/55683568/108130192-8ea99c00-70af-11eb-87b9-4984bbdce96e.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108130220-9c5f2180-70af-11eb-8a7a-189bb7d04112.png)

2. Footnote should be "All rights reserved" instead "all_rights_reserved"

Original:
![image](https://user-images.githubusercontent.com/55683568/108106025-b4be4480-708d-11eb-8149-2b4e0815d7a5.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108106071-c43d8d80-708d-11eb-9de3-bfe1fc25dc5b.png)

3. Copyright pages are missing in the generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/108106216-ef27e180-708d-11eb-9cca-780099b74a70.png)

![image](https://user-images.githubusercontent.com/55683568/108106513-55acff80-708e-11eb-82ea-df668c9f5173.png)

4. Appearance of the following page differs.

Original:
![image](https://user-images.githubusercontent.com/55683568/108106351-20a0ad00-708e-11eb-9e67-3f850ad6a78d.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108106319-154d8180-708e-11eb-8555-5cb0fed8ad3c.png)

5. Contents vs. Table of contents.

Original:
![image](https://user-images.githubusercontent.com/55683568/108106628-7e34f980-708e-11eb-81e8-a10d471a11a6.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108106614-77a68200-708e-11eb-9129-dd7e8531bf80.png)

6. Sections order differs.

Original:
![image](https://user-images.githubusercontent.com/55683568/108106761-aae91100-708e-11eb-84bf-6922b54e62cc.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108106719-9d338b80-708e-11eb-84fe-55c9e92352f7.png)

7. Word "Annex" overlaps with the annex title. Ping @Intelligent2013 .

Generated:
![image](https://user-images.githubusercontent.com/55683568/108106892-d66bfb80-708e-11eb-886b-1e7ad8265dcf.png)

8. Foreword generated using `.Foreword` syntax is not generated as a section (doesn't have a title and cannot be cross-referenced).

9. References vs. Bibliography and Index vs. alphabetical index.

Original:
![image](https://user-images.githubusercontent.com/55683568/108108682-39f72880-7091-11eb-9963-6f5f5f093222.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108108757-56936080-7091-11eb-82a4-af8f5b901e31.png)

10. Original document doesn't have an edition information in the title on the main page.

Original:
![image](https://user-images.githubusercontent.com/55683568/108109098-c0136f00-7091-11eb-87ee-af577b637e1b.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108109056-b5f17080-7091-11eb-93e7-37a094f377e4.png)

11. Clause vs. Chapter.

Original:
![image](https://user-images.githubusercontent.com/55683568/108111077-7d9f6180-7094-11eb-925c-7b37ecbd4e94.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108111036-71b39f80-7094-11eb-9648-be348aa314df.png)

12. `alt:[]` terms should probably be boldfaced by default.

Original:
![image](https://user-images.githubusercontent.com/55683568/108123576-5ea9cb00-70a6-11eb-90a2-11aa5d176a23.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108123594-68333300-70a6-11eb-92d0-0c340a01d7e4.png)

13. Annexes of the original document are numbered with letters (A, B, C, etc.), while generated document uses Arabic numbers.

14. Annex title is shown below the annex number in the generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/108129325-53f33400-70ae-11eb-8f8f-4bbe4c2976be.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108129298-4a69cc00-70ae-11eb-8d72-ee0932e01735.png)

15. Text starts in the same paragraph as the section number for the untitled sections in the original document, which can be seen in the images above.

**Comment by anermina** [comment]
After reviewing JCGM 104:2009, I can confirm that following differences are present in this document as well: 2, 3, 5, 7, 9-11, 13, 15.

Regarding the other differences reported in this ticket, here are the new notices:

1. Details about the date are missing in this document as well, but the original doesn't contain any information above the document identifier, unlike JCGM 100:2008.

4. No significant differences in style. However, there is a difference in header - generated doc contains information in French as well.

Original:
![image](https://user-images.githubusercontent.com/55683568/108417023-c2abcb00-722f-11eb-8f86-6b5f8df22932.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108417049-c9d2d900-722f-11eb-99e3-0d86bac24195.png)

14. Original JCGM 104:2009 doc has a different style than JCGM 100:2008 when it comes to annexes. It also differs from the generated doc. I need more documents to find a rule that should be applied.

Other differences will be reported in a separate ticket, since this one is already too long.

**Comment by Intelligent2013** [comment]
> 7. Word "Annex" overlaps with the annex title. Ping @Intelligent2013 .

Fixed (but Appendix instead Annex, it's presentation xml value).

![изображение](https://user-images.githubusercontent.com/5559926/108631292-37724580-747a-11eb-9ccf-71c77ccf2309.png)

**Comment by opoudjis** [comment]
1. "GUM 1995 with minor corrections" is an indication that this document is a reissue of GUM: _Guide to the Expression of Uncertainty in Measurement_, from 1995. We could express this as an "updates" link, but the description is too idiosyncratic. I'm going to make up a `:title-provenance:`, to be rendered in XML as `//bibdata/title[@type = 'provenance']`

The first edition date should be entered as `:date-published: 2008-09`.

**Comment by opoudjis** [comment]
2. Including "all_rights_reserved" text in BIPM YAML.

**Comment by opoudjis** [comment]
3. Inconsistencies in boilerplate between JCGM documents are not something I will address without guidance from JCGM. The specific reference to individual documents in the boilerplate is to be avoided, and we already got BIPM to agree to this for their boilerplate. Bilingual boilerplate is not used in other JCGM documents we have seen, and I would also expect guidance on that.

**Comment by opoudjis** [comment]
4. Matter for PDF.

**Comment by opoudjis** [comment]
5. Included different "table_of_contents" text in BIPM YAML; confirmed with BIPM Brochure.

**Comment by opoudjis** [comment]
6. This document follows ISO in putting the Introduction in the preface. We do not follow that default in BIPM proper, but JCGM is essentially ISO, so we will follow it in the case of JCGM.

The discomfort with JCGM documents in general is that they are BIPM documents which follow ISO formatting.

**Comment by opoudjis** [comment]
8. The problem is that Foreword only works with the recommended Asciidoctor markup if it used before any sections. You are using `.Foreword` after the Preface section `== Preliminary content`, so the `.Foreword` is not going to get any special formatting. Fixed by making the foreword an explicit section.

**Comment by opoudjis** [comment]
9. I would recommend treating "alphabetical index" as user supplied text and not the canonical auto-generated label for the index.

The Bibliography is having its given title overridden as "References". That's inherited, and good practice for ISO, which has a canonical title; it's not appropriate for BIPM, and I'm suppressing it.

**Comment by opoudjis** [comment]
10. I don't think we should attempt to normalise the rendering of editions without more information from JCGM. But if there is no mention of "edition 1" in the original, removing `:edition: 1` from the document attributes will remove it from the rendered document.

**Comment by opoudjis** [comment]
11. JCGM is following ISO rather than BIPM conventions for clause cross-referencing.

**Comment by opoudjis** [comment]
12. Since ISO does not boldface alt terms, and JCGM is attempting to emulate ISO, I'd like confirmation from JCGM.

**Comment by opoudjis** [comment]
13. BIPM uses arabic numbering, JCGM follows ISO in using letters.

**Comment by opoudjis** [comment]
14. JCGM inherits metanorma default (ISO) rendering of annex names.

**Comment by opoudjis** [comment]
15. Will use `clause/@inline-header` to signal such untitled subclauses in JCGM documents, as has been done elsewhere.

**Comment by opoudjis** [comment]
Handing over to @Intelligent2013 for rendering fixes

**Comment by Intelligent2013** [comment]
> 4. Appearance of the following page differs

@anermina  actually there are two kinds of such pages.

1st kind - the page from JCGM 100:2008:
![image](https://user-images.githubusercontent.com/5559926/113599655-91545680-9647-11eb-9c19-d45fe12d9563.png)

2nd kind - the page from JCGM 104:2009:
![image](https://user-images.githubusercontent.com/5559926/113599692-a0d39f80-9647-11eb-967f-501676dff07b.png)

The current version of JCGM XSLT generates page of 2nd kind. Please inform me if I need to modify xslt to generate 1st kind of page instead of 2nd.

**Comment by Intelligent2013** [comment]
JCGM XSLT updated for fixing issues 1, 10, 12, 14 and 15.
Resulted PDF: 
[document.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/6259703/document.presentation.pdf)

**Comment by opoudjis** [comment]
@anermina please review. Adding HTML.

[document.html.zip](https://github.com/metanorma/metanorma-bipm/files/6266387/document.html.zip)

**Comment by anermina** [comment]
> The current version of JCGM XSLT generates page of 2nd kind. Please inform me if I need to modify xslt to generate 1st kind of page instead of 2nd.

@Intelligent2013 Since this is an inconsistency in JCGM documents, I believe it is fine to keep the current version for now.

**Comment by anermina** [comment]
> The first edition date should be entered as `:date-published: 2008-09`.

@opoudjis  Although first edition date was added via `:date-published: 2008-09` to source .adoc, this information is still not present on the front page.

>The discomfort with JCGM documents in general is that they are BIPM documents which follow ISO formatting.

In the original document, Introduction is numbered as clause 0, having subclauses 0.1, 0.2, etc. There is no numeration in generated document. Was this done on purpose, due to following ISO formatting?

The rest of the fixes seem good. 

While reviewing the outputs, I've noticed several other issues. Since this ticket is already too long, I've reported them separately (#125, #126, #127, #128, #129, #130, #131, #132, #133). Generally, if you prefer separating all issues in regard to the same document as separate tickets, please let me know.

**Comment by anermina** [comment]
#125, #128, #129, #130 and #132 are solved.

Remaining: #126, #127, #131 and #133.

**Comment by opoudjis** [comment]
@anermina I actually prefer fewer issues rather than more, but all good. 

The issue with date published on the front cover presumably involves @Intelligent2013 ? 

I will address the introduction numbering, and then close this issue, since the others are opened.

**Comment by Intelligent2013** [comment]
git clone https://github.com/metanorma/mn-samples-jcgm

**Comment by Intelligent2013** [comment]
> The issue with date published on the front cover presumably involves @Intelligent2013 ?

@opoudjis in https://github.com/metanorma/mn-samples-jcgm/blob/master/sources/jcgm/100-2008-en/document.adoc there is `:date-published: 2008-09`, but in document.presentation.xml there isn't this date at all:
```xml
<bibdata type="standard">
<title language="en" format="text/plain" type="main">Evaluation of measurement data</title>
<title language="en" format="text/plain" type="part">Guide to the expression of uncertainty in measurement</title>
<title language="en" format="text/plain" type="provenance">GUM 1995 with minor corrections</title>
<title language="fr" format="text/plain" type="main">&#201;valuation des donn&#233;es de mesure</title>
<title language="fr" format="text/plain" type="part">Guide pour l&#8217;expression de l&#8217;incertitude de mesure</title>
<docidentifier type="BIPM">JCGM 100</docidentifier>
<docnumber>100</docnumber>
<contributor>
<role type="author"/>
<organization>
<name>Bureau International des Poids et Mesures</name>
<abbreviation>BIPM</abbreviation>
</organization>
</contributor>
<contributor>
<role type="publisher"/>
<organization>
<name>Bureau International des Poids et Mesures</name>
<abbreviation>BIPM</abbreviation>
</organization>
</contributor>
<edition>1</edition>
<version>
<revision-date/>
</version>
<language current="true">en</language>
<script current="true">Latn</script>
<status>
<stage language="">in-force</stage>
</status>
<copyright>
<from>2008</from>
<owner>
<organization>
<name>Bureau International des Poids et Mesures</name>
<abbreviation>BIPM</abbreviation>
</organization>
</owner>
</copyright>
<ext>
<doctype language="">guide</doctype>
<editorialgroup>
<committee acronym="JCGM">
Joint Committee for Guides in Metrology
Comit&#233; commun pour les guides en m&#233;trologie
</committee>

</editorialgroup>

<structuredidentifier>
<docnumber>100</docnumber>
</structuredidentifier>
</ext>
</bibdata>
```

**Comment by opoudjis** [comment]
Sorry, my bad: @anermina : that should have been `:published-date: 2008-09`.

**Comment by opoudjis** [comment]
@anermina Please confirm fixes

**Comment by anermina** [comment]
@opoudjis I reviewed the outputs. Please check my comments below.

> I will address the introduction numbering, and then close this issue, since the others are opened.

We actually need inline numbering here. Currently, text is generated below the section number.

Generated:
![image](https://user-images.githubusercontent.com/55683568/116615279-59d18500-a93b-11eb-9e94-a1f29f35827d.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/116615301-61912980-a93b-11eb-92ee-d32334ce28c7.png)

> 9. I would recommend treating "alphabetical index" as user supplied text and not the canonical auto-generated label for the index.

Fix added to PR #13.

#131 It seems we still have inline numbering for terms.

Generated:
![image](https://user-images.githubusercontent.com/55683568/116616881-7cfd3400-a93d-11eb-8da7-ffa8561f5193.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/116616910-87b7c900-a93d-11eb-945c-47ee29f28c66.png)

#127 I'm still getting notation Figure 1-1, although I'm using metanorma-bipm in Gemfile...

Generated:
![image](https://user-images.githubusercontent.com/55683568/116623775-08c78e00-a947-11eb-9f0f-90b225c4e330.png)

> @anermina I actually prefer fewer issues rather than more, but all good.

Thanks for letting me know. I'll make it that way in the future.

**Comment by anermina** [comment]
Summary of differences to be checked with JCGM:

> > 3. Copyright pages are missing in the generated document.
> 
> Inconsistencies in boilerplate between JCGM documents are not something I will address without guidance from JCGM. The specific reference to individual documents in the boilerplate is to be avoided, and we already got BIPM to agree to this for their boilerplate. Bilingual boilerplate is not used in other JCGM documents we have seen, and I would also expect guidance on that. Not currently fixing..

4. There are two different kinds of the intro page. It would be good to have a confirmation from JCGM that the currently used one is correct.

> > 12. alt:[] terms should probably be boldfaced by default.
> 
> Since ISO does not boldface alt terms, and JCGM is attempting to emulate ISO, I'd like confirmation from JCGM.

**Comment by anermina** [comment]
@Intelligent2013 could you please check my comments below?

15. Can Table H.9 be in landscape, because it cannot fit to page in portrait orientation? Following is used in source .adoc:
`[%landscape]`
`<<<`

Generated:
![image](https://user-images.githubusercontent.com/55683568/116621965-3d861600-a944-11eb-9e2b-1a865d1db194.png)

16. Not all the text is justified in PDF. For example, notes are, but some of the text around them is not:
![image](https://user-images.githubusercontent.com/55683568/116624289-fc900080-a947-11eb-8e63-d568ce5ec8b5.png)

**Comment by Intelligent2013** [comment]
> 15. Can Table H.9 be in landscape, because it cannot fit to page in portrait orientation?

At this time JCGM xslt doesn't support page orientation change (actually BIPM and IHO only support it). I have to make full refactoring of xslt to support it, and it will take a long time. JCGM xslt developed to support n-column layout and introducing horizontal page orientation will complicate all solution.
As workaround solution I propose to scale a math to fit into table cell:
![image](https://user-images.githubusercontent.com/5559926/116788290-6bd53400-aab1-11eb-983d-24710f98cc27.png)

(xslt updated yet)

> 16. Not all the text is justified in PDF. For example, notes are, but some of the text around them is not:

Clauses with inlined header were not justified in xslt. Fixed:

![image](https://user-images.githubusercontent.com/5559926/116788402-046bb400-aab2-11eb-8947-0a9cd8d2d83d.png)

**Comment by opoudjis** [comment]
I'm sorry it's taking this long to cycle back on these; there's a lot on.

> @opoudjis I reviewed the outputs. Please check my comments below.
> 
> > I will address the introduction numbering, and then close this issue, since the others are opened.
> 
> We actually need inline numbering here. Currently, text is generated below the section number.
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/116615279-59d18500-a93b-11eb-9e94-a1f29f35827d.png)
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/116615301-61912980-a93b-11eb-92ee-d32334ce28c7.png)

Fixed. Easy for me to forget that introductions under ISO (and hence JCGM) also have subclauses.

> #131 It seems we still have inline numbering for terms.
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/116616881-7cfd3400-a93d-11eb-8da7-ffa8561f5193.png)
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/116616910-87b7c900-a93d-11eb-945c-47ee29f28c66.png)

Cannot confirm in HTML:

<img width="672" alt="Στιγμιότυπο 2021-05-20, 00 38 03" src="https://user-images.githubusercontent.com/1911039/118832174-bf45df80-b903-11eb-8db8-84954e166511.png">

<img width="810" alt="Στιγμιότυπο 2021-05-20, 00 38 20" src="https://user-images.githubusercontent.com/1911039/118832193-c371fd00-b903-11eb-995e-c231fa1d37fb.png">
 
> #127 I'm still getting notation Figure 1-1, although I'm using metanorma-bipm in Gemfile...
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/116623775-08c78e00-a947-11eb-9f0f-90b225c4e330.png)

Cannot confirm: 

<img width="1252" alt="Στιγμιότυπο 2021-05-20, 00 40 15" src="https://user-images.githubusercontent.com/1911039/118832458-fb794000-b903-11eb-8407-9efba3ca2048.png">

You may have been working with an un-updated metanorma-bipm

**Comment by anermina** [comment]
I can confirm the fixes made by @opoudjis and @Intelligent2013. Closing.
