### ISSUE TITLE
JCGM 104:2009 (English version) review, continues #112

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#113]
Differences noticed between the original and generated documents are listed below.

1. Cross-references to specific clauses, notes etc. of some external document differ. I believe we need square brackets here and it seems word "Clause" is not positioned properly, if it is needed at all.

Original:
![image](https://user-images.githubusercontent.com/55683568/108418092-0ce17c00-7231-11eb-8799-987a0b04b5bd.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108418316-592cbc00-7231-11eb-9253-2850834de567.png)

2. "Equation" is written with capital "E" in generated and with small "e" in the original document. The same applies for "F" in "Figure". However, capitals are used in the original JCGM 100:2008 as well. I believe our outputs are correct here.

Original:
![image](https://user-images.githubusercontent.com/55683568/108418855-10293780-7232-11eb-81c1-28520eae8fc8.png)
![image](https://user-images.githubusercontent.com/55683568/108420163-b7f33500-7233-11eb-8ad1-d7ad9d135678.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108418796-fee02b00-7231-11eb-9427-c1b16138a8a7.png)
![image](https://user-images.githubusercontent.com/55683568/108420134-ab6edc80-7233-11eb-9ef2-bde6ee00519e.png)

3. "Section" vs. no keyword for cross-referencing sections. The same is present in JCGM 100:2008.

Original:
![image](https://user-images.githubusercontent.com/55683568/108419135-72823800-7232-11eb-95da-2d2c08ba7474.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/108419104-68603980-7232-11eb-90d0-a5e07faea3ec.png)

**Comment by ronaldtse** [comment]
Thanks @anermina for the review! I believe other than 1, 2 and 3 are fine. 

For 1 are three issues:
- JCGM is not part of BIPM (the secretariat is BIPM), so it’s documents should be cited as “JCGM”
- two particular JCGM documents have acronyms: the VIM and the GUM. We may not want to display that in a reference. 
- a term clause in the ISO sense is NOT a clause, and should not have the “Clause” prefix, as described by ISO/CS in https://github.com/metanorma/metanorma-iso/issues/471

**Comment by opoudjis** [comment]
> a term clause in the ISO sense is NOT a clause, and should not have the “Clause” prefix, as described by ISO/CS in metanorma/metanorma-iso#471

That's actually not the principle at work here; the principle at work is that a term clause is a subclause, and subclauses in ISO are not prefixed with "Clause" in general.

**Comment by opoudjis** [comment]
3 has already been addressed. 2 we are ignoring.
