### ISSUE TITLE
GHA Ubuntu Arial failure

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#114]
https://github.com/metanorma/metanorma-bipm/runs/1950852131?check_suite_focus=true

**Comment by ronaldtse** [comment]
Is this issue still present?

**Comment by ronaldtse** [comment]
Looks like it's gone, closing.
<img width="1213" alt="Screenshot 2021-04-19 at 3 51 51 PM" src="https://user-images.githubusercontent.com/11865/115200773-274baf00-a127-11eb-8dc8-80afc12266c4.png">
