### ISSUE TITLE
JCGM 101:2008-en: review

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#116]
Following with JCGM review, these are the issues to address in relation to JCGM 101:2008-en. 
I did not include other issues that were already reported by Nermina in https://github.com/metanorma/metanorma-bipm/issues/112.

1. Introduction prefatory section doesn't show in the table of contents.

*Generated:*
![issue1](https://user-images.githubusercontent.com/33627611/109521361-9be96200-7a83-11eb-9319-24dd84a0ecbd.PNG)

2. When there are more than one bibliographic reference in a row, these are enclosed in individual brackets. But in original source, they are enclosed in one bracket as a group.

*Generated:*
![issue2-generated](https://user-images.githubusercontent.com/33627611/109520363-89baf400-7a82-11eb-978f-0e1be2116c50.PNG)

*Original:*
![issue2-original](https://user-images.githubusercontent.com/33627611/109520384-8fb0d500-7a82-11eb-9963-7ece6d495060.PNG)

3. In original documents, appendixes are referred as "Annexes", numbered by letters. Not the same as in generated.

*Generated:*
![issue3-generated](https://user-images.githubusercontent.com/33627611/109521266-82e0b100-7a83-11eb-8c01-c2dfff67e65f.PNG)

*Original:*
![issue3-original](https://user-images.githubusercontent.com/33627611/109521282-86743800-7a83-11eb-879e-2218ca23b097.PNG)

4. In terms and definitions section, reference terms are shown in a different format. Instead of "SOURCE:", it puts "Adapted from"

*Generated:*
![issue4-generated](https://user-images.githubusercontent.com/33627611/109523498-ce945a00-7a85-11eb-824c-a403b00ef083.PNG)

*Original:*
![issue4-original](https://user-images.githubusercontent.com/33627611/109523518-d3590e00-7a85-11eb-80b4-01f8206ccbe0.PNG)

5. Normative reference section is not shown in the correct spot. It gets moved to the first position (before scope) instead of the second. The boilerplate differs too.

*Generated:*
![issue5-generated](https://user-images.githubusercontent.com/33627611/109526275-c2f66280-7a88-11eb-9226-fce0c8372483.PNG)

*Original:*
![issue5-original](https://user-images.githubusercontent.com/33627611/109526296-c8ec4380-7a88-11eb-96fb-6c11c6037826.PNG)

6. Bold symbols in math environment render in upright form. According to source, they need to be italicized as well.

*Generated:*
![issue6-generated](https://user-images.githubusercontent.com/33627611/109526830-634c8700-7a89-11eb-93a1-5ce7a34a9810.PNG)

*Original:*
![issue6-original](https://user-images.githubusercontent.com/33627611/109526843-6778a480-7a89-11eb-9ed0-9d6c29c0586b.PNG)

**Comment by opoudjis** [comment]
5. Because this gem inherits from BIPM, we do not give the title "Normative references" any special processing; to get the normative references positioned in spot 2, I'm changing the markup to put in an explicit "normative=true" flag.

The boilerplate for normative references may be inconsistent in JCGM, and I won't update it unless we have a finding of a consistent preference

**Comment by opoudjis** [comment]
Ah. "Scope" isn't recognised as a title, because it is being followed by index terms.

**Comment by opoudjis** [comment]
6. Well, you did explicitly put those terms as `stem:[f(bb(X))]`; `bb` is going to be treated as bold and not bold italic, because the MathML parser is not going to be clever to override an explicit font style with inherited italics, nor should it. Inserting explicit `bii(X)` instead.

**Comment by opoudjis** [comment]
4. I'm just replacing "SOURCE:" with "Adapted from", in the BIPM localisation; @Intelligent2013, you will need to strip the colon, currently I am doing this in isodoc output, not Presentation XML. I may yet be asked to make the string less similar to ISO, by removing the "modified"; but since JCGM is meant to be a version of ISO to begin with, I'm reluctant to.

**Comment by opoudjis** [comment]
1. Has been addressed already.

**Comment by opoudjis** [comment]
2. Addressed in Presentation XML
