### ISSUE TITLE
Dir.chdir intervening with byebug

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#118]
byebug writes and reads files from the local directory. However, as a result of the recent addition of temp directory processing in https://github.com/metanorma/metanorma-bipm/pull/115, byebug no longer finds the expect config files in the new temp directory:

````
        No such file or directory @ rb_sysopen - /private/var/folders/0x/fm2y9npj3jv50lx9xgwnnmr00000gs/T/rspec-20210304-94898-jdq7zp/.byebug_history
````

From debugging, it turns out that the first example runs fine, the second example creates a brand new temp directory as expected; but byebug then still looks for its temp files in the *first* temp directory, which no longer exists. It would seem that byebug is a process launched when first hit in an example, and then keeps running during rspec, configured to use the directory it was first run in.

I'm trying to debug the generation of JCGM with the gem under temp directory, but of course this is preventing me doing debugging at all; and the stickiness of the first temp directory under rspec may be influencing other bits of code.

**Comment by CAMOBAP** [comment]
@opoudjis looks like I missed somethig, here is my steps:

1. Local diff
   ```ruby
    index 23f6c9d..d7450e2 100644
    --- a/spec/metanorma/processor_spec.rb
    +++ b/spec/metanorma/processor_spec.rb
    @@ -35,6 +35,7 @@ RSpec.describe Metanorma::BIPM::Processor do
       end

       it "generates HTML from IsoDoc XML" do
    +    byebug
         input = <<~"INPUT"
           <bipm-standard xmlns="https://metanorma.org/ns/bipm">
             <sections>
    diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
    index f987120..065652f 100644
    --- a/spec/spec_helper.rb
    +++ b/spec/spec_helper.rb
    @@ -13,6 +13,8 @@ require "equivalent-xml"
     require "htmlentities"
     require "rexml/document"

    +require "byebug"
    +
     RSpec.configure do |config|
       # Enable flags like --only-failures and --next-failure
       config.example_status_persistence_file_path = ".rspec_status"
    @@ -24,7 +26,7 @@ RSpec.configure do |config|
         c.syntax = :expect
       end

    -=begin
    +
       config.around do |example|
         Dir.mktmpdir("rspec-") do |dir|
           if File.exists?(".byebug_history")
    @@ -33,7 +35,7 @@ RSpec.configure do |config|
           Dir.chdir(dir) { example.run }
         end
       end
    -=end
    +
     end

     def metadata(hash)
   ```
2. `bundle install`
3. `bundle exec bin/rspec --format doc`
4. it stops on `byebug` call in `spec/metanorma/processor_spec.rb`
5. input "continue" and tests finished without any errors

I have repeated those steps 2-3 times, no error observed

Ruby version: 2.6.6p146

**Comment by opoudjis** [comment]
To replicate the issue, insert the byebug not inside the spec file, but inside the code it is running -- for example, the start of "clause_parse" in metanorma-iso/lib/asciidoctor/iso/section.rb. The metanorma code is what is creating byebug history files that the rspec cannot access from Tempfile. Presumably rspec keeps track of its own byebug calls.

**Comment by CAMOBAP** [comment]
@opoudjis thanks for the details, I was able to reproduce the issue. At the moment I see several options:
 - `~/.byebugrc` with `set noautosave`
 - `~/.byebugrc` with `set histfile /Users/USERNAME/.byebug_history` - env vars or `~` doesn't supported
 - Override [`Byebug::HistfileSetting::DEFAULT`](https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/settings/histfile.rb#L10)  https://github.com/metanorma/metanorma-bipm/pull/143

**Comment by opoudjis** [comment]
Oh, I see. Byebug history is a nice to have; I can do ~/.byebugrc with set noautosave
