### ISSUE TITLE
JCGM 100:2008 (EN): Minus sign as a subscript (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#125]
In equations, minus sign in subscript is really small in comparison to the original document. Can this be fixed in PDF?
Of course, I can try using em dashes instead, if that would be more appropriate solution.

Original:
![image](https://user-images.githubusercontent.com/55683568/113757735-40119900-9713-11eb-91e7-f81caa68264c.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113757698-36883100-9713-11eb-892f-fe1902a64e9d.png)

**Comment by Intelligent2013** [comment]
There are two kind of 'minus'. In "Stix Two Math" font they display so:
![image](https://user-images.githubusercontent.com/5559926/113891490-cab6ce80-97cd-11eb-9714-a1eb1f919564.png)
![image](https://user-images.githubusercontent.com/5559926/113891609-e02bf880-97cd-11eb-87b6-98ea0da229bc.png)

Minus sign will display so:
![image](https://user-images.githubusercontent.com/5559926/113892316-8bd54880-97ce-11eb-9fe4-dd95723cfb4a.png)

**Comment by anermina** [comment]
Thanks @Intelligent2013 , I'll make changes in source files accordingly. Closing.

**Comment by anermina** [comment]
Actually, reopening to assign myself for this task.

**Comment by anermina** [comment]
Changes are applied in PR https://github.com/metanorma/mn-samples-jcgm/pull/13. Closing.
