### ISSUE TITLE
JCGM 100:2008 (EN): Footnotes in titles (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#128]
Footnote number is not superscripted when footnote is a part of the title of some clause/subclause. This footnote (its actual content) doesn't get generated in PDF at all.

Original:
![image](https://user-images.githubusercontent.com/55683568/113767234-bcf64000-971e-11eb-9d1d-5553606b2c3a.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113767191-a94ad980-971e-11eb-8fec-5cb67d6748d5.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/113902894-102cc900-97d9-11eb-8b05-95168be468ea.png)
