### ISSUE TITLE
JCGM 100:2008 (EN): Equations added in tables are shifted (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#129]
Some of the equations inserted in tables are misplaced in PDF.

Original:
![image](https://user-images.githubusercontent.com/55683568/113769122-e617d000-9720-11eb-8abb-b6f38b725d9d.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113769087-de582b80-9720-11eb-9c90-7e262dba20ec.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/113902819-fa1f0880-97d8-11eb-9f39-44c331da0921.png)

**Comment by anermina** [comment]
Looks good! Thank you.
