### ISSUE TITLE
JCGM 100:2008 (EN): Generating examples (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#130]
Text is written inline after the "example" keyword in the original document.

Original:
![image](https://user-images.githubusercontent.com/55683568/113757348-c8dc0500-9712-11eb-9229-b57cd3c3d7a9.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113757423-dee9c580-9712-11eb-9a69-97b6ca5a8153.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/113902659-cf34b480-97d8-11eb-87ef-40283833aa61.png)

**Comment by anermina** [comment]
Thanks! Closing.
