### ISSUE TITLE
JCGM 100:2008 (EN): Generating subclause titles (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#131]
In case of annexes and Terms and Definitions clause, subclause titles are written below their corresponding numbers in the original document.

Original:
![image](https://user-images.githubusercontent.com/55683568/113756571-d93fb000-9711-11eb-9639-d5750f34a28c.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113756602-e197eb00-9711-11eb-8586-f9d6341a6f1a.png)

**Comment by opoudjis** [comment]
First issue: inherit ISO formatting for term headers in HTML.

Second issue: Appendix 2 also contains terms. This is not expected in ISO or BIPM, and the terms are not being recognised as such.

**Comment by opoudjis** [comment]
Made Appendixes 2 and 3 terms sections be recognised as terms sections, by inserting `[heading=terms]` markup.

Standoc is constrained to recognise terms sections only at top level, and only once. Relaxing that in BIPM.
