### ISSUE TITLE
JCGM 100:2008 (EN): Overlapping equations' notation (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#132]
Due to the larger indentation before math expressions, equation H.22b overlaps its notation.

Original:
![image](https://user-images.githubusercontent.com/55683568/113769452-49a1fd80-9721-11eb-9656-61aa2bfc6ccc.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113769356-32631000-9721-11eb-8e6c-0fd89732af3c.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/113902471-97c60800-97d8-11eb-9347-56906f37673d.png)

**Comment by anermina** [comment]
Looks good now. Thank you!
