### ISSUE TITLE
JCGM 100:2008 (EN): Skipping letter "I" for annexes (continues #112)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#133]
Some flavors are not using "I" when numbering appedices/annexes, due to Roman "I" and special usage of Roman numbering. This original JCGM document skips "I" as well and uses "J" instead. Should we skip "I" for JCGM?

Original:
![image](https://user-images.githubusercontent.com/55683568/113770052-faa89800-9721-11eb-9992-a122d6dd2d02.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/113770040-f54b4d80-9721-11eb-9c65-643df23d7fda.png)

**Comment by opoudjis** [comment]
Yes
