### ISSUE TITLE
"SI badge" attribute for "SI brochure appendices" or "Mise en pratique" to indicate type of SI the document applies to

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#14]
We should have a document attribute called `:si-aspect:` that allows selection of the SI logo.

All aspects:

<img width="491" alt="Screen Shot 2020-09-29 at 12 18 59 AM" src="https://user-images.githubusercontent.com/11865/94459032-61844c00-01e9-11eb-8662-e10ed8ee135a.png">

SI Second:
<img width="520" alt="Screen Shot 2020-09-29 at 7 14 53 AM" src="https://user-images.githubusercontent.com/11865/94495106-7b428500-0223-11eb-9a59-e533d9122766.png">

The full matrix:

<img width="941" alt="Screen Shot 2020-09-29 at 7 15 20 AM" src="https://user-images.githubusercontent.com/11865/94495129-8b5a6480-0223-11eb-83fd-00764ce01ed9.png">

SVGs: [Archive.zip](https://github.com/metanorma/metanorma-bipm/files/5295542/Archive.zip)

attribute value | image
-- | --
A_e_deltanu | ![SI Illustration Constants Colour A_e_delta nu](https://user-images.githubusercontent.com/11865/94495619-dcb72380-0224-11eb-8162-95009d972673.png)
A_e | ![SI Illustration Constants Colour A_e](https://user-images.githubusercontent.com/11865/94495621-de80e700-0224-11eb-9386-5ccef8889d08.png)
cd_Kcd_h_delta nu | ![SI Illustration Constants Colour cd_Kcd_h_delta nu](https://user-images.githubusercontent.com/11865/94495623-df197d80-0224-11eb-8c7e-76300a12b529.png)
cd_Kcd | ![SI Illustration Constants Colour cd_Kcd](https://user-images.githubusercontent.com/11865/94495624-df197d80-0224-11eb-8cef-acf4e5634199.png)
full | ![SI Illustration Constants Colour Full](https://user-images.githubusercontent.com/11865/94495625-dfb21400-0224-11eb-80d6-a363956a89b9.png)
K_k_delta nu | ![SI Illustration Constants Colour K_k_delta nu_h](https://user-images.githubusercontent.com/11865/94495627-e04aaa80-0224-11eb-895a-11d2998a1025.png)
K_k | ![SI Illustration Constants Colour K_k](https://user-images.githubusercontent.com/11865/94495629-e04aaa80-0224-11eb-9c63-15c3c604a613.png)
kg_h_c_deltanu | ![SI Illustration Constants Colour kg_h_c_delta nu](https://user-images.githubusercontent.com/11865/94495632-e0e34100-0224-11eb-9255-65b7c2934834.png)
kg_h | ![SI Illustration Constants Colour kg_h](https://user-images.githubusercontent.com/11865/94495634-e17bd780-0224-11eb-98dc-c0eafa99537c.png)
m_c_delta nu | ![SI Illustration Constants Colour m_c_delta nu](https://user-images.githubusercontent.com/11865/94495638-e2146e00-0224-11eb-8ac9-ceda9ca8731e.png)
m_c | ![SI Illustration Constants Colour m_c](https://user-images.githubusercontent.com/11865/94495640-e2ad0480-0224-11eb-8344-8132e0333c97.png)
mol_NA | ![SI Illustration Constants Colour mol_NA](https://user-images.githubusercontent.com/11865/94495641-e2ad0480-0224-11eb-9579-df785b81cb54.png)
s_delta nu | ![SI Illustration Constants Colour s_delta nu](https://user-images.githubusercontent.com/11865/94495643-e3459b00-0224-11eb-97b3-c203f5ed80c2.png)

Original EPS: https://www.bipm.org/utils/common/img/rev-si/SI-4-eps.zip

**Comment by opoudjis** [comment]
Added to XML as /bibdata/ext/si-aspect. deltanu consistently given as one word.

**Comment by opoudjis** [comment]
The online publication of mises en pratiques, https://www.bipm.org/en/publications/mises-en-pratique/, has left out the cover pages from their PDFs, so I don't have evidence these are used at all. I am guessing that each mise en pratique has only the shading of its primary unit and constant.

**Comment by ronaldtse** [comment]
> The online publication of mises en pratiques, https://www.bipm.org/en/publications/mises-en-pratique/, has left out the cover pages from their PDFs, so I don't have evidence these are used at all. I am guessing that each mise en pratique has only the shading of its primary unit and constant.

BIPM will publish new versions of them using Metanorma.

**Comment by opoudjis** [comment]
In that case, I'm going to shove a version of the logo into the existing HTML.
