### ISSUE TITLE
Comma character after quote causes wrong right double quote

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#147]
From @manuel489:

> *In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*
> 
> From BIPM:
> ![issue15](https://user-images.githubusercontent.com/33627611/121970530-c1555f80-cd44-11eb-9a1b-fe582db4eed9.PNG)
> 
> (I think this is a known issue already.)

From @Intelligent2013:

> this issue occurs due char comma after quote.
> MN xml:
> ```xml
> &#8220;ppb<bookmark id="..."/>&#8221; and &#8220;ppt<bookmark id="..."/>&#8220;,
> ```
> If we add space after quote and before comma (just for experiment)
adoc:
> ```
> "((ppb))" and "((ppt))" ,
> ```
> then last quote is ok:
> ```xml
> &#8220;ppb<bookmark id="_..."/>&#8221; and &#8220;ppt<bookmark id="..."/>&#8221; ,
> ```

_Originally posted by @Intelligent2013 in https://github.com/metanorma/bipm-si-brochure/issues/130#issuecomment-862561306_

**Comment by opoudjis** [comment]
I can keep fiddling with smart quote detections to deal with more and more edge cases, but it is clearly far more sustainable to put smart quotes into the source text to begin with. This isn't 1980, and there is no ASCII constraint on the text.

**Comment by opoudjis** [comment]
Smartquote detection works on text spans in the XML; so confronted with `"text<tag/>" and`, the smartquote detector processes separately `"text` and `" and`.

The solution here is to detect any instances of `\S<tag/>"[punct]*` and transform them into `\S"[punct]*<tag/>`, which is... unpleasant.
