### ISSUE TITLE
Treatment of notes in brochure

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#15]
The treatment of note material in the BIPM brochure is monstrously inconsistent. @ronaldtse is seeking clarification from BIPM, but I will be astonished if we do not end up forced to introduce a sidebar/inline/footnote rendering attribute.

The current issues are as follows. If anyone adds an issue or discussion without a number to indicate the current issue....

I am retaining numbering from https://github.com/metanorma/metanorma-bipm/issues/1 . Page references to the English PDF: https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf

(9) There are sidebar notes with asterisks, which is consistent with footnote rendering:

![изображение](https://user-images.githubusercontent.com/5559926/94462964-edd04800-01c4-11eb-89fd-4500bf5168b7.png)

(p. 159)

They are currently marked up as notes in the source XML, which does not allow anchoring to a location, nor asterisk place markers.

(10) There is an inline note which is not a sidebar note:

![изображение](https://user-images.githubusercontent.com/5559926/94488804-f8ea9e80-01eb-11eb-936a-30e13a123d8c.png)
 
(p. 194)

(1) (@ronaldtse you introduced this without clarifying that it was a distinct issue, and giving it a distinct number.)

There is a numbered list of notes under a table; p. 162

<img width="565" alt="image" src="https://user-images.githubusercontent.com/11865/94599767-7e8d4d80-02c3-11eb-860c-7fdfc9d474af.png">

The automated label is NOTES not NOTE

(2) There is a set of table footnotes in p. 138, which is distinct from Notes

(3) In contrast to (9), there are numbered footnotes rendered at the bottom of the page; e.g. 140

To me, it is clear that footnotes are distinct from notes, differentiated by the presence or not of a footnote marker, and both notes and footnotes can be rendered either in their normal position, or in a sidebar.

**Comment by opoudjis** [comment]
The table notes are correctly embedded within the table in XML:

````
</tbody>
<note id="_9a2c99d7-f37b-48f8-82b6-7ef6218d285e"><name>NOTE  1</name>
<p id="_e56a163f-b10d-4536-b2c2-495d23ec3fd6">The symbols whose unit names are preceded by dots are those which had already been adopted by a decision of the CIPM.</p>
</note><note id="_aab7a11d-f245-4512-97fe-6eae3b95481a"><name>NOTE  2</name>
<p id="_10b9ffeb-e7ec-42b5-96cd-c0d0e5424608">The symbol for the stere, the unit of volume for firewood, shall be “st” and not “s”, which had been previously assigned to it by the CIPM.</p>
</note><note id="_c63a37f9-82b0-44e4-883a-cc960f7e96f4"><name>NOTE  3</name>
<p id="_0ff9e1f7-91e0-483f-a56a-7b5e4d89254d">To indicate a temperature interval or difference, rather than a temperature, the word “degree” in full, or the abbreviation “deg”, must be used.</p>
</note></table>
````

So @Intelligent2013 I don't see how there is any problem there.

**Comment by Intelligent2013** [comment]
> The table notes are correctly embedded within the table in XML:
> ...
> So @Intelligent2013 I don't see how there is any problem there.

There isn't problem here. It's clear. For this xml hierarchy
```
</tbody>
<note...</note>
<note...</note>
<note...</note>
</table>
```

I'll change the xslt to show note(s) **_under_** table.
BUT there is a very similar case (p. 130), there is a side note:
![изображение](https://user-images.githubusercontent.com/5559926/94963484-e41a4d80-0500-11eb-9958-189d650c40bd.png)

In XML:
```xml
</tbody>
<note id="_c477d8c3-7000-48d7-a8c9-c43ca8271d13"><name>NOTE</name>
<p id="_0670c251-f3a1-4bdc-a600-2c5e061807b9">The symbols for quantities are generally single letters of the Latin or Greek alphabets, printed in an italic font, and are <em>recommendations</em>. The symbols for units are printed in an upright (roman) font and are <em>mandatory</em>, see <xref target="unit_symbols">Clause 5</xref>.</p>
</note></table>
```

I.e. xml hierarchy is
```xml
</tbody>
<note ...</note>
</table>
```

I see only one difference between these two hierarchies: in last case we have only one note. I.e. if table has one note, then show it as side note, and there are a few notes, then after the table?

**Comment by ronaldtse** [comment]
> I see only one difference between these two hierarchies: in last case we have only one note. I.e. if table has one note, then show it as side note, and when there are a few notes, then after the table?

Table notes should always below the table, according to BIPM.

**Comment by ronaldtse** [comment]
> (9) There are sidebar notes with asterisks, which is consistent with footnote rendering:

These are footnotes indeed.

> (10) There is an inline note which is not a sidebar note:

<img width="438" alt="Screen Shot 2020-10-04 at 9 14 30 AM" src="https://user-images.githubusercontent.com/11865/95004744-11aae800-0622-11eb-9fce-851595ca9fd0.png">

This note is a Note of the Resolution. It's a "note from the quotation".

> (1) There is a numbered list of notes under a table; p. 162

These are table notes.

> (2) There is a set of table footnotes in p. 138, which is distinct from Notes

These are table footnotes.

> (3) In contrast to (9), there are numbered footnotes rendered at the bottom of the page; e.g. 140

<img width="155" alt="Screen Shot 2020-10-04 at 9 16 41 AM" src="https://user-images.githubusercontent.com/11865/95004767-50d93900-0622-11eb-9614-f5666e02f8ee.png">

p. 140 is a footnote.

**Comment by ronaldtse** [comment]
Have agreed with @opoudjis way forward.

**Comment by opoudjis** [comment]
@manuel489 The actions to be taken are the following. These presuppose that all quoted material in Appendix 1 are to be treated as blockquotes (#16), and that Resolutions and Recommendations are to be treated as separate clauses (#17).

* In the main body of the text:
  * If the note is anchored with an asterisk or number to the main body of the text, it needs to be encoded as a footnote, even if it is represented as a sidebar.
  * Otherwise, it remains a Note

* In the infamous appendix 1, usage of asterisks is wildly inconsistent. We will clean it up, as follows:
  * If the note relates to the entire clause (recommendation, resolution), it shall be left as a Note, at the end of the clause, outside of the blockquote. It will not be converted into a footnote, even if an asterisk is present.
  * If the note is inline in quoted material, it will be left as a note within the blockquote. 
  * If the note is marginal, and relates to a particular spot of quoted text, if shall be converted into a footnote, even if no asterisk has been used.

So in the examples given above:

(9): convert into footnotes
(10): Leave as note within the blockquote
(1): Leave as table notes
(2): Leave as footnotes
(3): Make footnotes

For the case in p. 130, we can differentiate between a note which is part of a table, and a note which is not, by using `[NOTE,keep-separate=true]` for the latter. If we use that markup in p. 130, the note will not be considered part of the table, and will become a sidebar. If on the other hand BIPM are saying that the note should have been put under the table, as Ronald is indicating, then leave it alone.

**Comment by Intelligent2013** [comment]
@opoudjis Agree with your proposals.

**Comment by manuel489** [comment]
> @manuel489 The actions to be taken are the following...

PR added in https://github.com/metanorma/bipm-si-brochure/pull/23

**Comment by opoudjis** [comment]
@Intelligent2013 is work on this ticket finished?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is work on this ticket finished?

@opoudjis  not yet, I'm working on it.

**Comment by Intelligent2013** [comment]
Finished.
