### ISSUE TITLE
Support custom table of contents: PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#150]
Follow on from https://github.com/metanorma/metanorma-bipm/issues/148

We are realising the idiosyncratic table of contents of Appendix 1 in the BIPM brochure as a native Table of Contents. To that end, I have introduced a new `<toc>` tag in Metanorma XML. Its contents are an unordered list, potentially nested, of section titles, as xrefs.

To realise this in PDF, you can assume that all xrefs within a toc tag should be realised as page references, um, looking like a ToC does.

I will generate and send to you XML for the BIPM brochure to work from. This is not immediate priority, since BIPM are currently on holidays, but it should be done within the month.

**Comment by ronaldtse** [comment]
>  have not implemented what the Brochure has now, an idiosyncratic manually authored list of values

I have confirmed with BIPM that they require the TOC titles for resolutions to "differ" from the real titles after a lengthy discussion.

An alternative to consider: a "TOC title" for sections?

**Comment by opoudjis** [comment]
Yeah, I'll come up with something. We still need the functionality I've implemented though

**Comment by ronaldtse** [comment]
Good point @opoudjis , I did not realize that there were two descriptive columns.

Now that makes me think — is that a TOC or an Index?

**Comment by Intelligent2013** [comment]
@opoudjis  I can render this structure as ToC:
```xml
<toc>
	<ul id='_'>
		<li>
			<xref target='clause1A'>Clause 1A</xref>
		</li>
		<li>
			<ul id='_'>
				<li>
					<xref target='clause1Aa'>Clause 1Aa</xref>
				</li>
				<li>
					<xref target='clause1Ab'>Clause 1Ab</xref>
				</li>
			</ul>
		</li>
		<li>
			<xref target='clause1B'>Clause 1B</xref>
		</li>
		<li>
			<ul id='_'>
				<li>
					<xref target='clause1Ba'>Clause 1Ba</xref>
				</li>
			</ul>
		</li>
	</ul>
</toc>

```

but you wrote:

>  If you need a marker saying "this table needs to be considered a ToC", we will need to do something else, such as wrap `<toc>` around the table.

I.e. if ToC will be represented in xml as `<table>`, then I need to know some indication about how it should be rendered - as usual table or as ToC. In case of ToC I have to know about indentation for each table row. For example, `toc/ul/li` and `toc/ul/li/li` will be displayed as nested lists. But in case of `table/tr` - there isn't possibility to determine the indentation...

**Comment by Intelligent2013** [comment]
From: https://github.com/metanorma/metanorma-standoc/issues/515#issuecomment-920091661
To do: modify xslt for xml based on:
```adoc
[type=toc]
== Table of Contents of Appendix 1

=== Decisions relating to the establishment of the SI page

* <<resolution:foo>>

=== Decisions relating to the base units of the SI

==== Length

* <<resolution:bar, populated title>>
```

> If you don't provide text in the xrefs in the ordered list, the text will be retrieved from the variant title of type toc in the section referenced, or failing that the proper title of the section referenced.

**Comment by Intelligent2013** [comment]
Done.
