### ISSUE TITLE
Semantic differences between sans-serif and serif in Appendix 1 of SI Brochure

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#16]
It is obvious to me that the alternation between sans-serif and serif in Appendix 1 relates to whether the material is quoted from a resolution, or is an editorial addition to the quotation; I therefore have requested that all such material be put in blockquotes.

Referring to https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf , in Appendix 1, the following material is not in sans-serif:

* All side notes (which are editorial additions)
* p. 161: descriptions of material which is not cited directly: table extraneous to "Triple point of water", and description of decision about Celsius.
<img width="493" alt="Screen Shot 2020-10-04 at 8 54 06 AM" src="https://user-images.githubusercontent.com/11865/95004550-2afe6500-061f-11eb-89c9-2b7047ecd5ee.png">

* p. 164: description in square brackets of tables and lists which are not directly cited
<img width="438" alt="Screen Shot 2020-10-04 at 8 54 22 AM" src="https://user-images.githubusercontent.com/11865/95004553-33ef3680-061f-11eb-91b0-098853b5cbea.png">

* p. 171: Editorial comment introducing a later supplement to the cited material
<img width="493" alt="Screen Shot 2020-10-04 at 8 54 43 AM" src="https://user-images.githubusercontent.com/11865/95004557-40738f00-061f-11eb-8efd-f8aa0c1c774a.png">

* p. 180: Editorial comment introducing the cited material
<img width="408" alt="Screen Shot 2020-10-04 at 8 55 23 AM" src="https://user-images.githubusercontent.com/11865/95004570-58e3a980-061f-11eb-819d-b563855e9c3e.png">

It is clear to me that the use of serifed font is meaningful, and needs to be indicated in markup as blockquotes. @manuel489 @ronaldtse please explain if you disagree with the assessment. 

BIPM have  apparently indicated that we can dispense with font differentiation, but without the addition of square brackets (which are only used in p. 164), that introduces unnecessary ambiguity into the text, which does not otherwise differentiate cited and non-cited material.

**Comment by manuel489** [comment]
I thought that blockquote markup should be applied to sans serif text instead of serif (as we talked in private). Now I'm happy that it's not in that way anymore. This approach seem much more feasible to me.

What about the side notes? should they be typeset as footnotes?

**Comment by ronaldtse** [comment]
@opoudjis "notes on resolutions" are considered annotations on the original resolutions. 

They are not considered notes in the sense of this particular document (the SI brochure) -- they are also provided in the source of the resolutions.

The right question is: how do we incorporate a resolution text that is annotated, and represent them?

**Comment by opoudjis** [comment]
@manuel489 

> I thought that blockquote markup should be applied to sans serif text instead of serif text. Now I'm happy that it's not in that way anymore. This approach seem much more feasible to me.

Um... sorry, I was not being clear. I am still saying that the sans-serif stuff is quoted, and thus needs to be in blockquote. Is your concern that there's too much of them?

> What about the side notes? should they be typeset as footnotes?

In my opinion yes, but we're waiting on guidance on those in general: #15

**Comment by opoudjis** [comment]
> The right question is: how do we incorporate a resolution text that is annotated, and represent them?

In my opinion: footnotes. With an option on them to render them as sidebars instead.

**Comment by manuel489** [comment]
> Um... sorry, I was not being clear. I am still saying that the sans-serif stuff is quoted, and thus needs to be in blockquote. Is your concern that there's too much of them?

Not really, it's just I think the markup will look kind of messy... Or maybe I'm just being paranoid 😄 . Ok, no problem.

**Comment by ronaldtse** [comment]
> > The right question is: how do we incorporate a resolution text that is annotated, and represent them?
> In my opinion: footnotes. With an option on them to render them as sidebars instead.

The key difference between footnotes and normal notes is locality:
* Footnotes are apply to a location within a block
* Notes apply to a block

A resolution can have Footnotes (to point to particular content within) and Notes (that applies to the whole resolution or a block of text inside the resolution).

We don't need "options" for rendering here.

**Comment by ronaldtse** [comment]
@opoudjis I've added screenshots to your message. They are much more helpful and suggest this as good practice in the future.

The larger questions that are not answered:
* Are resolutions considered quotations in this document, which allows for the switch from serif to sans serif? 
* How do we differentiate annotations of the original resolutions vs annotations made by this document? Semantically.

I think we need to clarify the types of text here:
1. Content belonging to the document itself (p. 161, p. 180, p. 171)
2. Additional note to resolution (p. 164)

For 1. they should be inlined, not as notes but as content. 

For 2. it should be encoded as a Footnote.


In the case of "p. 180: Editorial comment introducing the cited material"
<img width="416" alt="Screen Shot 2020-10-04 at 8 57 10 AM" src="https://user-images.githubusercontent.com/11865/95004584-97796400-061f-11eb-8bd8-7c6964349c11.png">

Notice that:
* "The CIPM approved in 2001 the following proposal of the CCU regarding “SI units”..." This is content of Appendix 1.
* "“We suggest that “SI units” a..." This is a quotation.

**Comment by ronaldtse** [comment]
Have agreed with @opoudjis way forward.

**Comment by opoudjis** [comment]
@manuel489 The way forward is:

* All sans-serif material in Appendix 1 shall be put in blockquotes
* Titles cannot and will not be included in blockquotes. 
* On how to differentiate annotations and quoted notes, we have decided to use the most expedient mechanism of note vs footnote, as discussed in #15 :
  * A footnote on quoted material will be rendered in the margin with asterisks, no matter what the source document has done
  * A note inline will be treated as a note within quoted material
  * A marginal note which does not apply to a specific point in the quoted material shall be encoded as a note outside of the blockquote

**Comment by manuel489** [comment]
> @manuel489 The way forward is...

PR added in https://github.com/metanorma/bipm-si-brochure/pull/23

**Comment by ronaldtse** [comment]
Semantics confirmed by BIPM.

There are:

(a) Notes of the original resolutions (or decisions)
(b) Notes added by the SI Brochure on the original resolutions

Moreover, a note (of both kinds) can apply to the whole resolution, or to a particular part of a resolution.

These two kinds of notes were differentiated in the original SI Brochure by switching between sans serif (the font style used by Resolutions for (a) and serif text (the font style used in SI Brochure main text for (b)). 

The 4 particular examples are shown at this link:
https://github.com/metanorma/metanorma-bipm/issues/16

> Your understanding is correct [...]: the sans serif text is used for the original resolutions and notes which are part of the resolution. Text in serif font is added as a later comment to the original resolution.
 
We should semantically differentiate them with consistent styling.

**Comment by opoudjis** [comment]
@ronaldtse You are therefore rescinding what we have agreed above, using footnotes for editorial annotations, and we are compelled to add semantic attributes indicating that a note is of editorial origin. _As I had initially proposed._

**Comment by ronaldtse** [comment]
I’m confused. Footnote style annotation is clearly done at the brochure level not the quotation level.

**Comment by opoudjis** [comment]
> I’m confused. Footnote style annotation is clearly done at the brochure level not the quotation level.

FFS. I am going to have to do more analysis. 

As we Greeks say, a fool throws a stone in the well, and forty sensible men can't pull it out again.

**Comment by opoudjis** [comment]
We're agreed it's the former. Cases like this:

<img width="1209" alt="Στιγμιότυπο 2020-10-14, 01 20 33" src="https://user-images.githubusercontent.com/1911039/95875561-de085480-0dbd-11eb-8184-32c574459152.png">

really do need to be treated as footnotes and not marginal notes, or notes external to the quotation. So this ticket is closed.
