### ISSUE TITLE
Incorrect `--split-by-language` pass

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-bipm#160]
###  Intro

During https://github.com/metanorma/bipm-si-brochure build, I noted that mn2pdf.jar called with unwanted `{}`, like this:
```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mn2pdf-1.38.1/lib/../bin/mn2pdf.jar --xml-file "collection/collection.presentation.xml" --xsl-file "/Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-2.0.0.1/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "collection/collection.pdf" {} --split-by-language
```

This is not lead to any issue, but I think make sense to fix it

### Proposed fix

This code needs to be fixed https://github.com/metanorma/metanorma-bipm/blob/main/lib/isodoc/bipm/pdf_convert.rb#L34 because `super` returns `Hash` so we need handle it

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
Reviewed.

**Comment by CAMOBAP** [comment]
Merged
