### ISSUE TITLE
Support citation of bipm-data-outcomes (CIPM, CGPM, CCTF) for the SI Brochure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#164]
From Janet Miles of the BIPM:

For the Resolutions/Recommendations/Decisions I think the following simple rule works without any ambiguity:

English:
```
[BODY] [Type] {number} (YEAR)
```
 
(where the number can be omitted if necessary, and the Type will be Resolution/Recommendation/Declaration as appropriate).

French (in French an additional dash is required as follows):
```
[BODY] - [Type] {number} (YEAR)
```
(and of course the Type has to be specified in French : Résolution,  Recommandation, Déclaration…)

Examples:
```
CGPM Resolution 6 (1987)
CIPM Resolution (1948)
CCDS Recommendation 2 (1970)
 ```

We can omit the official citation (CR, PV etc.) since the Brochure will provide links to the relevant pages on the BIPM website, and these contain the citation details.
 
Within the notes to the Resolutions there is no need to make any changes. For example in the link you provide (for CGPM Resolution (1889)) we can leave the phrasing in the note as is
“as abrogated in 1960 by the 11th CGPM (Resolution 6)”.
 
------------

 
Four points for your attention please:
 
1. When generating the Table of Contents for Appendix 1 it would be good to use the user-friendly labels (as in the current Appendix)  rather than the official (CGPM/CIPM/CCTF) titles.
 
    * For example, in the index to Appendix 1, “CGPM Resolution 6 (1948)” is listed as “decision to establish the SI”, whereas the official English title is “Proposal for establishing a practical system of units of measurement” (https://www.bipm.org/en/committees/cg/cgpm/9-1948/resolution-6)
 
2. For the CCDS Recommendation 2 (1970) the link is https://www.bipm.org/en/committees/cc/cctf/5-1970/resolution-2, but the committee at that time was called CCDS, not CCTF.

3. In the yml example you provide, I see that two different URLs are given for the “pdf” and “reference” (which correspond to the document on the BIPM website). Can you please omit the segment “?version=1.3&download=true”, and for the links use the versions as given on https://www.bipm.org/en/committees/cg/cgpm/publications, https://www.bipm.org/en/committees/ci/cipm/publications, https://www.bipm.org/en/committees/ci/cipm/older-meeting-reports, https://www.bipm.org/en/committees/cc/cctf/publications
(Unfortunately the documents are posted twice.)
 
4. Also in the yml example I see: 
    ```yaml
    type: affirmative
    degree: unanimous
    ``` 

    * I haven’t checked if “unanimous” is appropriate for each of the listed Resolutions, but it would probably be safer to omit that line!

**Comment by opoudjis** [comment]
Waiting on https://github.com/metanorma/metanorma-bipm/issues/164

**Comment by ronaldtse** [comment]
@opoudjis I think you meant https://github.com/relaton/relaton-bipm/issues/4 instead of 164, which is this very issue... 😉

**Comment by opoudjis** [comment]
First task:

Translate into French the IDs of BIPM documents, and introduce dashes.

**Comment by opoudjis** [comment]
need to strip BIPM prefix to BIPM documents (as we always do for intra-SDO citations).

**Comment by opoudjis** [comment]
Need to add the year in to the citation.

**Comment by opoudjis** [comment]
I believe this ticket is also complete, but will close when brochure generated

**Comment by opoudjis** [comment]
Is working as expected now.
