### ISSUE TITLE
(SI Brochure, URGENT) Brochure: Duplicate years on rendered CIPM/CGPM references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#170]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/145*

From https://github.com/metanorma/bipm-si-brochure/pull/168, this markup:
````
* [[[CR1968-7, CGPM Resolution 1967-07]]]
````

Renders:
![issue1](https://user-images.githubusercontent.com/33627611/170766779-1e7ca80f-b7cc-4a2b-997a-66cb4aefec00.PNG)

**Comment by ronaldtse** [comment]
@opoudjis @andrew2net is this a Relaton BIPM issue, or a Metanorma issue?

**Comment by ronaldtse** [comment]
According to the data file, the year is already included in the "ID":
https://github.com/relaton/relaton-data-bipm/blob/d40968792b9fc8e90aefc23f6921e9c74dec1ae4/data/cgpm/resolution/1967-07.yaml#L22

Is this a Relaton BIPM rendering issue? @andrew2net

**Comment by opoudjis** [comment]
We're doubling up clearly. 

* I actioned advice from BIPM that the year was to be added to the citation, but is a distinct thing from the identifier; so I added it on top of the ID
* @andrew2net, acting on the same advice, added the year to the ID

@ronaldtse Given the ambiguity we have already discussed for these resolutions, whose numbering restarts each year, I will have to assume that *all* BIPM publications have the year attached to the ID (@andrew2net please confirm), and I will undo the change adding the year to the ID.

**Comment by ronaldtse** [comment]
@andrew2net this is an issue in Relaton-BIPM. 

The raw data seems to be correct:
* CGPM Resolution 1: https://github.com/metanorma/bipm-data-outcomes/blob/59a48683f130986f3834d0a10c54e6ff9da20789/cgpm/meetings-en/meeting-01.yml#L9-L15
* CIPM Decision 105: @opoudjis has fixed it, there is no actual "Decision 105".

**Comment by ronaldtse** [comment]
@opoudjis , "CGPM Resolution (1889)" already has year :
https://github.com/relaton/relaton-data-bipm/blob/7b3460028d0c064ecb6743f6cb4c075136d7bc46/data/cgpm/meetings/resolution/1889-00.yaml#L22

**Comment by opoudjis** [comment]
PR has passed. This should now be fine. Yes, I know know they already have years, that's why I'm no longer adding them.
