### ISSUE TITLE
(URGENT) Fix hiding of CGPM/CIPM tag references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#171]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/145

CGPM/CIPM reference tags are not being hidden.

Maybe this line from https://github.com/metanorma/metanorma-bipm/commit/722995e1a78706e93e452286fd06059120733933  has to do with the problem:

````
return true if /^BIPM CGPM Resolution|^BIPM CIPM Decision/.match?(b&.text)
````

CGPM/CIPM identifiers are no longer starting with "BIPM".

In addition, we need to take into account two more types of outcomes:
"Recommendation" and "Declaration".

Some identifier examples:
````
CGPM Resolution 2011-01
CIPM Resolution 02 (1946)
CIPM Recommendation (1961)
CIPM Recommendation 2 (1967)
CIPM Declaration (1964)
CIPM Declaration 1 (2001)
CIPM Decision 2017-10
CCDS Recommendation 2 (1970)
````

`CCDS` is another body that we need to include besides CGPM/CIPM.
And judging for this piece of message:

"For the CCDS Recommendation 2 (1970) the link is https://www.bipm.org/en/committees/cc/cctf/5-1970/resolution-2, but the committee at that time was called CCDS, not CCTF."
(from https://github.com/metanorma/metanorma-bipm/issues/164)

Maybe we should include `CCTF` as well.

**Comment by ronaldtse** [comment]
> Maybe we should include CCTF as well.

Yes.

I think the code for skipping references should possibly reside in metanorma-bipm because we don't need to skip BIPM references if used in other flavors.

**Comment by opoudjis** [comment]
It does. Actioning.
