### ISSUE TITLE
Support French retrieval of Resolution, Recommendation, Declaration and Meeting

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#175]
From https://github.com/relaton/relaton-bipm/issues/27

Posted by @ronaldtse:

The fetching syntax should allow both English and French, and retrieve the identical bibliographic item. This is because BIPM is a French-first organization.

In rendering the title/contents, the language should respect the rendering options.

* "Résolution" => English Resolution
* "Réunion" => English Meeting
* "Déclaration" => English Declaration
* "Recommandation" => English Recommendation

**Comment by ronaldtse** [comment]
@opoudjis can you please help with this? This is the remaining blocker for the SI brochure and they are waiting for it. Thanks.

**Comment by manuel489** [comment]
> This is the remaining blocker for the SI brochure and they are waiting for it. Thanks.

@ronaldtse I believe it is not: https://github.com/metanorma/metanorma-bipm/issues/174

**Comment by opoudjis** [comment]
The requirement is incorrect. What should happen is, the rendering of the fetched bibliographic item should match the language of the text, not of the reference.

**Comment by opoudjis** [comment]
Is waiting on https://github.com/relaton/relaton-bipm/issues/27

**Comment by ronaldtse** [comment]
I can confirm this is fixed.

**Comment by ronaldtse** [comment]
@opoudjis thanks!

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton-bipm/issues/27 needs to be fixed to language-tag docidentifiers.
