### ISSUE TITLE
Brochure: Numbering of visible references is unordered

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#176]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/169

References that are meant to be visible (i.e Meeting references) are not
numerically ordered:

![capture1](https://user-images.githubusercontent.com/33627611/173206583-9f749954-9516-4080-b98d-6a252719e54e.PNG)

It seems like they are taking into account the present of hidden references.

**Comment by ronaldtse** [comment]
I believe this is also the case with numbered bibliographies in other flavors.

**Comment by opoudjis** [comment]
Issue is specific to PDF, HTML renders correctly.

Presentation XML has:

````
<bibitem id="CR1948"><formattedref>Bureau International des Poids et Mesures. <em>9th meeting of the CGPM</em>. 1948.</formattedref><uri type="src">https://www.bipm.org/en/committees/cg/cgpm/9-1948</uri><uri type="pdf">https://www.bipm.org/documents/20126/38095573/CGPM9.pdf/10f7e9dc-a8d7-1e4c-fdfb-5f139fefd018</uri><uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-en/meeting-09.yml</uri><uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-fr/meeting-09.yml</uri><docidentifier type="BIPM" primary="true">CGPM Meeting 9</docidentifier></bibitem>
````

Semantic XML has:

````
<bibitem id="CR1948">  <fetched>2022-06-13</fetched>
<title format="text/plain" language="en" script="Latn">9th meeting of the CGPM</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/9-1948</uri>  <uri type="pdf">https://www.bipm.org/documents/20126/38095573/CGPM9.pdf/10f7e9dc-a8d7-1e4c-fdfb-5f139fefd018</uri>  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-en/meeting-09.yml</uri>  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cgpm/meetings-fr/meeting-09.yml</uri>  <docidentifier type="BIPM" primary="true">CGPM Meeting 9</docidentifier>  <docnumber>CGPM Meeting 9</docnumber>  <date type="published">    <on>1948-10-21</on>  </date>  <contributor>    <role type="publisher"/>    <organization>
<name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>      <uri>www.bipm.org</uri>    </organization>  </contributor>  <language>en</language>  <language>fr</language>  <script>Latn</script></bibitem>
````

In isodoc by default, a `docidentifier[@type = 'metanorma-ordinal']` is generated, and that skips hidden references.  I've told metanorma not to number BIPM references in bibliography, but that's clearly not true, given what I'm seeing (it's an assumption from ISO.)

So:

* I am turning metanorma-ordinal back on
* @Intelligent2013 You will need to use metanorma-ordinal, or else ignore hidden references, to count bibliographic references.

**Comment by Intelligent2013** [comment]
@manuel489 could you inform me which is problematic document?


si-brochure-fr.presentation.xml contains 'hidden' bibliography:
```
<bibliography>
		<references id="_bibliography_si-brochure-fr" normative="false" obligation="informative" hidden="true" displayorder="13">
			<title depth="1">Bibliography</title>
			<bibitem type="standard" hidden="true" id="english-doc_si-brochure-fr">
				<formattedref>Bureau International des Poids et Mesures. <em>Le Système international d’unités</em>. 9e édition. <link target="si-brochure-en.html">si-brochure-en.html</link>.</formattedref>
				<uri type="citation">si-brochure-en.html</uri>
				<docidentifier type="BIPM">BIPM Brochure</docidentifier>
				<docidentifier type="ISBN">ISBN 978-92-822-2272-0</docidentifier>
			</bibitem>
		</references>
	</bibliography>
```

**Comment by manuel489** [comment]
@Intelligent2013 the capture presented above comes from English version of the brochure (si-brochure-en).
However, French version should give the same issue.
Maybe you are not compiling with the lasted markup changes
which are given in this PR: https://github.com/metanorma/bipm-si-brochure/pull/168.
Please use these changes. Thanks!

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/173422261-724e4919-cb68-4580-9a6d-5e4a19ddc18a.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 @manuel489 why do we have this funny entry here?
<img width="281" alt="Screenshot 2022-06-14 at 3 52 20 PM" src="https://user-images.githubusercontent.com/11865/173512223-c6ae87e4-fae9-4fb2-a184-2cc89c6cd6b3.png">

**Comment by manuel489** [comment]
@ronaldtse I believe that entry is necessary to cross-reference external document version (English and French).
For when the Brochure is compiled as a collection instead of individual language version.

**Comment by manuel489** [comment]
> We definitely do not want to render it as such in a collection because both parts exist, this entry should be hidden.

Yeah, it is hidden on a collection.

**Comment by manuel489** [comment]
> In the use case where both parts exist separately, we want to have a clean citation, e.g. "Bureau International des Poids et Mesures. SI Brochure. Edition 9." for the citation for the English version.

Maybe this is not implemented?

**Comment by opoudjis** [comment]
> In the use case where both parts exist separately, we want to have a clean citation, e.g. "Bureau International des Poids et Mesures. SI Brochure. Edition 9." for the citation for the English version.

> Maybe this is not implemented?

In fact, there is no Relation XML record for `repo:(current-metanorma-collection/si-brochure-en)`, though one can be extrapolated—it would of course be the bibdata of the target document. 

It may indeed not be implemented; let me check.

**Comment by opoudjis** [comment]
````
<bibitem id="english-doc">
  <formattedref format="application/x-isodoc+xml"/>
  <docidentifier>si-brochure-en</docidentifier>
  <docidentifier type="repository">current-metanorma-collection/si-brochure-en</docidentifier>
  
</bibitem>
````

**Comment by opoudjis** [comment]
There is in fact code to insert the bibitem of the linked document. But that code is only invoked when the document is compiled as part of a collection! It doesn't get invoked when the document is compiled as a standalone, and indeed, if the document is compiled as a standalone, it's not going to have any idea what the repo(...) reference, pointing to the external document means: by definition, that compilation does not involve a document manifest!

So if the French and English Brochures are to be compiled as standalones, as well as in the collection, then the references titles will need to be supplied manually in the bibliography. The entire reference gets overwritten with the linked document's when the collection is compiled anyway, so supplying a manual title is safe.

@manuel489

**Comment by manuel489** [comment]
The output is almost as expected:

````
* [[[french-doc,repo:(current-metanorma-collection/si-brochure-fr)]]] Bureau International des Poids et Mesures. _SI Brochure_. Edition 9.
````

![capture1](https://user-images.githubusercontent.com/33627611/173843787-a31d27c1-6dc9-48ee-b42f-61e3667890f2.PNG)

**Comment by opoudjis** [comment]
````
* [[[french-doc,dropid(repo:(current-metanorma-collection/si-brochure-fr))]]] Bureau International des Poids et Mesures. _SI Brochure_. Edition 9.
````

**Comment by opoudjis** [comment]
<img width="784" alt="Screen Shot 2022-06-23 at 00 49 51" src="https://user-images.githubusercontent.com/1911039/175060085-c2ded286-2464-4049-bef1-b9b2f8b41167.png">

**Comment by opoudjis** [comment]
I'm updating the brochure in main. You will need to use standoc and isodoc from github, and you will need to wait for Alex Dyuzhev to implement this in PDF.
