### ISSUE TITLE
Bibliography references to BIPM meetings not being hidden using latest Relaton data

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#180]
For some reason we are now seeing the Bibliography again.

Originally, bibliography references to BIPM meetings are hidden within the SI Brochure. The Relaton-BIPM data may have recently changed that causes this.

Bilingual PDF French section:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/11865/176504842-40e7bad5-c68d-4ca0-9646-e94c506587bf.png">

Bilingual PDF English section:
<img width="921" alt="Screenshot 2022-06-30 at 3 00 55 AM" src="https://user-images.githubusercontent.com/11865/176504861-ae287455-9f93-461c-a1fd-67893ecfe6b2.png">

I believe this is not meant to happen, right @opoudjis ?

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/179#issuecomment-1170314921_

**Comment by opoudjis** [comment]
Already fixed in https://github.com/metanorma/bipm-si-brochure/issues/172 . https://github.com/metanorma/metanorma-bipm/pull/179 is an open PR. Recompiled locally with PR, and meetings are still absent.
