### ISSUE TITLE
Accessible math showing as white text against the "DRAFT" watermark

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#188]
Example below:
<img width="692" alt="Screen Shot 2022-08-18 at 10 54 07 AM" src="https://user-images.githubusercontent.com/11865/185282784-89f995b8-1eba-435c-a419-2a565152233e.png">

Is it possible to not show the accessible math as white text at all (e.g. 100% transparency of text)?

**Comment by Intelligent2013** [comment]
In XSL-FO there isn't property to set text transparency. I'll investigate how to tweak it. At first glance there are two options (don't sure where they can be applited yet):
- move text behind background image with watermark (change z-order)
- set 'Text rendering mode' to `3 Tr` (9.3.6 in PDF Spec):
![image](https://user-images.githubusercontent.com/5559926/185366967-961c0849-6758-4f30-915e-4296601615b7.png)

**Comment by ronaldtse** [comment]
Looks like both are good options and probably should do both. And we should extend the previous blog post with this new technique too.

**Comment by Intelligent2013** [comment]
mn2pdf updated for 1st option
> move text behind background image with watermark (change z-order)

![image](https://user-images.githubusercontent.com/5559926/185463180-c8feb145-60f0-447a-ac70-a9c1a8282b64.png)

Text is searchable - checked:
![image](https://user-images.githubusercontent.com/5559926/185463373-9c6b1b80-fabd-49a7-9335-ac42eddb2877.png)

**Comment by Intelligent2013** [comment]
Regarding 2nd option, the the FOP class `fop-core\src\main\java\org\apache\fop\pdf\PDFTextUtil.java` there are constants:
```java
/** PDF text rendering mode: Fill text */
    public static final int TR_FILL = 0;
    /** PDF text rendering mode: Stroke text */
    public static final int TR_STROKE = 1;
    /** PDF text rendering mode: Fill, then stroke text */
    public static final int TR_FILL_STROKE = 2;
    /** PDF text rendering mode: Neither fill nor stroke text (invisible) */
    public static final int TR_INVISIBLE = 3;
    /** PDF text rendering mode: Fill text and add to path for clipping */
    public static final int TR_FILL_CLIP = 4;
    /** PDF text rendering mode: Stroke text and add to path for clipping */
    public static final int TR_STROKE_CLIP = 5;
    /** PDF text rendering mode: Fill, then stroke text and add to path for clipping */
    public static final int TR_FILL_STROKE_CLIP = 6;
    /** PDF text rendering mode: Add text to path for clipping */
    public static final int TR_CLIP = 7;
```
and the method `setTextRenderingMode`:
```java
/**
     * Sets the text rendering mode.
     * @param mode the rendering mode (value 0 to 7, see PDF Spec, constants: TR_*)
     */
    public void setTextRenderingMode(int mode) {
        if (mode < 0 || mode > 7) {
            throw new IllegalArgumentException(
                    "Illegal value for text rendering mode. Expected: 0-7");
        }
        if (mode != this.textRenderingMode) {
            writeTJ();
            this.textRenderingMode = mode;
            write(this.textRenderingMode + " Tr\n");
        }
    }
```

It seems the class `org\apache\fop\render\pdf\PDFPainter.java` should be modified to call `setTextRenderingMode(int mode)`.

**Comment by Intelligent2013** [comment]
mn2pdf updated for 2nd option.

**Comment by Intelligent2013** [comment]
Issue found with the text selection.
Before update (both options) we can select the text before formula, formula and text after formula:
![image](https://user-images.githubusercontent.com/5559926/185625471-a8ccfdbc-7ed2-4c6b-8ca0-d560deca8d2c.png)

After update - the formula isn't selected:
![image](https://user-images.githubusercontent.com/5559926/185625680-09316e2e-57be-4a4c-83e6-2d8026cdf201.png)
but we can select the formula only:
![image](https://user-images.githubusercontent.com/5559926/185625810-b52a1e9c-459a-4e83-8c05-20af6414575c.png)

Looks like the text selection feature depends on the element depth (z-order) or the rendering order.
May be we need to remove 1st option. Will check it.

**Comment by Intelligent2013** [comment]
Now the hidden text placed at start of page, therefore we need to remove 1st option.

PDF Before update:
![image](https://user-images.githubusercontent.com/5559926/185630768-f2f05bbc-f6d4-4630-ad0b-081d6e2bed54.png)

Currently generated PDF:
![image](https://user-images.githubusercontent.com/5559926/185631099-f09c3247-7bbc-4181-afb1-f96a1054af69.png)

**Comment by Intelligent2013** [comment]
1st option removed.

**Comment by Intelligent2013** [comment]
@ronaldtse issue fixed in https://github.com/metanorma/mn2pdf/releases/tag/v1.49

Blog post updated a bit in PR https://github.com/metanorma/metanorma.org/pull/640
