### ISSUE TITLE
Brochure: Replace "chapître" by "chapitre" (regular i)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#193]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/189

Cross-references to chapters show "chapître" in French. We need to change it
to "chapitre".

Example:

```adoc
NOTE: Les symboles des grandeurs, imprimés
en italique, sont généralement de
simples lettres de l’alphabet grec ou latin
et constituent des _recommandations_.
Les symboles des unités, imprimés en
caractères romains (droits), sont
_obligatoires_ (voir <<chapter5,nosee%>>).
````

Output:
![issue2-1](https://user-images.githubusercontent.com/33627611/190455891-62b52764-2d03-443b-9c65-ffe3bfcb6233.PNG)

**Comment by opoudjis** [comment]
1990 French spelling reform, for the win.
