### ISSUE TITLE
Brochure: remove space in "-0, 234"

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#194]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/189

This:
```adoc
[example]
====
stem:[−0,234] +
mais pas +
stem:["−,234"]
====
```

renders:
![issue15-1](https://user-images.githubusercontent.com/33627611/190468842-39b86ce3-43c6-48eb-b03d-0c2f23c33594.PNG)

**Comment by opoudjis** [comment]
The asciidoc/Asciimath parser we have been using to date is not localised:

-0.6 is recognised as a single number
-0,6 , -,6, -.6 are not: they are being processed as:

`<mo>−</mo><mn>0</mn><mo>,</mo><mn>234</mn>` for -0,234 (which renders with the space shown)
`><mtext>−,234</mtext>` for -,234

If we enter -0.234, that is not only recognised as a number, but is correctly rendered with its decimal point converted to a comma.

But the Asciimath parser has to cope to begin with with commas in numbers.

I'm switching our Asciimath parser to Plurimath, and... well, we're signing up for a lot of regression testing.

**Comment by opoudjis** [comment]
Right now:

* our native Asciimath parser (Plurimath) does not recognise any decimals, comma or point
* our current Asciimath parser (Asciidoctor) only recognises decimal points
* getting our native Asciimath parser (Plurimath)  to the level of maturity of the Asciidoctor parser is a big job, especially given the underspecification of Asciimath

Our options are:

* to ban all use of decimal comma in Asciidoctor French source: localisation will render decimal points as decimal commas correctly. This is anglocentric (you can only enter maths using English conventions, however you render them), but it's not the worst thing that has ever happen; the metalanguage of our markup is English, after all.
* to map all decimal commas in Asciidoctor French source to decimal points in preprocessing. I don't think that's absurd.
* to ask Asciidoctor Asciimath to recognise decimal commas. I'm not convinced that they should, and that decimal commas even are correct Asciimath
* to wait for Plurimath Asciimath to catch up with Asciidoctor Asciimath. I think making a major deliverable like the BIPM Brochure subject to a complete reimplementation of Asciimath would be a very foolish thing to do, this late in the process.

**Comment by opoudjis** [comment]
In fact, in this instance, we have been using decimal point in French throughout; this is a one-off exception, which I've fixed. This issue will come back to us, but for now, we will just document that Asciimath markup requires decimal points.

**Comment by ronaldtse** [comment]
Correct, and in fact, the `-0,234` and `0,234` statements were meant to be "counter-examples", so let's not generalize this issue.

We probably want to support the decimal comma but NOT until we decide what the French use for separators (e.g. in matrices).
