### ISSUE TITLE
Brochure: Malformed cross-reference in side note

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#196]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/189

For some reason, there is one cross-reference that is malformed in a side note.

```adoc
footnote:[Le CIPM a approuvé en
2001 une proposition du CCU visant à clarifier la
définition des «{nbsp}unités SI{nbsp}» et «{nbsp}unités du SI{nbsp}»,
_voir_ <<cipm_unites_si>>]
```

renders
![issue26-1](https://user-images.githubusercontent.com/33627611/190557125-40d68130-627b-49b1-90e0-17a4a3dd1fff.PNG)

Generally, these kinds of cross-references show a page number, with the structure *p. some-number*.
But in this case, it's not happening.

**Comment by opoudjis** [comment]
Aha!

The xref for cipm_unites_si, marked up as

`_voir_ <<cipm_unites_si>>`

is pointing to:

`<clause id="cipm_unites_si" unnumbered="true" obligation="normative">`

This is a clause with no clause number.

... So... Metanorma has no idea what to call the cross-reference. It's therefore dumped the last-resort text of the anchor ID as the cross-reference text: `<xref target="cipm_unites_si">"[cipm_unites_si]"</xref>`

When Metanorma knows what the clause number is, it does:

* Asciidoctor: `décalage relativiste de fréquence entre les étalons à césium (voir <<cls-236,nosee%>>).`
* Semantic XML: `décalage relativiste de fréquence entre les étalons à césium, voir <xref target="cls-236" nosee="true"/>`  
* Presentation XML: `(voir <xref target="cls-236" nosee="true">section 2.3.6</xref>)`
* Renders as: (voir section 2.3.6, p. 29).

So the PDF knows to put a page number after a numbered clause reference, but is confused by the fall-back anchor text.

We also have:

* Asciidoctor: `dans le texte «{nbsp}<<le_bipm_et_la_cdm,Convention du Mètre>>{nbsp}» (page <<le_bipm_et_la_cdm,pagenumber%>>).`
* Semantic XML: ` « <xref target="le_bipm_et_la_cdm">Convention du Mètre</xref> » (page <xref target="le_bipm_et_la_cdm" pagenumber="true"/>).</p>`
* Presentation XML: `« <xref target="le_bipm_et_la_cdm">Convention du Mètre</xref> » (page <xref target="le_bipm_et_la_cdm" pagenumber="true">Le BIPM et la Convention du Mètre mètre (m ) Convention du Mètre</xref>).</p>`
* Renders as: sont décrits dans le texte « Convention du Mètre » (page 5).

Now, the latter case is comparable to what we're dealing with: it's a preface reference, so no section number, and we've ended up inserting  a manual page reference to deal with it.

We'll address this instance with the same workaround:

`_voir_ <<cipm_unites_si,pagenumber%>>`

**Comment by opoudjis** [comment]
<img width="146" alt="Στιγμιότυπο 2022-10-17, 23 26 08" src="https://user-images.githubusercontent.com/1911039/196176765-0939c74f-2cf0-4b00-afd4-744151b7db61.png">
