### ISSUE TITLE
Brochure: Insert vertical space between list items in Preface

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#197]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

BIPM want us to insert vertical space between list items in the Preface (like in original document).

Generated:
![issue5-1](https://user-images.githubusercontent.com/33627611/190670860-55c7dfe7-2bca-493c-b8d4-326ff3196d99.PNG)

Original:
![issue5-2](https://user-images.githubusercontent.com/33627611/190670884-6383dd5b-29a2-4beb-8f58-d544494b6e25.PNG)

**Comment by ronaldtse** [comment]
If this is an unordered list, it's normal to have some vertical spacing between them.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/190874566-76780012-751b-4704-9b6d-92bcb590e089.png)

**Comment by manuelfuenmayor** [comment]
Confirmed!
