### ISSUE TITLE
Brochure: Insert vertical space between paragraphs in Preface note

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#198]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

We need to insert a vertical space between paragraphs in the Preface note.
Also, a space before and after the semicolon must be added. I.e "NOTE : La…".

Current presentation:
![issue6-1](https://user-images.githubusercontent.com/33627611/190672389-c3583038-1c79-4e26-bcc1-7cd3fd86b769.PNG)

**Comment by manuelfuenmayor** [comment]
Also, the content should be justified.

**Comment by manuelfuenmayor** [comment]
This issue applies to both French and English versions.

**Comment by Intelligent2013** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/5559926/190874474-a0a4ecdf-efd6-4898-9e74-8b7edd2e73b4.png)

**Comment by manuelfuenmayor** [comment]
Confirmed fixed. Thanks @Intelligent2013.
