### ISSUE TITLE
Brochure: Use French hyperlinks to Recommendations and Resolutions in French document

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#199]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

Currently, all hyperlinks to Recommendations and Resolutions lead to a English version website.
We need to use French webiste hyperlinks in French version of the Brochure.

For example, this reference:
```adoc
* [[[PV57_5, CIPM Recommandation 5 (1989)]]]
```

Should lead to this website: https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5 
(And not this: https://www.bipm.org/en/committees/ci/cipm/78-1989/resolution-5)

**Comment by opoudjis** [comment]
Implemented in https://github.com/metanorma/bipm-si-brochure/issues/192, waiting on debugging of https://github.com/metanorma/bipm-si-brochure/issues/192
