### ISSUE TITLE
Brochure: Replace letters by numbers in list items

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#200]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

From BIPM:
<html>
<body>

19 | 47 | "sanctionne" | enumeration 1., 2., 3. replaced by a), b), c); in the English text, the numbers are maintained, use numbers also in French
-- | -- | -- | --

</body>
</html>

Example:
![issue18-1](https://user-images.githubusercontent.com/33627611/190708196-d0e7d921-3d30-4d75-a21a-5c67155c233c.PNG)

Letters must be replaced by numbers in French version. I.e. `a)`, `b)`, `c)` to `1.`, `2.`, `3.`

**Comment by Intelligent2013** [comment]
Currently, Metanorma presentation XML has `type="alphabet` for sub-list:

```xml
<ol id="_" type="alphabet_upper">
	<li>
		<p id="_">En ce qui concerne les prototypes internationaux :</p>
		<ol id="_" type="alphabet">
			<li>
				<p id="_">Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
```

Adoc:
```
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:

.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
```

I'll try to specify `[arabic]` for nested list (https://www.metanorma.org/author/bipm/authoring/#ordered-lists):
```
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:

[arabic]
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
```

**Comment by Intelligent2013** [comment]
Metanorma XML is wrong - the nested list marked up as standalone list and the main list item `En ce qui concerne les prototypes nationaux` is as sub-item...:
```xml
<ol id="_" type="alphabet_upper">
	<li>
		<p id="_">En ce qui concerne les prototypes internationaux :</p>
	</li>
</ol>
<ol id="_" type="arabic">
	<li>
		<p id="_">Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
désormais, à la température de la glace fondante, l’unité métrique de longueur<bookmark id="_88b6cbc0-88d6-4cb6-bf58-2b3aa20db3fe"/>.</p>
	</li>
	<li>
		<p id="_">Le Prototype du kilogramme<bookmark id="_7c2f8a97-7cdb-4774-bd60-f12b5d69248f"/> adopté par le Comité international. Ce prototype sera considéré
désormais comme unité de masse<bookmark id="_bd0a2699-edf0-4547-9d71-f427b02c9de8"/>.</p>
	</li>
	<li>
		<p id="_">L’échelle thermométrique centigrade à hydrogène par rapport à laquelle les équations des
Mètres prototypes ont été établies.</p>
		<ol id="_" type="arabic">
			<li>
				<p id="_">En ce qui concerne les prototypes nationaux :</p>
			</li>
		</ol>
	</li>
</ol>
```

@opoudjis could you help?

**Comment by opoudjis** [comment]
Good God. French and English have different ordered list types?! Really?! And with dots at that?!

But it seems that is not what you are asking. What you are asking about is 

````
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:

[arabic]
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
````

being parsed as two separate lists, with Metanorma ignoring the nestedness of the `..` item.

That is an Asciidoctor bug when the second list is styled, which means Metanorma never finds out that the second list is indented. All of the following parse correctly:

````
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:
[arabic]
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
````

````
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:
+
--
[arabic]
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
--
````

and

````
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:

.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
````

preserves nesting.

Blank lines between ordered list nesting levels in Asciidoctor markup are a bad idea. Avoid them.

**Comment by Intelligent2013** [comment]
Confirmed. Adoc:
```
[upperalpha]
. En ce qui concerne les prototypes internationaux{nbsp}:
[arabic]
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
```
renders in PDF:
![image](https://user-images.githubusercontent.com/5559926/191705348-7a0fcc08-dc4c-4abc-bfed-725e92b6e3d7.png)

@opoudjis thanks!

@manuelfuenmayor please make updates as specified.
