### ISSUE TITLE
Brochure: Add space before semicolon in NOTE blocks (French version)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#201]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/191 (and https://github.com/metanorma/bipm-si-brochure/issues/190)

In French version, we need to insert a blank space before the colon in NOTE blocks.

For example:
```adoc
NOTE: Le gray est l’unité SI de ((dose absorbée)). Dans le domaine des ((rayonnements ionisants)), le
gray peut encore être employé avec d’autres grandeurs physiques qui s’expriment aussi en
joules par ((kilogramme)){nbsp}; le Comité consultatif des unités est chargé d’étudier cette question en
collaboration avec les organisations internationales compétentes.
```
renders:
![issue28-1](https://user-images.githubusercontent.com/33627611/190712727-263e5290-dd2f-41a8-8d55-2bd71bb5b94b.PNG)

Here, the presentation should be: *"Note : Le gray..."*

**Comment by Intelligent2013** [comment]
It seems this issue is my. In XSLT there is special processing for `note/name` title.
Currently, presentation XML is:
```xml
<note id="_">
	<name>NOTE</name>
	<p id="_">Le gray est l’unité SI
```

But in all sections except preface we have to render:
- for French
   - `Remarque` for the note in the list
   - `Note` in another cases
- for English
   - `Note`

```xml
<xsl:choose>
	<xsl:when test="$curr_lang = 'fr'">
		<xsl:choose>
			<xsl:when test="ancestor::bipm:li">Remarque: </xsl:when>
			<xsl:otherwise>Note: </xsl:otherwise>
		</xsl:choose>
	</xsl:when>
	<xsl:otherwise>Note: </xsl:otherwise>
</xsl:choose>
```
So, I have to add space before `:` for French.

**Comment by Intelligent2013** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/5559926/190874507-fb5b3918-7778-4988-a8d6-31923ec3ab10.png)

**Comment by manuelfuenmayor** [comment]
Confirmed!
