### ISSUE TITLE
Brochure: Move the position of a side note

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#202]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

Question from BIPM:

> 36 | 80 | side note (1) | The place of this side note follows the general scheme to anchor all side notes at the beginning of the section. In this case, the use of the reference is two pages later. Is there a simple way to bring the note closer to this place?

There is a side note that is not getting placed to the side of the content where it was referenced:

![issue36-1](https://user-images.githubusercontent.com/33627611/190726793-d2e8372d-e5fe-4430-b5e5-8faa0cbb050f.PNG)

The highlighted side note should be (ideally) placed close to the side of this content:
![issue36-2](https://user-images.githubusercontent.com/33627611/190726906-14cbd16f-7b87-46ae-be18-b3276a14d906.PNG)

Is it possible to achieve this?

**Comment by Intelligent2013** [comment]
There is a similar case a few pages above, but it renders ok:
![image](https://user-images.githubusercontent.com/5559926/190863405-8fb76226-2cb4-42b3-88a3-0362d7c57733.png)


Hmm, I've tried to remove the note for header:
![image](https://user-images.githubusercontent.com/5559926/190863227-f602d9f8-e127-4ce0-9a0a-a4f52951c4bf.png)
and after that the footnote `(1)` moved down as expected:
![image](https://user-images.githubusercontent.com/5559926/190863254-c074cb76-1cf2-447f-b4da-169ac5600f45.png)

I'll investigate it, the logic of XSLT layout is very complicated due side notes, so the fix will not so quick.

**Comment by Intelligent2013** [comment]
I've found why we've moved the list's side notes near the title. Almost two year ago we've tried a different options: see experiments here https://github.com/metanorma/mn-native-pdf/issues/268 and the best option was 

> 1. Merge side notes from level 4 (Resolution level) to level 3 in annexes.

realized in https://github.com/metanorma/mn-native-pdf/issues/271.

**Comment by ronaldtse** [comment]
As stated in https://github.com/metanorma/mn-native-pdf/issues/268#issuecomment-714524889 , it is already the best we can do with automatic flow. The reason why the asterisk notes and numbered notes are combined, is that the height of the asterisk notes and the numbered notes share the same vertical space in the side bar. 

I will communicate this to BIPM.

**Comment by ronaldtse** [comment]
Closing.
