### ISSUE TITLE
Brochure: Fix superscript for the "e"

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#204]
In relation to https://github.com/metanorma/bipm-si-brochure/issues/190

In Brochure French version.

From first line of the ToC:
![issue8-1](https://user-images.githubusercontent.com/33627611/190840146-6d437a62-5d78-4ffe-865c-2deb2eda83ed.PNG)

From header of the preface:
![issue8-2](https://user-images.githubusercontent.com/33627611/190840148-38598ab5-4390-4de0-8b1f-c5261be981bd.PNG)

The "e" is a supercript of "9".

Correct presentation:
![issue8-3](https://user-images.githubusercontent.com/33627611/190840244-c5e228d8-ec90-45f0-b0fa-3becceec95e4.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
> From first line of the ToC:

![image](https://user-images.githubusercontent.com/5559926/190874434-bbedc6c6-515f-4a95-b51d-f81bbd6ad732.png)

> From header of the preface:

![image](https://user-images.githubusercontent.com/5559926/190874454-0dd4a468-fdaf-4076-926a-2f9ab05d20de.png)

**Comment by manuelfuenmayor** [comment]
Confirmed! Thanks.
