### ISSUE TITLE
Listing CIPM, CGPM and CCTF Meetings, Recommendations etc. in the Bibliography

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#213]
CIPM, CGPM, and CCTF references weren't needed to be listed in the Bibliography/References section of the BIPM SI Brochure. However, documents in Recommended values of standard frequencies (https://github.com/metanorma/bipm-si-brochure/tree/main/sources/rec-values) do list references of these types in their Bibliography/References sections.

Example from https://www.bipm.org/documents/20126/41513479/Neutral_H_1233THz_2015.pdf/c4cdadd0-facf-457f-ca13-52a799b06ad2:
![image](https://user-images.githubusercontent.com/55683568/196534921-6b7bc48e-20df-4e21-bce3-13733836e446.png)

Current state:

````
== testing

referencing <<matveev>>, <<cipm-rec2>>, <<CR1971>> and <<cctf-rec2>>

[bibliography]
== References

* [[[cipm-rec2,(1)CIPM Recommendation 2 (2015)]]], CIPM Recommendation 2 (CI-2015): Updates to the list of standard frequencies http://www.bipm.org/jsp/en/CIPMRecommendations.jsp

* [[[parthey,2]]], C. G. Parthey, A. Matveev, J. Alnis, B. Bernhardt, A. Beyer, R. Holzwarth, A. Maistrou, R. Pohl, K. Predehl, T. Udem, T. Wilken, N. Kolachevsky, M. Abgrall, D. Rovera, C. Salomon, P. Laurent, and T. W. Hänsch: Improved Measurement of the Hydrogen 1S--2S Transition Frequency, _Phys. Rev. Lett._ *107*, 203001 (2011).

* [[[matveev,3]]], A. Matveev, Ch. G. Parthey, K. Predehl, J. Alnis, A. Beyer, R. Holzwarth, Th. Udem, T. Wilken, N. Kolachevsky, M. Abgrall, D. Rovera, Ch. Salomon, Ph. Laurent, G. Grosche, O. Terra, Th. Legero, H. Schnatz, S. Weyers, B. Altschul, Th. W. Hänsch: Precision Measurement of the Hydrogen stem:[1S - 2S] Frequency via a 920-km Fiber Link, _Phys. Rev. Lett._ *110*, 230801 (2013).

* [[[cctf-rec2,(4)CCTF Recommendation 2 (1970)]]]

* [[[CR1971, CGPM Meeting 14]]]
````

![image](https://user-images.githubusercontent.com/55683568/196535518-0da85df3-8e67-4491-8c5a-0fe05fc8165c.png)

**Comment by opoudjis** [comment]
Having the visibility of references depend on the type of document is [censored], but this is not the first or the last [censored] editorial decision coming out of BIPM...
