### ISSUE TITLE
BIPM "short references" to outcomes: Resolutions, Decisions, Recommendations, Statements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#216]
As agreed with BIPM's Janet Miles:

## Basic pattern

General:
```
Long: {group name} -- {type} {number} ({year})
Short: {group name} -- {type-abbrev} {number} ({year}, {lang})
```

## Special case pattern

The basic pattern works fine for all.

Except for these 2 cases:
* Decisions of the CIPM (since 2012)
* Recommendations/Resolutions/Decisions of the JCRB

Where the committee name is part of the outcome identifier:

Special cases:
```
Decision CIPM/111-10 (2022) / Décision CIPM/111-10 (2022)
Recommendation JCRB/43-1 (2021) / Recommandation JCRB/43-1 (2021)
```

## Single language version (English)

`type` can be:
* Resolution (RES)
* Recommendation (REC)
* Decision (DECN)
* Statement (DECL)

e.g.
```
CCTF -- Recommendation 2 (1970)
CCTF -- REC 2 (1970, EN)
```

Special cases:
```
Decision CIPM/111-10 (2022)
CIPM DECN CIPM/111-10 (2022, EN)
Recommendation JCRB/43-1 (2021)
JCRB REC JCRB/43-1 (2021, EN)
```

## Single language version (French)

`type` can be:
* Résolution (RES)
* Recommandation (REC)
* Décision (DECN)
* Déclaration (DECL)

e.g.
```
CCTF -- Recommandation 2 (1970)
CCTF -- REC 2 (1970, FR)
```

Special cases:
```
Décision CIPM/111-10 (2022)
CIPM DECN CIPM/111-10 (2022, FR)
Recommandation JCRB/43-1 (2021)
JCRB REC JCRB/43-1 (2021, FR)
```

## Dual language version (language independent version)

`type` can be in their respective languages or the following abbreviations:
* RES
* REC
* DECN
* DECL
 
```
CCTF -- Recommandation 2 (1970) / Recommendation 2 (1970)
CCTF REC 2 (1970)
```

Special cases:
```
Decision CIPM/110-10 (2022) / Décision CIPM/111-10 (2022)
CIPM DECN CIPM/110-10 (2022)
Recommendation JCRB/43-1 (2021) / Recommandation JCRB/43-1 (2021)
JCRB REC JCRB/43-1 (2021)
```

**Comment by opoudjis** [comment]
No idea what I am meant to do with this, and I cannot do anything with it until https://github.com/relaton/relaton-bipm/issues/34 is actioned anyway.

**Comment by opoudjis** [comment]
References can now be entered in short format, and will continue to be referenced in long format. That was always going to flow through immediately from relaton-bipm:


````
        [bibliography]
        == Bibliography
        * [[[a1,CGPM -- Meeting 1 (1889)]]]
        * [[[a2,BIPM DECN CIPM/101-1 (2012, EN)]]]
      INPUT

      output = <<~OUTPUT
        <sections>
          <clause id='_' obligation='normative'>
            <title>Clause</title>
            <p id='_'>
            <eref type="inline" bibitemid="a1" citeas="CGPM — Meeting 1 (1889)"/>
            <eref type="inline" bibitemid="a2" citeas="Decision CIPM/101-1 (2012)"/>
            </p>
          </clause>
        </sections>
      OUTPUT
````

````
        [bibliography]
        == Bibliography
        * [[[a2,BIPM DECN CIPM/101-1 (2012, FR)]]]
        * [[[a1,CGPM -- Meeting 1 (1889)]]]
      INPUT

      output = <<~OUTPUT
        <sections>
          <clause id='_' obligation='normative'>
            <title>Clause</title>
            <p id='_'>
            <eref type="inline" bibitemid="a1" citeas="CGPM — Réunion 1 (1889)"/>
            <eref type="inline" bibitemid="a2" citeas="Décision CIPM/101-1 (2012)"/>
            </p>
          </clause>
        </sections>
      OUTPUT
````

There is nothing further to be done in Metanorma for this ticket, and indeed **there never was**. Closing this.
