### ISSUE TITLE
Broken rendering (or encoding?) of EXAMPLEs (possibly NOTEs?) in terms

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#244]
In this document:
* https://github.com/metanorma/bipm-si-brochure/blob/main/sources/bipm-outcomes-en.adoc

The EXAMPLEs are rendered without proper style and runs into the example content.
<img width="531" alt="Screen Shot 2023-02-07 at 11 35 50 AM" src="https://user-images.githubusercontent.com/11865/217142143-4ef9b4c1-aa09-428c-8185-543b65811ffd.png">

A typical EXAMPLE in BIPM looks like this (from the same document):
<img width="471" alt="Screen Shot 2023-02-07 at 11 37 23 AM" src="https://user-images.githubusercontent.com/11865/217142173-10e774a2-f4cd-4b28-adb8-60692d3a2e0e.png">

I'm not sure whether this is an encoding or rendering issue, hence tagging both of you.

**Comment by Intelligent2013** [comment]
This is a rendering issue due the wrong styles for `termexample` element. I don't figure out why I've missed it. Will fix.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
@Intelligent2013 can you also review the `termnote` style? Thanks.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can you also review the `termnote` style? Thanks.

@ronaldtse currently, in the BIPM brochure, `note`'s render in three manner:
- in the main section - as side notes (on the right page margin), 
- in the preface section - as main text with 'NOTE:' title:
![image](https://user-images.githubusercontent.com/5559926/217169274-eca9ab29-b7d3-497e-80d2-5129a3161292.png)
- in the quote text - as main text with 'Note:' title: 
![image](https://user-images.githubusercontent.com/5559926/217169427-72fe9920-8dbd-4284-860f-3d39eb877298.png)

I think enough to fix the bottom margin (in XSLT) and add the colon after `to entry` (in metanorma gem by @opoudjis):

Currently:
![image](https://user-images.githubusercontent.com/5559926/217170260-97bf868c-314a-487d-b40e-41703b2abd4b.png)


After changes:
![image](https://user-images.githubusercontent.com/5559926/217170219-63106e51-ec08-45bc-9d85-61884a966688.png)

Right?

**Comment by ronaldtse** [comment]
Agree. Thanks @Intelligent2013 !

**Comment by Intelligent2013** [comment]
@opoudjis currently, in BIPM presentation XML, colon is missing in `termnote/name` at the end:
```xml
<termnote id="_"><name>Note 1 to entry</name><p id="_">Information resource can refer to an asset, a record, a dataset, a
document or a component part of a document.</p>
</termnote>
```
Could you add it? Thanks.

**Comment by Intelligent2013** [comment]
BIPM XSLT updated for `termexample` and `termnote` rendering:
![image](https://user-images.githubusercontent.com/5559926/217220916-bedc9004-8fd0-451a-aa1f-5f9f1fb03f7a.png)

(`:` after `Note 1 to entry` added manually just for demo)

**Comment by opoudjis** [comment]
I've added the colon; is there anything else needed for this ticket?

**Comment by ronaldtse** [comment]
Confirm fixed.

<img width="749" alt="Screenshot 2023-02-25 at 2 22 48 PM" src="https://user-images.githubusercontent.com/11865/221342189-6cd47ce5-0d5d-4bef-a4cf-48fbf5938f22.png">
