### ISSUE TITLE
(PDF) Brochure: Horizontal misalignment in ToC of Annex 1

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#287]
In relation to https://github.com/metanorma/bipm-si-brochure/pull/213

In the ToC of Annex 1, there is a horizontal misalignment between the first column and the second:
    Generated French version:
    ![brochure-issue-3-fr](https://user-images.githubusercontent.com/33627611/232920952-4fd6923d-f99b-4055-8fb2-01f6b3aa3308.PNG)

On the English version, the misalignment occurs in a different manner -- there are random line breaks in the first column:
    Generated English version:
    ![brochure-issue-3-en](https://user-images.githubusercontent.com/33627611/232921284-f92d66c3-4731-40a6-a8ec-013fea621815.PNG)

**Comment by Intelligent2013** [comment]
> In the ToC of Annex 1, there is a horizontal misalignment between the first column and the second:

It occurs due the superscript `e` in the 1st column (base-line shift). I'll fix it.

> On the English version, the misalignment occurs in a different manner -- there are random line breaks in the first column:

In the presentation XML, the ToC represents as list:
```xml
<toc>
	<ul id="_d3414b9b-6b9f-af12-1615-75b5173b4633">
		<li>
			<p id="_8cb8fc78-c5af-a103-29e1-ce06a3ecf6e8">
				<xref target="cgpm9th1948r6" style="short">[cgpm9th1948r6]<tab/>9th CGPM, 1948:<tab/>decision to establish the SI</xref>
			</p>
		</li>
		<li>
			<p id="_af100f6f-9268-1eec-eeff-3fa849276806">
				<xref target="cgpm10th1954r6" style="short">[cgpm10th1954r6]<tab/>10th CGPM, 1954:<tab/>decision on the first six base units<bookmark id="_c806106e-4185-45e7-92ac-2e933142cf49"/>
				</xref>
			</p>
		</li>
```

but it renders in the PDF as the table. I'll try to fix it by displaying 1st column with non-break spaces.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/233050650-778596a8-2e02-4799-b494-b78fbcab8ab0.png)

![image](https://user-images.githubusercontent.com/5559926/233050838-1f6b96c1-48b7-483e-8cbc-27aacf3c6144.png)

BIPM XSLT will be available in metanorma-bipm soon.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
