### ISSUE TITLE
Brochure: Refer to French websites in references

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#288]
In relation to https://github.com/metanorma/bipm-si-brochure/pull/213

In French version, references that refer to an external website (i.e. hyperlinks), they do it to the English version of
the website instead of the French version.

For example, in the highlighted reference below:
![refs-2-fr](https://user-images.githubusercontent.com/33627611/232922945-a61793d4-1a42-4bfc-92db-530b93d28423.PNG)

The hyperlink of *CIPM — Recommandation 5 (1989)* leads to:
https://www.bipm.org/en/committees/ci/cipm/78-1989/resolution-5
instead of:
https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5

I'm not sure if this should be considered an (important) issue.

**Comment by ronaldtse** [comment]
@manuelfuenmayor this is an important issue, thank you for finding this.

Basically, Metanorma should be using the French version of the same Relaton item (name and link).

Right now, Relaton returns the same item regardless of the input syntax, and already provides the French content:

```sh
$ bundle exec relaton fetch "CIPM Recommandation 5 (1989)"
<bibdata type="proceedings" schema-version="v1.2.3">
  <fetched>2023-04-19</fetched>
  <title format="text/plain" language="en" script="Latn">The International Temperature Scale of 1990</title>
  <title format="text/plain" language="fr" script="Latn">L’Échelle internationale de température de 1990</title>
  <uri type="citation" language="en" script="Latn">https://www.bipm.org/en/committees/ci/cipm/78-1989/resolution-5</uri>
  <uri type="citation" language="fr" script="Latn">https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5</uri>
  <uri type="src" language="en" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-en/meeting-78.yml</uri>
  <uri type="src" language="fr" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-fr/meeting-78.yml</uri>
  <uri type="pdf">https://www.bipm.org/documents/20126/17315032/CIPM78.pdf/078200cd-d8b2-f33b-da22-a2a3badeee10</uri>
  <docidentifier type="BIPM" primary="true">CIPM -- Recommendation 5 (1989)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en" script="Latn">CIPM -- Recommendation 5 (1989)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr" script="Latn">CIPM -- Recommandation 5 (1989)</docidentifier>
  <docnumber>CIPM -- Recommendation 5 (1989)</docnumber>
  <date type="published">
    <on>1989-09-28</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <contributor>
    <role type="author"/>
    <organization>
      <name language="en" script="Latn">International Committee for Weights and Measures</name>
      <name language="fr" script="Latn">Comité International des Poids et Mesures</name>
      <abbreviation>CIPM</abbreviation>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
  <place>
    <city>Paris</city>
  </place>
  <ext schema-version="v1.0.0">
    <doctype>recommendation</doctype>
    <structuredidentifier>
      <docnumber>5</docnumber>
    </structuredidentifier>
  </ext>
</bibdata>
```

See the attributes: `title`, `uri`, `docidentifier`, `contributor`. 

However, I am seeing that there are 2 issues:

`language` is not in an array.
```xml
  <language>en</language>
  <language>fr</language>
```

`contributor author` is not localized in French:
```xml
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
```

The Relaton item is also missing the language-independent document identifier described [here](https://metanorma.github.io/bipm-editor-guides/documents/bipm-outcomes-en.html).

I will move the Relaton issues to a new ticket.

**Comment by ronaldtse** [comment]
Sorry I made a mistake -- the title and docidentifier are indeed already localized in Metanorma. It is only the `uri` that is not.

**Comment by opoudjis** [comment]
Cannot replicate in a small French document, one paragraph long:

````
<p id="_54aff993-77ec-4e66-34e4-635a62492bce">Le kelvin<a id="_9c7f0c76-4861-4b48-a43c-150c6c39ff15"></a> et le degré Celsius<a id="_e002947c-0adf-4b29-977a-d03b2b673586"></a> sont aussi les unités de l’Échelle internationale de température
de 1990 (EIT-90) adoptée par le CIPM en 1989 dans sa Recommandation 5 (CI-1989, <a href="https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5">CIPM — Recommandation 5 (1989)</a>).</p>
````

That URI is localised, just as its title is.

When I compile si-brochure-fr.adoc on its own, no difference, the link is French.

**Comment by opoudjis** [comment]
The use of the citation URL instead of a link to the bibliography is currently exclusive to HTML; the HTML has hyperlink to French, the PDF hyperlink to English (because it does not have the localisation of URIs that the HTML has implemented). 

The introduction of the citation URL, complete with localisation, should be generalised to Presentation XML, rather than left to HTML and PDF separately.

@Intelligent2013 This means that I will be converting an `eref` to a `bibitem` with `uri[@type = 'citation']` into a hyperlink to that URI in Presentation XML, and you need not implement that independently; I am localising the URI to language, and you until now haven't been, so I'll move that logic from HTML to Presentation XML.
