### ISSUE TITLE
Brochure: Misplaced NOTE block

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#292]
*Issue found in https://github.com/metanorma/bipm-si-brochure/pull/213*

An instance of `NOTE` expected to appear at the end of an unordered list block
 it gets placed earlier in between list items:

Generated:
![issue-2-generated](https://user-images.githubusercontent.com/33627611/234137335-0ac051dc-81cb-461c-893f-4bbf1fd6570b.PNG)

Original:
![issue-2-original](https://user-images.githubusercontent.com/33627611/234137340-00c4b337-cf74-4f51-86d2-23c506936ad1.PNG)

**Comment by Intelligent2013** [comment]
Issue on the page 81 in the generated PDF:
![image](https://user-images.githubusercontent.com/5559926/234189935-c1e9a0f7-db4d-4b02-8689-d103229d3b5a.png)

**Comment by Intelligent2013** [comment]
Generated in Sep, 2022:
![image](https://user-images.githubusercontent.com/5559926/234191097-6f911580-477b-4fda-8cd9-8348a7e11fd7.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/234234004-47d768cc-5e2c-49c6-8ec8-4f6d96f1ec9c.png)

**Comment by manuelfuenmayor** [comment]
Confirmed fixed. Thanks @Intelligent2013!
