### ISSUE TITLE
Brochure: Certain NOTE blocks are not shown

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#293]
*Issue found in https://github.com/metanorma/bipm-si-brochure/pull/213*

Certaing `NOTE` blocks are not appearing in PDF outputs.

For example:

Generated:
![issue-1-generated](https://user-images.githubusercontent.com/33627611/234136634-b4c48225-8e98-42d0-a31d-abe9f90db152.PNG)

Original:
![issue-1-original](https://user-images.githubusercontent.com/33627611/234136640-831095bc-a7b5-4ce6-a93f-31de80b7cb78.PNG)

Another example:

Generated:
![issue-1-2-generated](https://user-images.githubusercontent.com/33627611/234136702-dbdd7f76-eb54-49c8-a0f2-04344fcfa194.PNG)

Original:
![issue-1-2-original](https://user-images.githubusercontent.com/33627611/234136711-ea62f30b-c09b-40ce-b01d-0f11030ef260.PNG)

**Comment by Intelligent2013** [comment]
For 1st example, 'note' moved under the 1st list item, the issue similar to https://github.com/metanorma/metanorma-bipm/issues/292
![image](https://user-images.githubusercontent.com/5559926/234201624-dcfb75c0-4fbe-4e9a-a046-7bf601299ba3.png)

> Another example:

Note is missing at all.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/234233615-4f3b9109-ee8f-4647-91a2-29ce3996a40b.png)

![image](https://user-images.githubusercontent.com/5559926/234233818-1c835c6b-5a9c-426d-9c60-8d3897ee8081.png)

**Comment by manuelfuenmayor** [comment]
Confirmed fixed, closing.
