### ISSUE TITLE
(URGENT) Brochure: Extra blank page in ToC

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#296]
*Issue found in https://github.com/metanorma/bipm-si-brochure/pull/213*

This issue was not before.
There is a blank page at the beginning to the Table of Contents:

![issue-1-generated](https://user-images.githubusercontent.com/33627611/234733263-cb4fd460-c3ba-4a4c-8f20-addab757ccf8.PNG)

**Comment by Intelligent2013** [comment]
The issue occurs due the new element `clause[@type='toc']`:
```
<preface>
		<clause type="toc" id="_27549cd1-1c48-4300-8b0f-837f229aae76" displayorder="1">
			<title depth="1">Contents</title>
		</clause>
```
It fixed in https://github.com/metanorma/mn-native-pdf/issues/563, but not merged yet.

**Comment by Intelligent2013** [comment]
BIPM XSLT updated.

**Comment by manuelfuenmayor** [comment]
Confirmed fixed, closing.
