### ISSUE TITLE
(URGENT) Brochure: Prefatory content should be before Table of Contents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#297]
*Issue found in https://github.com/metanorma/bipm-si-brochure/pull/213*

According to original source (and previous generated documents) the *The BIPM and the Metre Convention*
prefatory section should be placed *before* the Table of Contents, and also, should not be included in the ToC.

Generated:
![issue-2-1-generated](https://user-images.githubusercontent.com/33627611/234734159-6d3370d3-bb00-4273-8a1a-5e8195122bc3.PNG)

![issue-2-generated](https://user-images.githubusercontent.com/33627611/234734054-94c07df1-cd7e-4184-ab98-58fa03d35141.PNG)

**Comment by Intelligent2013** [comment]
It's side effect after introducing `clause[@type='toc']`.
Fixed in https://github.com/metanorma/mn-native-pdf/issues/563, but not merged yet.

**Comment by Intelligent2013** [comment]
BIPM XSLT updated:
![image](https://user-images.githubusercontent.com/5559926/234788999-40b283a8-fbe3-44ec-82fd-1705c70b9650.png)

**Comment by manuelfuenmayor** [comment]
Confirmed fixed, closing.
