### ISSUE TITLE
Handling units in UnitsML with MathML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#3]
W3C MathML Units: https://www.w3.org/TR/mathml-units/

BIPM is all about defining units and we should represent their units properly (later)

**Comment by ronaldtse** [comment]
I have contacted people involved in the OASIS/NIST UnitsML to see whether that work is still active.

**Comment by opoudjis** [comment]
We have implemented asciimath2unitsml as a gem, and this allows us to implement units rendering.

Need to consume UnitsML annotations, then extract them into one place in the XML document. May need to extend units parsing to deal with division of units.

**Comment by ronaldtse** [comment]
We should actually integrate that gem into plurimath so metanorma doesn’t need to care about it.

**Comment by opoudjis** [comment]
I don't know how you think that's going to work, but Metanorma needs to rearrange the UnitsML content it receives to be unique instances in the document: Metanorma does have to worry about it.

**Comment by opoudjis** [comment]
Will move UnitsML content to a MiscContainer element between bibdata and boilerplate, containing arbitrary elements in any namespace.
