### ISSUE TITLE
(URGENT) Brochure: Tables embedded in list items show bigger font size

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#302]
*Issues found in https://github.com/metanorma/bipm-si-brochure/pull/213*

Tables that are embedded in list items:

```adoc
* text
+
--
|===
...
|===
--
````

...Show slightly bigger font size.

For instance:

Generated:
![issue-2-generated](https://user-images.githubusercontent.com/33627611/234951358-1a66b5c3-7643-41ef-ab2a-4cf65cc6a4bc.PNG)

Original:
![issue-2-original](https://user-images.githubusercontent.com/33627611/234951382-cf196318-3b15-4606-9a62-5a46d244e894.PNG)

This issue applies for both English and French versions.

(Sorry I didn't not notice this issue before.)

**Comment by Intelligent2013** [comment]
BIPM XSLT fixed:
![image](https://user-images.githubusercontent.com/5559926/234978214-e4044855-39a6-4d98-8162-b3351c981045.png)

**Comment by manuelfuenmayor** [comment]
Confirmed fixed. Thanks @Intelligent2013!
