### ISSUE TITLE
JCGM: Uppercased math letters render straight instead of italic

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#312]
*Issue found in https://github.com/metanorma/mn-samples-jcgm/pull/27*

`stem:[Y]` renders as:

```xml
<semantic__mi mathvariant="normal">Y</semantic__mi>
````

Is that on purpose?

**Comment by ronaldtse** [comment]
@manuelfuenmayor I believe this aligns with ISO 80000-2 practice.
