### ISSUE TITLE
JCGM: Encoding particular math letters

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#315]
*Issue found in https://github.com/metanorma/mn-samples-jcgm/pull/27*

In JCGM 106, there these math letters that I'm not sure how to encode:

![issue7-original-2](https://user-images.githubusercontent.com/33627611/236960976-1810dca7-7378-45ae-9502-07af60a32b70.PNG)
![issue7-original-1](https://user-images.githubusercontent.com/33627611/236960984-c480b3aa-8ac9-46fa-bf1e-5686b94f69a0.PNG)

In the meantime, I've marked them as: `sf(A)` and `sf(C)`.

**Comment by opoudjis** [comment]
These are intended to be script, which is `cc(A), cc(C)`. (It's a bad choice of font in Zapf Chancery, but Script is the intent.)

**Comment by opoudjis** [comment]
I see from https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference that LaTeX differentiates between Script and Calligraphic, and these characters are Calligraphic. Asciimath implementations do not make that distinction, and nor does MathML (Fraktur is of course not the same as either), and nor does Unicode. Make it script.
