### ISSUE TITLE
GHA fails on merge?

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#316]
https://github.com/metanorma/metanorma-bipm/actions/runs/4940337667

https://github.com/metanorma/metanorma-bipm/actions/runs/4940317005

**Comment by opoudjis** [comment]
No GHA jobs are running:

https://github.com/metanorma/metanorma-standoc/actions/runs/4940635668
https://github.com/metanorma/metanorma-standoc/actions/runs/4940617578

**Comment by CAMOBAP** [comment]
Looks like GH Infrastructure is experience issues

<img width="640" alt="Screenshot 2023-05-10 at 9 39 25 PM" src="https://github.com/metanorma/metanorma-bipm/assets/2169738/289dbb7b-58d5-4e6c-9876-573b3895e018">

**Comment by ronaldtse** [comment]
I think this was a GHA issue that is now resolved. Closing.
