### ISSUE TITLE
BIPM review on document layout for "mise en pratique"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#32]
From BIPM:

> In the mise en pratique for the ampere I observed the following:
>  
> * ~~On the title page “Brochure sur le SI” should be replaced by “Le système international d’unités”, which is the equivalent of the English wording.~~ (done in metanorma/bipm-si-brochure#31)
> * "1. Edition 2019" should be replaced with "9. Edition 2019", also on page 3
> * ~~“’Mise en pratique” should always be italicized in English text.~~ (done in metanorma/bipm-si-brochure#31)
> * Each section starts on a new page, which is strange when the sections are as short as in this document.
> * The symbol for the elementary charge “e” should always be italicized.
> * In numbers with many digits, they should be grouped by three for better readability:
>   * page 5: 1.602176634  -> 1.602 176 636
>   * page 7: 483597.848416984 -> 483 597.848 416 984
> * The spaces need to be protected against line-breaks
> * Page 6: in the original text, lists were not numbered but had letters (a), (b), (c), …
> * References to “sections” have become references to “clauses”
> * References to “equations” have become references to “formulas”
> * Pages 8 and 16: Wrong font size in the header
> * Page 17: “References” have become “Bibliography”.

I believe the title page titles are encoded in the sample document as document attributes. @manuel489 can you help update the mise en pratiques? Thanks.

**Comment by manuel489** [comment]
> I believe the title page titles are encoded in the sample document as document attributes. @manuel489 can you help update the mise en pratiques? Thanks.

Sure, PR link is shown above.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

**Comment by Intelligent2013** [comment]
> "1. Edition 2019" should be replaced with "9. Edition 2019", also on page 3

Need to source data fix.

> Each section starts on a new page, which is strange when the sections are as short as in this document.

I'll add section text length check.

>The symbol for the elementary charge “e” should always be italicized.
>In numbers with many digits, they should be grouped by three for better readability:
>    page 5: 1.602176634 -> 1.602 176 636
>    page 7: 483597.848416984 -> 483 597.848 416 984

Need to source data fix.

> The spaces need to be protected against line-breaks

What does mean?

> Page 6: in the original text, lists were not numbered but had letters (a), (b), (c), …

Need to source data fix.

> References to “sections” have become references to “clauses”
> References to “equations” have become references to “formulas”

Need to source data fix.

> Pages 8 and 16: Wrong font size in the header

Done in https://github.com/metanorma/mn-native-pdf/issues/269

> Page 17: “References” have become “Bibliography”.

Need to source data fix.

**Comment by manuel489** [comment]
@Intelligent2013, ok. I'm taking care of the source data fix parts...

**Comment by manuel489** [comment]
>"1. Edition 2019" should be replaced with "9. Edition 2019", also on page 3

Fixed by markup in PR above.

> The symbol for the elementary charge “e” should always be italicized.
>In numbers with many digits, they should be grouped by three for better readability:
>page 5: 1.602176634 -> 1.602 176 636
>page 7: 483597.848416984 -> 483 597.848 416 984

Fixed by markup in PR above.

**Comment by manuel489** [comment]
> Page 6: in the original text, lists were not numbered but had letters (a), (b), (c), …

I don't understand this issue. The lists in [mise en pratique for ampere](https://github.com/metanorma/bipm-si-brochure/blob/master/sources/mep-ampere-definition-en.adoc) output are ordered by letters like: "a.", "b.", "c.", etc. If they should render as "(a)", "(b)", ... , then I believe it's not fixable by markup.

> References to “sections” have become references to “clauses”
> References to “equations” have become references to “formulas”

I believe this is not fixable by markup.

> Page 17: “References” have become “Bibliography”.

I believe this is not fixable by markup.

**Comment by opoudjis** [comment]
> I don't understand this issue. The lists in mise en pratique for ampere output are ordered by letters like: "a.", "b.", "c.", etc. If they should render as "(a)", "(b)", ... , then I believe it's not fixable by markup.

Note that I shall refuse, with extreme vehemence, to allow individual documents to change list markup from "a." to "(a)" or "a)" or "---->a", and I have been saying so in tickets. Such muddle-headed inconsistency between documents is a bug and not a feature, and I will not do anything to perpetuate it. _That's what Metanorma is for:_ to impose consistency.

> References to “sections” have become references to “clauses”
> References to “equations” have become references to “formulas”

BIPM need to provide assurance that all sections in BIPM publications are referred to as clauses, and all formulas are referred to as equations (or possibly inequations). I am not going to do document-specific fixes: that is not what Metanorma is for.

> Page 17: “References” have become “Bibliography”.

Again, need to ensure that is consistent practice: Metanorma imposes uniform clause titles.

I will investigate documents on BIPM site to see what the patterns are. But as I have said repeatedly, BIPM are NOT going to get solutions specific to a document.

**Comment by Intelligent2013** [comment]
> Each section starts on a new page, which is strange when the sections are as short as in this document.

1. I will display sections for MEP without page breaks, but in this case I have to change the header to 'Appendix X' instead of '<section title>', because jEuclid can't set font-size and font-name property via retrieve-marker mechanism.
2. If need pagebreak between concrete section, then put <<< to `<pagebreak/>`

**Comment by Intelligent2013** [comment]
> * Each section starts on a new page, which is strange when the sections are as short as in this document.
	
Done.

> * Page 6: in the original text, lists were not numbered but had letters (a), (b), (c), …

Done. The rule for 'alphabet' lists changed from `a)` to `(a)` for appendixes.

**Comment by ronaldtse** [comment]
From @Intelligent2013 

In the source PDF, the French part on page 72 (section Révision de la mise en pratique de la définition du mètre (PV, 70, 90-101 et Metrologia, 40, 103-133)) uses:
a)...
b)
c)

However, in the English part, page 181 (Revision of the practical realization of the definition of the metre (PV, 70, 194-204 and Metrologia, 40, 103-133) uses:
(a)
(b)
(c)

And there are:

<img width="494" alt="Screen Shot 2020-10-24 at 1 11 25 AM" src="https://user-images.githubusercontent.com/11865/97040474-8e394280-15a0-11eb-9c40-c137cc992f4a.png">

And
<img width="480" alt="Screen Shot 2020-10-24 at 1 13 40 AM" src="https://user-images.githubusercontent.com/11865/97040483-93968d00-15a0-11eb-82c6-05b32a4485ad.png">

Asked BIPM to see if they can accept a unified numbered list style.

**Comment by ronaldtse** [comment]
> > Each section starts on a new page, which is strange when the sections are as short as in this document.
> 
> 1. I will display sections for MEP without page breaks, but in this case I have to change the header to 'Appendix X' instead of '', because jEuclid can't set font-size and font-name property via retrieve-marker mechanism.
> 2. If need pagebreak between concrete section, then put <<< to `<pagebreak/>`

This is addressed in #48, we will start a new page per section for consistency.

**Comment by ronaldtse** [comment]
> Note that I shall refuse, with extreme vehemence, to allow individual documents to change list markup from "a." to "(a)" or "a)" or "---->a", and I have been saying so in tickets. Such muddle-headed inconsistency between documents is a bug and not a feature, and I will not do anything to perpetuate it. _That's what Metanorma is for:_ to impose consistency.

This is addressed in #47 , we will use "1." then "a)" as agreed with BIPM across all documents.

> > References to “sections” have become references to “clauses”
> > References to “equations” have become references to “formulas”
> > Page 17: “References” have become “Bibliography”.

> BIPM need to provide assurance that all sections in BIPM publications are referred to as clauses, and all formulas are referred to as equations (or possibly inequations). I am not going to do document-specific fixes: that is not what Metanorma is for.

I have confirmed in existing documents (SI Brochure, MEPs) that BIPM uses the following referential conventions:

* "Section X.X" or "section X.X" for clauses
* "Equation (n)" or "equation (n)" for formulas
* "References" as the section title for the bibliography.

We will implement these.

**Comment by opoudjis** [comment]
All issues raised addressed.
