### ISSUE TITLE
BIPM review on independently published SI Brochure Appendix 4

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#33]
From BIPM:

> I did not read Appendix 4 in detail. The only comment I have on the layout is that on the title page we should have “Le système international d’unités / The international system of units” instead of “Brochure sur le SI / SI Brochure”. This would be consistent with the present title page of the SI brochure.

I think this may simply be a problem with title specification in the text?

**Comment by Intelligent2013** [comment]
@ronaldtse yes, source text should be fixed:

In sib-a4-en.presentation.xml and sib-a4-fr.presentation.xml:
```xml
<title language="en" format="text/plain" type="main">SI Brochure</title>
...
<title language="fr" format="text/plain" type="main">Brochure sur le SI</title>
...

In another MEP xmls main title in English is OK:
```
<title language="en" format="text/plain" type="main">The International System of Units</title>
...
<title language="fr" format="text/plain" type="main">Brochure sur le SI</title>
```

**Comment by opoudjis** [comment]
Yes, fixing now in source.
