### ISSUE TITLE
JCGM: missing  `<p class="zzSTDTitle1"` in the Presentation XML

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#337]
Source ticket: https://github.com/metanorma/metanorma-ogc/issues/579

The presentation XML doesn't contain title in `<p class="zzSTDTitle1"`.

How to repeat:
```
git clone https://github.com/metanorma/mn-samples-jcgm
```

update `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "features/displayorder"
gem "metanorma-bipm", git: "https://github.com/metanorma/metanorma-bipm", branch: "features/displayorder"
```

```
cd sources/jcgm/106-2012-en
```
```
bundle exec metanorma -t bipm -x presentation document.adoc
```

Presentation XML:
```xml
	<sections>
		<clause id="_scope" type="scope" obligation="normative" displayorder="7">
			<title depth="1">1.<tab/>Scope</title>
```

**Comment by opoudjis** [comment]
I had removed the middle title from JCGM, but that was a logic error: it is BIPM straight, not JCGM, that lacks the middle title.

**Comment by Intelligent2013** [comment]
@opoudjis the title should contain the part title also.

The source document:
https://github.com/metanorma/mn-samples-jcgm/tree/main/sources/jcgm/106-2012-en
```adoc
:title-en: Evaluation of measurement data
:title-part-en: The role of measurement uncertainty in conformity assessment
```

Original PDF:
![image](https://github.com/metanorma/metanorma-bipm/assets/5559926/da79d69e-deab-4e80-8573-f2d0a974c900)


Current Presentation XML contains the main title only:
```xml
<sections>
	<p class="zzSTDTitle1" displayorder="4">Evaluation of measurement data</p>
	<clause id="_scope" type="scope" obligation="normative" displayorder="5">
		<title depth="1">1.<tab/>Scope</title>
```

**Comment by opoudjis** [comment]
Yeah, we have a problem here that

**Comment by opoudjis** [comment]
I'm using ISO code to generate the JCGM titles, so span="boldtitle" and span="nonboldtitle" now show up. I suggest we ignore them unless told otherwise by BIPM.

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
