### ISSUE TITLE
JCGM: wrong displayorder for Normative references

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#338]
Source document: https://github.com/metanorma/mn-samples-jcgm/sources/jcgm/106-2012-en

`<clause id="_scope" type="scope" obligation="normative" displayorder="7">`
vs.
`<references id="_normative_references" normative="true" obligation="informative" displayorder="5">`

The presentation XML:
```xml
<sections>
		<clause id="_scope" type="scope" obligation="normative" displayorder="7">
			<title depth="1">1.<tab/>Scope</title>
...
<references id="_normative_references" normative="true" obligation="informative" displayorder="5">
			<title depth="1">2.<tab/>Normative references</title>
</references>
</sections>
```
The resulted PDF:
![image](https://github.com/metanorma/metanorma-bipm/assets/5559926/d28157bf-ad44-4430-a6f7-74d333fb40f0)

**Comment by opoudjis** [comment]
<img width="899" alt="Screenshot 2023-07-31 at 20 25 09" src="https://github.com/metanorma/metanorma-bipm/assets/1911039/d9ef674e-7449-480c-822a-131cc3dc69a9">

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
