### ISSUE TITLE
SI brochure side note math equation out of bounds

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#35]
The equation of this particular note in clause 4 is out of bounds. If a source edit is necessary please indicate so. Thanks.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/11865/96816577-1d831080-1450-11eb-83af-873b2c5c87c8.png">

**Comment by Intelligent2013** [comment]
jEuclid doesn't support auto line-break in equations if resulted svg doesn't fit into area, and also doesn't support `linebreak` mathml feature. (https://www.oxygenxml.com/forum/topic16181.html)

The solutions:
1. it should be splitted into two equations 
2. encoded it as usual text.

**Comment by Intelligent2013** [comment]
From source docx:
![изображение](https://user-images.githubusercontent.com/5559926/96890561-6bb80400-1490-11eb-9111-3980167be1c1.png)

**Comment by ronaldtse** [comment]
Would jEuclid support using line breaks inside MathML?

**Comment by Intelligent2013** [comment]
> Would jEuclid support using line breaks inside MathML?

No.

**Comment by ronaldtse** [comment]
Then we can encode it as two equations.

**Comment by Intelligent2013** [comment]
> 
> 
> Then we can encode it as two equations.

@ronaldtse  for @manuel489 ?

**Comment by ronaldtse** [comment]
Yes, @manuel489 can you please help? Thanks!

**Comment by manuel489** [comment]
> Yes, @manuel489 can you please help? Thanks!

Sure, done in PR above.

**Comment by Intelligent2013** [comment]
Fixed. Thanks @manuel489!
![изображение](https://user-images.githubusercontent.com/5559926/97187958-0d529480-17b4-11eb-8862-4aff6090101b.png)
