### ISSUE TITLE
Add signatures of BIPM for SI Brochure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#36]
This is necessary for publication.

Original:
<img width="556" alt="Screen Shot 2020-10-22 at 10 27 48 AM" src="https://user-images.githubusercontent.com/11865/96817122-3d670400-1451-11eb-88c3-8ffcea236ceb.png">

Now:
<img width="576" alt="Screen Shot 2020-10-22 at 10 24 16 AM" src="https://user-images.githubusercontent.com/11865/96816903-bdd93500-1450-11eb-96bd-0970e59495e4.png">

Image files here:

![image-000](https://user-images.githubusercontent.com/11865/96817085-288a7080-1451-11eb-8a54-d98ad899982b.jpg)
![image-001](https://user-images.githubusercontent.com/11865/96817086-29bb9d80-1451-11eb-977a-c615d84189ec.jpg)
![image-002](https://user-images.githubusercontent.com/11865/96817088-29bb9d80-1451-11eb-86a4-76eade43c5d6.jpg)

**Comment by manuel489** [comment]
Signatures markup added in https://github.com/metanorma/bipm-si-brochure/pull/33.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
