### ISSUE TITLE
About :committee: validation

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#37]
When I set the `:committee:` attribute value to the full name of a BIPM consultative committee, for instance: 
`:committee: Consultative Committee for Length`

I get this message from compilation:

````
...
Metanorma XML Syntax: (XML Line 000043:57): character content of element "committee" invalid; must be equal to "BIPM", 
"CCAUV", "CCEM", "CCL", "CCL-CCTF", "CCM", "CCPR", "CCQM", "CCRI", "CCT", "CCTF", "CCU", "CGPM", "CIPM", "INetQI", "JCGM",
 "JCRB" or "JCTLM"
...
````

Which indicates that I should use the corresponding acronym instead, right? But, isn't the `:committee-acronym:` attribute used for that purpose already?

**Comment by opoudjis** [comment]
1, ignore that error, and 2, don't use `:committee:`. The error validation hasn't caught up yet, but I've abandoned `:committee:`. Use: `:committee-acronym:`, `:committee-en:`, and `:committee-fr:`. For the latest markup, refer to https://github.com/metanorma/metanorma-bipm/blob/master/README.adoc

**Comment by opoudjis** [comment]
Keeping this ticket open, but now it's about fixing the validation of committees.
