### ISSUE TITLE
Localisation of numbers

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#38]
In order to enable localisation of number rendering in BIPM, will do the following.

* All numbers to be localised in rendering must be marked up as `stem:[]`. Sorry @manuel489. So a number like 1337 must be marked up as `stem:[1337]`.
* Will create gem in plurimath to iterate through MathML, and change the rendering of any numbers in MathML in Presentation XML to localised versions of the numbers. BIPM's requirements are satisfied by twitter_cldr's `.localize(:fr).to_s`. twitter_cldr's localisations are configured in YAML, and we might need to inherit localisation from the gem and configure it likely for a flavour; that is not currently the case.
* Any MathML in Presentation XML that consists only of a number (after localisation) is converted to the string of that number.

**Comment by ronaldtse** [comment]
@opoudjis when you say stem:[] you mean number:[]? Are you saying all numbers have to be marked up as mathml?

**Comment by opoudjis** [comment]
Yes I am. We agreed on that.

**Comment by opoudjis** [comment]
> twitter_cldr's localisations are configured in YAML, and we might need to inherit localisation from the gem and configure it likely for a flavour; that is not currently the case.

In fact, ITU wants apostrophe as the numeral group separator, so we will need to configure twitter_cldr after all to realise that.

**Comment by manuel489** [comment]
> All numbers to be localised in rendering must be marked up as stem:[]. Sorry @manuel489. So a number like 1337 must be marked up as stem:[1337].

Does that include dates as well? What does "localisation of number rendering" mean? Is this for addressing the "group-by-three" issue in numbers with many digits? (specified in https://github.com/metanorma/metanorma-bipm/issues/32)

**Comment by ronaldtse** [comment]
> Does that include dates as well? 

This is a good question that @opoudjis and I also discussed. In fact there should be a `date:[]` and/or `year:[]` command that allows specifying such data (and localizing them).

So `stem:[]` should not be used with dates.

> What does "localisation of number rendering" mean? 
> Is this for addressing the "group-by-three" issue in numbers with many digits? (specified in #32)

Yes.

**Comment by opoudjis** [comment]
@manuel489 if it's any consolation, I would not bother doing this for numbers that are less than four digits long. There is nothing to localise there.
