### ISSUE TITLE
Separate SI brochure in 3 documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#4]
1. Bilingual version, with bilingual cover
2. French version with French cover, but page numbers following the bilingual version
3. English version with English cover, but page numbers following the bilingual version

**Comment by ronaldtse** [comment]
FYI

**Comment by opoudjis** [comment]
This raises bilingual documents in general, although this is an edge case.

I have implemented local_bibdata to replicate one language. If a document is said to have multiple languages, there should be one local_bibdata for each language, but that really does seem overengineered.

**Comment by opoudjis** [comment]
Generate presentation.xml as a format in metanorma collection.

Concatenate parsed XML and Presentation XML (with references between documents resolved, as required to generate HTML) into a single collection.xml artefact.

**Comment by Intelligent2013** [comment]
@opoudjis 
Is it possible to change the order of `doc-container`s? In current collection xml 1st doc-container contains `en` document, 2nd - `fr`. But in SI brochure - 1st is `fr`, 2nd is `en`.

**Comment by opoudjis** [comment]
Done

**Comment by opoudjis** [comment]
`bundle exec metanorma collection si-brochure-bilingual.yml -x xml,html,presentation,pdf -w bilingual-brochure -c collection_cover.html`

will now generate the three versions of the brochure, as requested. This task is done.
