### ISSUE TITLE
Support for italic text in cross-references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#41]
BIPM documents usually contain this citation style: "[Nicholas *et al.* 1997, Peruzzi *et al.* 2007]" (notice that "et al." is in italics).

For which I'm using this markup: `[<<Nicholas1997,Nicholas _et al._ 1997>>, <<Peruzzi2007,Peruzzi _et al._ 2007>>]`

However, this results in the following rendering: "[*et al.* 1997Nicholas , *et al.* 2007Peruzzi ]"
(If I use no italic markup the result is as expected.)

**Comment by opoudjis** [comment]
extract_localities function presupposes eref is text-only.
