### ISSUE TITLE
List numbering in quote

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#42]
In the source PDF (SI-Brochure-9.pdf ) there a sub-list (A) (B):
![изображение](https://user-images.githubusercontent.com/5559926/97037939-b6aa4800-1572-11eb-9658-ebd47fe1e1ce.png)

In the source adoc it encoded as:
```adoc
[start=4]
. &#x200c;

.. Definitions of the mechanical units which enter the definitions of electric units:
+
--
*_Unit of force_*.:: The unit of....

.. Definitions of electric units. The Comité International des Poids et Mesures (CIPM) accepts the following propositions which define the theoretical value of the electric units:
```

In xml, sub-list marked as `alphabet`, not  `alphabet_upper`:
```xml
<ol id="_637101b4-b506-4d2b-a7b3-cc9bfc5e4f6e" type="arabic" start="4">
<li>
<p id="_60d9719c-9d7e-40a5-9d87-8f6fcb88edad">‌</p>
<ol id="_4927e39a-502b-45c3-aa9f-8d2e23811f8d" type="alphabet" start="">
<li>
<p id="_cdc0e2c5-5f25-4ada-8a17-a79409a73a81">Definitions of the mechanical units which enter the definitions of electric units:</p>
```

Can we mark this sub-list in adoc as `alphabet_upper`. If no, then I propose to set (A) (B) as fixed text. The reasons:
- this list in the cited text and should be cited exactly as original
- i'm sure that in the different years they used different styles for lists and we can't re-generate styles depends on years.

**Comment by opoudjis** [comment]
Marking up as alphabet_upper
