### ISSUE TITLE
Decimal number grouping

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#44]
#38 has used twitter_cldr to implement number localisation, with thousands grouping, but twitter_cldr does not implement groupings of numbers in decimals, which BIPM in their wisdom also need.

For that reason, unless someone else out there has done it, we need to implement a number formatter to replace twitter_cldr.

This number formatter will take the following configuration options, exemplified from the twitter_cldr YAML configuration files:

        :decimal: "." — choice of decimal point
        :exponential: E — for exponential notation
        :group: "," — for groupings of three integer digits
        :fraction_group: "," — for groupings of three fractional digits—not in twitter_cldr
        :minus_sign: "-" — for exponential notation, negatives
        :nan: NaN — for floating point notation
        :plus_sign: + — for exponential notation

The formatter should deal with decimals and integers for now; we can implement exponential notation later.

We also should not hardcode the number of integer and fractional digits to group; Indian scripts use groups of two instead of three.

The formatter should take either a numeric or a string argument. If string, we can assume English locale for float (i.e. decimal point not comma). If string, the number of decimal points should be the same as what is passed in; if numeric, there should be a precision option for how many digits to print, defaulting to a value like 3.

The number formatter will be a new gem under plurimath.

So:

````
NumberFormatter(1000.01212, decimal: ",", group: " ", fraction_group: " ", group_digits: 2, fraction_group_digits: 2, precision: 3) = "10 00,01 21"

NumberFormatter("1000.01212", decimal: ",", group: " ", fraction_group: " ", group_digits: 2, fraction_group_digits: 2) = "10 00,01 21 2"
````

And for now the option hashes to be used by the formatter are: decimal, group, fraction_group, group_digits, fraction_group_digits, precision.

**Comment by opoudjis** [comment]
As mentioned:

It is possible that you can set default values for the options hash using twitter cldr and locale

````
require "twitter_cldr"
locale = TwitterCldr.supported_locale?(@lang.to_sym) ? @lang.to_sym : :en
num = TwitterCldr::DataReaders::NumberDataReader.new(locale)
````

`num.symbols` includes some of the entries in the hash. So you could use `locale` as an argument to look up default values, but any explicit values in the hash would still override them.

So for `:en`, `:decimal == "."`, for `:fr`, `:decimal == "."`

**Comment by ronaldtse** [comment]
> So for :en, :decimal == ".", for :fr, :decimal == "."

You mean `:en, :decimal == "."`, for `:fr, :decimal == ","`?

**Comment by opoudjis** [comment]
Yeah, that.

**Comment by w00lf** [comment]
@opoudjis implemented almost all requirements except one: `group_digits`, this value is usually set by cldr notation for particular locale, so I don't think its will be normal to change this behavior. Take a look: metanorma/isodoc#223

**Comment by opoudjis** [comment]
group_digits is not essential, it was only there in case we did reimplement CLDR.

**Comment by opoudjis** [comment]
... Wow, great work!
