### ISSUE TITLE
ITS-90 Guide contains multiple parts, need to support parts/sub-parts and their titles

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#46]
The ITS-90 Guide contains multiple parts, metanorma-bipm needs to support parts and sub-parts, and part/sub-part titles.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-bipm/issues/2#issuecomment-716957021_

**Comment by ronaldtse** [comment]
ITS-90 guides have been merged in metanorma/mn-samples-bipm#6. This issue is ready for action.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-model-bipm/issues/2: 

title type="part", title type="subpart"
ext/structuredidentifier/part, ext/structuredidentifier/subpart
