### ISSUE TITLE
Consistent numbered list label styling across all BIPM deliverables: SI Brochure, MEP, etc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#47]
From Michael Stock of BIPM:
> Ok, use numbers also for the lists in the mises en pratique. We need then to check if there are any references to the list items which need to be modified, too.

Consistent styling for numbered list labels across BIPM documents (this doesn't apply to quoted/historic texts):

First-level: "1."
Second-level: "a)"
Third-level: what's the typical style we use?

### Warning

> We should not change the type of lists in such texts which are originally printed as part of other documents (CIPM reports, Metrologia publications). Otherwise we would have different types of lists in different publications of the same text. We should therefore not replace the letters in such historic texts with numbers. 

### Rationale

This is in accordance with the following styling:
![image006](https://user-images.githubusercontent.com/11865/97256174-4be85d80-184d-11eb-8014-0e4c70a0f4c6.png)

In the SI Brochure, the numbered lists adopted the format of “1., 2., 3.…”, at the first level, e.g.:
![image002](https://user-images.githubusercontent.com/11865/97256266-92d65300-184d-11eb-888f-4bbc2e76417d.png)

This is also reflected in most resolutions, e.g.:
![image004](https://user-images.githubusercontent.com/11865/97256272-9669da00-184d-11eb-94d8-ef52a01936d5.png)

**Comment by Intelligent2013** [comment]
For info, in XSLT I use the attribute `@type` to set these formats independent of list-level:
- `arabic` - `1.`
- `alphabet` - `a)`
- `alphabet_upper` - `A.`
- `roman` - `(i)`
- `roman_upper` - `I.`

**Comment by opoudjis** [comment]
Which means you're OK now @Intelligent2013 

All that remains is for me to implement these in HTML CSS.

**Comment by opoudjis** [comment]
As https://github.com/metanorma/metanorma-standoc/issues/349 found, putting parentheses into lists in HTML forces the use of a CSS counter, and using start values on top of those CSS counters forces the use of either Javascript or else extensive use of inline styling. I'm implementing this with the latter, but only one level of nesting deep.

**Comment by opoudjis** [comment]
Ambushed by case insensitivity of CSS type (!): CSS selector `[type = "a"]` matches `[type = "A"]`. The flag `[type = "a" s]` for case sensitivity is unsupported by SACC. https://stackoverflow.com/questions/53099708/css-attribute-selector-and-case-sensitivity-with-the-type-attribute-vs-made-u Having to use added class as workaround.
