### ISSUE TITLE
Page breaks per section should be retained for consistency

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#48]
From Michael Stock of BIPM:

>>> 4. Each section starts on a new page, which is strange when the sections are as short as in this document.

>> This practice is inherited from the SI Brochure. Should we retain identical formatting to the SI Brochure (which seems more consistent)? Otherwise we can do a “length check” to determine whether the section should begin on a new page or follow the current page.

> Let’s keep it simple and give priority to consistency.

**Comment by Intelligent2013** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks!
