### ISSUE TITLE
Implement BIPM style for reference labels

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#49]
I have confirmed in existing documents (SI Brochure, MEPs) that BIPM uses the following referential conventions:

* "Section X.X" or "section X.X" for clauses
* "Equation (n)" or "equation (n)" for formulas
* "References" as the section title for the bibliography.

We will implement these.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-bipm/issues/32#issuecomment-716978859_

**Comment by opoudjis** [comment]
For French, have used: Section, Équation (and Inégalité for Inequality), Références

**Comment by opoudjis** [comment]
You are requiring casing on Section, Equation. We have implemented that already for ITU. If other crossreferences need to be cased, let me know.

**Comment by ronaldtse** [comment]
I believe BIPM requires their references to be cased, so let’s do that. Thanks!

**Comment by opoudjis** [comment]
Lowercase i18n labels are cased as cross-references, but need to be capitalised when used as labels of objects.

**Comment by opoudjis** [comment]
Do not capitalise i18n labels if they are all-caps.
