### ISSUE TITLE
Add support for "brochure" document type's independently published appendices

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#5]
Appendix 4 of the SI brochure is published within the SI brochure, and also published separately.

Independent document:
https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-App4-EN.pdf
<img width="507" alt="Screen Shot 2020-09-19 at 6 25 07 PM" src="https://user-images.githubusercontent.com/11865/93664983-73594700-faa5-11ea-8ecf-ba2a9cae0fde.png">

Within SI brochure (page 202 to 210):
https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf
<img width="546" alt="Screen Shot 2020-09-19 at 6 24 32 PM" src="https://user-images.githubusercontent.com/11865/93664970-5e7cb380-faa5-11ea-9c2c-0ce42a1a5eb6.png">

The document sources are provided in https://github.com/metanorma/bipm-si-brochure/tree/master/sources as 
sib-a4-en.adoc and 
sib-a4-fr.adoc.

**Comment by ronaldtse** [comment]
Mockup of an independent Appendix.
<img width="419" alt="Screen Shot 2020-09-21 at 11 00 34 AM" src="https://user-images.githubusercontent.com/11865/93730086-ae6c8f00-fbf9-11ea-8483-03474c7b3987.png">

**Comment by opoudjis** [comment]
This will end up similar to what was done with ITU, with annextitle and annexid:

* The document has the same title as the main document
* The document has a distinct appendix-title
* The document also has a distinct appendix identifier. In ITU, that is treated as part of the structured identifier, along with the part number.

**Comment by opoudjis** [comment]
However, I am NOT treating this as a separate document type: I have no reason to think other document types might not also publish their appendixes separately. Instead, separate appendix publications shall be detected by the presence of an appendix ID in the structured identifier, but they shall otherwise have the same document type as their parent.

**Comment by ronaldtse** [comment]
> separate appendix publications shall be detected by the presence of an appendix ID in the structured identifier, but they shall otherwise have the same document type as their parent

Agree.

**Comment by opoudjis** [comment]
@Intelligent2013 As with the other BIPM issues I've worked on, this is on hold for me, pending input from you.

**Comment by Intelligent2013** [comment]
@opoudjis 
BIPM XSLT will process xml to produce PDF in such manner:

1. If input xml contains `structuredidentifier/appendix`, then bipm brochure xslt will be produce PDF with appendices only as independent document with design from SI-Brochure-9-App4-EN.pdf. One xml -> one pdf.
2. To pass appendix xml(s) into bipm brochure xslt to produce brochure together with appendices, I'll use the parameter `--param appendicesXMLs` for mn2pdf, for example:

```
java -jar mn2pdf.jar --xml-file collection.presentation.xml  --xsl-file bipm.brochure.presentation.xsl  -o out.pdf  --param appendicesXMLs="sib-a4-fr.presentation.xml,sib-a4-en.presentation.xml"
```

**Comment by Intelligent2013** [comment]
Here is resulted PDFs for independently published appendices:
[sib-a4-fr.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5341010/sib-a4-fr.presentation.pdf)
[sib-a4-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5341009/sib-a4-en.presentation.pdf)

@opoudjis in source XML this data are absent:
![изображение](https://user-images.githubusercontent.com/5559926/95338226-6321d400-08bb-11eb-82a3-04c51300a613.png)

to produce a cover page. Could you add it please? (I've hardcoded it in xslt temporarely)

**Comment by Intelligent2013** [comment]
I think no need to add a parameter `appendicesXMLs` processing into mn2pdf (to pass appendix xml(s) into bipm brochure xslt to produce a brochure together with appendices), because source XML contains appendix yet.

**Comment by ronaldtse** [comment]
@Intelligent2013 this is the latest design from our designer. Could you help update the PDF styling for appendices? Thanks!

[SI Appendix_v2.pdf](https://github.com/metanorma/metanorma-bipm/files/5341158/SI.Appendix_v2.pdf)

**Comment by Intelligent2013** [comment]
> this is the latest design from our designer. Could you help update the PDF styling for appendices? Thanks!

@ronaldtse I've confused a bit, looks like SI Appendix_v2.pdf is MEP document. But Appendix 4 is "brochure" document type.
Should I use one design from 'SI Appendix_v2.pdf' for both independently appendices types "brochure" and "mise-en-pratique"?

**Comment by opoudjis** [comment]
@Intelligent2013 

> To pass appendix xml(s) into bipm brochure xslt to produce brochure together with appendices, I'll use the parameter --param appendicesXMLs for mn2pdf, for example:

OK, but I am generating the appendixes as part of the brochure already, through Asciidoctor includes. So I do not need to invoke --param appendicesXMLs , do I? If the XML you have been getting is working, then I do not need to change anything.

**Comment by Intelligent2013** [comment]
> OK, but I am generating the appendixes XML as part of the brochure already, through Asciidoctor includes. So I do not need to invoke --param appendicesXMLs , do I? If the XML you have been getting is working, then I do not need to change anything.

@opoudjis Actually I've refused my proposal (https://github.com/metanorma/metanorma-bipm/issues/5#issuecomment-704951609), so you do not need to change anything.

**Comment by opoudjis** [comment]
In that case nothing further for me to do that I can see, and I am unassigning myself from this ticket.

**Comment by opoudjis** [comment]
No, had not noticed:

![изображение](https://user-images.githubusercontent.com/5559926/95338226-6321d400-08bb-11eb-82a3-04c51300a613.png)

**Comment by opoudjis** [comment]
The committees full names need to be added, and the mises en pratique need to be assigned document identifiers.

**Comment by opoudjis** [comment]
The identifiers are being made up by us.

**Comment by opoudjis** [comment]
Will add committee acronym as distinct from committee name.

**Comment by ronaldtse** [comment]
> > this is the latest design from our designer. Could you help update the PDF styling for appendices? Thanks!
> 
> @ronaldtse I've confused a bit, looks like SI Appendix_v2.pdf is MEP document. But Appendix 4 is "brochure" document type.
> Should I use one design from 'SI Appendix_v2.pdf' for both independently appendices types "brochure" and "mise-en-pratique"?

Yes, the same design should be used for both MEP and brochure appendix types. The key point is the styling should be consistent with the full SI brochure.

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated PDF styling for appendices based on `SI Appendix_v2.pdf` (cover pages only) and brochure styles.
Here is resulted PDF example:
[mep-second-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5374031/mep-second-definition-en.presentation.pdf)

Notices and questions:
1. I've manually added `<appendix>2</appendix>` into source XML, because design PDF has this number, but xml source doesn't. 
2. Titles
![изображение](https://user-images.githubusercontent.com/5559926/95915641-1c971280-0db0-11eb-9312-9155f6c6282c.png)
hard-coded in xlst, no such data in source xml.
3. In English version (design PDF) I saw French title:
![изображение](https://user-images.githubusercontent.com/5559926/95915691-36d0f080-0db0-11eb-904a-7faf16aca74f.png)
It is OK?
4. In English version of source XML there isn't first committee name and vice versa:
![изображение](https://user-images.githubusercontent.com/5559926/95915777-59fba000-0db0-11eb-8b53-b5d2561da303.png)
(first name hard-coded in xslt)
5. Common question relates to 3 and 4 and other title - should we put the bilingual cover to one-language document?

**Comment by ronaldtse** [comment]
> 1. I've manually added <appendix>2</appendix> into source XML, because design PDF has this number, but xml source doesn't.

For @opoudjis 

> 2. Titles hard-coded in xlst, no such data in source xml.

This should be supplied in the source XML (the source asciidoc)

> 3. In English version (design PDF) I saw French title:
 
Yes, let's keep just the French for edition for consistency with the SI brochure which does the same.

> 4. In English version of source XML there isn't first committee name and vice versa:

Should be provided in source XML.

> 5. Common question relates to 3 and 4 and other title - should we put the bilingual cover to one-language document?

No. We should keep the 3 types of documents: bilingual, English, French separately. If the bilingual document doesn't have a French version, we use the bilingual cover but only have English inside.

**Comment by opoudjis** [comment]
> "1". I've manually added 2 into source XML, because design PDF has this number, but xml source doesn't.

Changed source: we're using `:appendix-id:` not `:appendix:`

> "2". Titles hard-coded in xlst, no such data in source xml.

The documents currently think the title of the parent document is "SI Brochure"/"Brochure sur le SI", because that's what the mockup said. "This should be supplied in the source XML (the source asciidoc)"? _You should be telling me to beforehand_.

Changed in source.

4. You want bilingual committee names now? Again: _You should be telling me to beforehand_.

Implementing bilingual committee names. @Intelligent2013 I will be using the `variant` tag to do so:

`<committee acronym="CCTF><variant lang="fr">Comité consultatif du temps et des fréquences</variant><variant lang="en">Consultative Committee for Time and Frequency</variant></committee>`

**Comment by opoudjis** [comment]
Need to add lang and script to metadata vector, in order to pick variants in Liquid metadata vector matching current language

**Comment by opoudjis** [comment]
Am compiling and sending updated files to @Intelligent2013

**Comment by Intelligent2013** [comment]
Latest PDFs for MEP and Appendix 4:
[mep-ampere-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385974/mep-ampere-definition-en.presentation.pdf)
[mep-candela-si-app2.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385977/mep-candela-si-app2.presentation.pdf)
[mep-kelvin-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385978/mep-kelvin-definition-en.presentation.pdf)
[mep-kilogram-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385979/mep-kilogram-definition-en.presentation.pdf)
[mep-metre-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385980/mep-metre-definition-en.presentation.pdf)
[mep-mole-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385982/mep-mole-definition-en.presentation.pdf)
[mep-second-definition-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385983/mep-second-definition-en.presentation.pdf)
[sib-a4-en.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385986/sib-a4-en.presentation.pdf)
[sib-a4-fr.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5385987/sib-a4-fr.presentation.pdf)

**Comment by ronaldtse** [comment]
BIPM feedback provided in #32 and #33

**Comment by ronaldtse** [comment]
@opoudjis please close this if these document types are already properly implemented in gem. The remaining work are tweaks/bug fixes.

**Comment by ronaldtse** [comment]
Closing this since the documents are properly generated (pending #32 and #33)
