### ISSUE TITLE
MEP: mep-metre-definition-en.adoc identical sections

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#52]
In mep-metre-definition-en.adoc the are two almost identical sections:
```
== Definition of the metre
```

Second looks superfluous.

**Comment by manuel489** [comment]
Thanks @Intelligent2013! Yes, the section is wrongly duplicated. Problem solved in https://github.com/metanorma/bipm-si-brochure/commit/144c00d977bf24b2ebb04a15aae782bbb831040e. Closing.
