### ISSUE TITLE
Implement BIPM reference style for bibliographic items

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#55]
BIPM documents currently refer documents this way.

```
[<<Mohr2012,Mohr _et al._ 2012>>\]
...
* [[[Mohr2012,1]]] Mohr P J, Taylor B N and Newell D B (2012) _Rev. Mod. Phys_. *84* 1527-1605
```

```
[<<Quinn1990,Quinn 1990>>].
...
* [[[Quinn1990,1]]] Quinn T J (1990) _Temperature_, 2nd edition (London: Academic Press) p. 495
```

To BIPM documents:

```
<<westwood>>
...
* [[[westwood,4]]], https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-06.pdf[Westwood, S. _Purity Evaluation Guideline: Zearalenone. BIPM-PEG-01. Rapport BIPM-2019/06._ Sèvres (France) : Bureau International des Poids et Mesures, 2019.]
```

```
<<muller>>
...
* [[[muller,1]]], J.W. Müller: "Sums of alternate powers - an empirical approach", Rapport BIPM-94/14 (1994)
```

We should implement a single style for all bibliographic items in BIPM documents.

**Comment by opoudjis** [comment]
We can do this now we have Relaton-Render

**Comment by opoudjis** [comment]
Um....

> We should implement a single style for all bibliographic items in BIPM documents.

Quite. I'm not implementing the second two reference instances, they completely contradict the first two. I've implemented the first two, and will submit them to your approval. But the second two are at odds with the first two, and it would be folly to implement them.

**Comment by opoudjis** [comment]
If we receive initials from relaton formatted "J. K.", and the stylesheet requires initials to be formatted "JK", we need to take the preformatted initials apart and split them, as we already do for forenames. That way, we can re-render initials as needed.

**Comment by opoudjis** [comment]
This sounds like another ticket that requires approval from BIPM. Is it, or can we proceed with the foregoing?

**Comment by opoudjis** [comment]
We're proceeding.

**Comment by opoudjis** [comment]
CCL-GD-MeP-1 displays article titles, in quotes: 

We have implemented:

> {{ creatornames }} ({{role | capitalize}}) ({{date}} ({{ labels['updated'] }}_{{date_updated}}) {% if date %}){% endif %} {{ series }}.

It has done:

> {{ creatornames }} ({{role | capitalize}}), “{{title}}”, _{{ series }}_   {{extent}}

with

extenttemplate: date: "<strong>{{ volume_raw }}</strong> ({{issue_raw}})  ({{date}}) {{ page_raw }}"

We are not currently deviating from the unitary style from all BIPM documents given above, and will not encourage such deviation. I would not rule out though that we end up with a couple of variant styles.

**Comment by opoudjis** [comment]
For the CCL-GD-MeP-1  extent style, which interpolates date between volume and page for articles (something that does happen in references):

> Taniguchi N, “Current status in, and Future Trends of, Ultraprecision Machining and Ultrafine Materials Processing”, CIRP Annals - Manufacturing Technology, 32 (2) (1983) 573–582.
DOI: 10.1016/S0007-8506(07)60185-1

We need to allow extent templates to process all fields, not just volume, issue, page.

**Comment by opoudjis** [comment]
I'm not submitting this to BIPM approval, since we have had zero communication on reference styling from BIPM, unless @ronaldtse there is something you have not passed on. I am satisfied that this is rendering references according to one style, and that that is the style that works for the brochure. 

I won't keep this open as a zombie ticket. If BIPM want different types of document to render citations differently, they will need to say so explicitly: until then, we will treat the other documents' practices as inconsistencies and errors, such as we have repeatedly encountered in working with them.

**Comment by opoudjis** [comment]
@ronaldtse Final signoff please. I draw to your particular attention that article citations exclude the article title in the formatting you'd requested.

**Comment by opoudjis** [comment]
Introduce notion of home standard, but DO NOT apply it to BIPM publications: ISO and IEC include the year in their document identifier if dated at all, BIPM do not.
