### ISSUE TITLE
Add support for document type "mise-en-pratique"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#6]
SI Brochure Appendix 2 contains a number of independent documents, seen here:
https://www.bipm.org/en/publications/mises-en-pratique/

<img width="823" alt="Screen Shot 2020-09-19 at 6 28 02 PM" src="https://user-images.githubusercontent.com/11865/93665026-dba82880-faa5-11ea-9cc8-40db8e1640b6.png">

For each SI Unit, there is 1 document published as a Mise en pratique (MEP). Each MEP may be accompanied by additional guidance documents, but we consider those separately.

The sources for MEPs are provided here:
https://github.com/metanorma/bipm-si-brochure/tree/master/sources with the prefix `mep-`.

We need to unify a document layout for all MEPs and probably for all other "non-brochure" document types.

**Comment by opoudjis** [comment]
Not seeing any great idiosyncrasies in the documents, the versions online are straightforward Word documents with autoformatting.

**Comment by opoudjis** [comment]
Review of #5 is in effect review of these MEPs, so closing this ticket.
