### ISSUE TITLE
Install fonts for BIPM PDF producing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#63]
These fonts should be installed to produce PDF for BIPM flavors :
- Arial
- Times New Roman
- WorkSans fonts ( 'static' fonts WorkSans-Thin, WorkSans-ExtraLight, WorkSans-Light, WorkSans-Regular, WorkSans-Medium, WorkSans-Semibold, WorkSans-Bold, WorkSans-ExtraBold, for info https://github.com/fontist/formulas/issues/7)
- STIX Two Math (STIX2Math.otf)

**Comment by ronaldtse** [comment]
@opoudjis you need to add this information to metanorma-bipm:

https://github.com/metanorma/metanorma-iso/blob/55568ddec7defdefc8126495296e9b4cd04d2b3c/lib/metanorma/iso/processor.rb#L5-L12

You can find the font names here: https://github.com/fontist/formulas

Fontist formula names needed:

* "Arial"
* "Times New Roman"
* "Work Sans"
* "STIX"
