### ISSUE TITLE
Generate index in Presentation XML

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#67]
Presumably it will be realised in Presentation XML as the page-only cross-references we have already been bludgeoned by BIPM into producing.

**Comment by ronaldtse** [comment]
Note: This functionality also applies to ISO 10303.

**Comment by opoudjis** [comment]
Index in Presentation XML shall take the form of a final index clause, after the bibliography, with a title and an unordered list. The unordered list shall contain list entries, each of which shall be the index term, then comma, then a comma-delimited list of pagenumber-only cross-references. As already discussed, and to @Intelligent2013's trepidation, it shall be @Intelligent2013's  responsibility to eliminate consecutive cross-references to the same page number.

**Comment by opoudjis** [comment]
BIPM have "X, see Y" entries; I will need to add those to metanorma-standoc

**Comment by opoudjis** [comment]
Fix standoc indexterm: if Asciidoctor index term contains formatting, preserve it in rendered text.

**Comment by opoudjis** [comment]
Index target is converted to bookmark in PresentationXML. Rendering highlights the fact that bookmark targets are rendered as bare GUIDs. They need to be rendered as the containing section, for HTML. @Intelligent2013 that means that I will have `<xref pagenumber="true" target="X">Clause 1.4</xref>`: ignore the content of any xref with pagenumber=true, and only put in the page number: those xrefs are deliberately meant to be page number only in PDF.

**Comment by Intelligent2013** [comment]
>  @Intelligent2013 that means that I will have `<xref pagenumber="true" target="X">Clause 1.4</xref>`: ignore the content of any xref with pagenumber=true, and only put in the page number: those xrefs are deliberately meant to be page number only in PDF.

@opoudjis FYI, I've made it already for ToC in Appendix 1 for brochure.

**Comment by opoudjis** [comment]
> @opoudjis FYI, I've made it already for ToC in Appendix 1 for brochure.

I know, I just wanted to make sure.

**Comment by opoudjis** [comment]
@Intelligent2013 The horrors continue:

> ampère (A), 13, 16, 18, 20, 28, 44, 49, 51,
> 52, 54, 55, 71, 81, 83-86, 89, 91-94, 97,
> 99, 100, 101, 103-104

if there are more than 2 consecutive numbers, you may be expected to concatenated them into x–y. If you do, please use an en-dash: once again, we are obliged to do better typographically than BIPM.

**Comment by opoudjis** [comment]
"X see Y" and "X see also Y" in an index is going to be handled as a new macro, `index:see[term]` and `index:also[term]`, and a new tag, `<index-xref also="true/false">term</index-xref>`.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 The horrors continue:
> 
> > ampère (A), 13, 16, 18, 20, 28, 44, 49, 51,
> > 52, 54, 55, 71, 81, 83-86, 89, 91-94, 97,
> > 99, 100, 101, 103-104
> 
> if there are more than 2 consecutive numbers, you may be expected to concatenated them into x–y. If you do, please use an en-dash: once again, we are obliged to do better typographically than BIPM.

Hmm, then why they put `99, 100, 101` instead of `99-101`... Is there a sense?

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe `99, 100, 101` can be concatenated as 99-101.

**Comment by opoudjis** [comment]
> Hmm, then why they put 99, 100, 101 instead of 99-101... Is there a sense?

...

Oh God, it's even worse.

It's entirely possible that the index entry is tagged not to a single word instance, but to an entire span of text discussing it.

That's quite reasonable and commonplace, and it is not supported natively by Asciidoctor. Moreover, it will override clause boundaries, and will have to be handled via a starting and ending bookmark in text.

... I mean... yuck. But yes, it means I'm not done here.

**Comment by opoudjis** [comment]
Secondary index terms are needed.

**Comment by opoudjis** [comment]
There is formatted text in the index terms (e.g. subscripts). We are going to have to break the existing XML, and make the attributes into elements, to preserve the formatting.

**Comment by opoudjis** [comment]
> Span will be `term, <xref target="A" to="B" pagenumber="true"/>` in Presentation XML, `index-range:term[B]` in markup (A is the location of the macro in text).

And the semantic XML markup shall be `<index to="B">...</index>`

**Comment by opoudjis** [comment]
Modify Asciidoc: we want the equivalent of `(((primary, secondary, tertiary, to)))`, with optional secondary and tertiary terms. We will represent this as `index-range[(((A, B, C))), TO]`

**Comment by ronaldtse** [comment]
> Modify Asciidoc: we want the equivalent of `(((primary, secondary, tertiary, to)))`, with optional secondary and tertiary terms. We will represent this as `index-range:TO[(((A, B, C)))]`

Why not define the concept of a "spanning anchor" and point the index to it?

**Comment by opoudjis** [comment]
... Because the solution I have already implemented is far more elegant than shoving complexity into the target, and making me go through hoops to extract the information again. It is more complicated for both data entry and for processing, it yields minimal conceptual encapsulation at the cost of much confusion, and I reject it.

**Comment by opoudjis** [comment]
@Intelligent2013 This is ready for you to implement. This is a sample index, as featured in the metanorma-bipm rspec:

````
<clause type="index" id="_"><title>Index</title><clause id="_"><title>D</title><ul><li><em>Dasein</em>, <em>voir</em> Emancipation, &#xEA;tre</li></ul></clause><clause id="_"><title>E</title><ul><li>&#xE9;long&#xE9;,  <xref target="_" to="End" pagenumber="true">chap&#xEE;tre 1</xref></li><li>Emancipation,  <xref target="_" pagenumber="true">chap&#xEE;tre 1</xref>, <xref target="_" pagenumber="true">section 1.1</xref><ul><li>dans la France,  <xref target="_" pagenumber="true">chap&#xEE;tre 1</xref><ul><li>&#xE0; Paris,  <xref target="_" pagenumber="true">section 1.1</xref></li><li>en Bretagne,  <xref target="_" pagenumber="true">chap&#xEE;tre 1</xref></li></ul></li><li>dans les &#xC9;tats-Unis,  <xref target="_" pagenumber="true">section 1.1</xref></li></ul></li><li>&#xEA;tre<ul><li>Husserl, <em>voir</em> zebra, <em>voir aussi</em> Emancipation, zebra<ul><li>en allemand,  <xref target="_" pagenumber="true">chap&#xEE;tre 1</xref></li></ul></li></ul></li></ul></clause><clause id="_"><title>Z</title><ul><li>zebra,  <xref target="_" pagenumber="true">section 1.1</xref></li></ul></clause></clause>
````

Note that `<xref target="_" to="End" pagenumber="true">chap&#xEE;tre 1</xref>` is a page range, as I've previous indicated to you; and, as also previously indicated, you are to ignore the contents of `xref[@pagenumber = 'true'], which are intended for use in HTML, since you will be substituting them with page ranges.
