### ISSUE TITLE
Item cross-reference issue

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#68]
*This issue comes from the feedback provided by BIPM in https://github.com/metanorma/bipm-si-brochure/issues/53*

Item cross-references render different list items respect to the source they point to. For example:

````
The purpose of this section is to clarify the terms that will be used in the following
sections on <<item-1>> primary thermometry and <<item-2>> defined temperature scales.
A clear and well-defined nomenclature is essential to support an unambiguous taxonomy of
methods in the _MeP_-K. The _MeP_-K uses the following definitions.

. [[item-1]]_Primary thermometry_ is carried out using a thermometer based on a...
````

Output (HTML):
![Capture](https://user-images.githubusercontent.com/33627611/99428344-e6800d80-28dc-11eb-94bc-54be87e242bb.PNG)

`<<item-1>>` and `<<item-2>>` render as `a)` and `b)`, respectively. But they should be `1.` and `2.`, like the source.

**Comment by opoudjis** [comment]
In fact the type of the ordered list, and any start value, are being ignored in the generation of crossreferences to list items, which hardcodes ISO's list numbering.

**Comment by opoudjis** [comment]
And make isodoc respect any ol type supplied by standoc; we will override to ignore in ISO.

**Comment by opoudjis** [comment]
This will likely not work in Word, which wants list CSS styles. Oh well.
