### ISSUE TITLE
Add support for document type "guide"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#7]
The SI brochure Appendix 2 contains a number of "guide" documents, as supplements to the Mise en pratique documents. 

<img width="827" alt="Screen Shot 2020-09-19 at 6 32 19 PM" src="https://user-images.githubusercontent.com/11865/93666145-3f365400-faae-11ea-8c76-d4dc73ec615b.png">

For example:
https://www.bipm.org/utils/common/pdf/CC/CCL/CCL-GD-MeP-1.pdf
<img width="449" alt="Screen Shot 2020-09-19 at 7 29 38 PM" src="https://user-images.githubusercontent.com/11865/93666165-773d9700-faae-11ea-8c91-bc0ee8ec7218.png">

And
https://www.bipm.org/utils/common/pdf/CC/CCM/BIPM_Note-on-kilogram-redefinition.pdf
<img width="434" alt="Screen Shot 2020-09-19 at 7 29 58 PM" src="https://user-images.githubusercontent.com/11865/93666168-81f82c00-faae-11ea-8d3d-3185956d02bc.png">

The layouts of them need to be harmonized.

Sources for all Appendix 2 guides are available in https://github.com/metanorma/bipm-si-brochure/tree/master/sources starting with the prefix of `guide-`.

**Comment by opoudjis** [comment]
The document control section needs to be appended after references.

**Comment by ronaldtse** [comment]
> The allergy of BIPM guides to section numbering is bad practice, and BIPM should be talked out of it.

Can you help provide screenshots/samples?

**Comment by opoudjis** [comment]
> Can you help provide screenshots/samples?

You already have. There is no section numbering anywhere in the guide documents. And that is bad practice, because it means nothing in the document can be referenced.

**Comment by opoudjis** [comment]
The random variation in ordered list styling between documents, 1. vs (1), shall be ignored summarily.

https://www.bipm.org/utils/common/pdf/CC/CCM/CCM_Note-on-dissemination-after-redefinition.pdf has a header "Approved at the 17th CCM meeting, 16-17 May 2019". Will add it as `:meeting-note:`, but this is the only guide with that information, and it constitutes capricious inconsistency which should be stamped out.

**Comment by opoudjis** [comment]
The document control information, included only in the metre guides, is metadata. It includes document history: "Draft/Version n.n" with a date. Will encode as `//bibdata/relation[@type = 'supersedes']/bibitem`, `./version/revision-date` and `./version/draft`. (If there was a past edition rather than a draft, it would of course be `./edition`.)

The authors, WG-N co-chairs, and WG-N chairs and their affiliations are coded as author metadata.

All of this demands custom attribute processing, which cannot be handled by the configuration YAML.

**Comment by opoudjis** [comment]
Document attributes shall be:

* supersedes-date_{i}, supersedes-draft_{i} or supersedes-version_{i}
* fullname_{i}, affiliation_{i}
* role_{i}, supplied if other than "author".

The role in fact has to be just "editor", and the actual description in role_{i} moved to role/description.

**Comment by opoudjis** [comment]
I will render the document control section in Presentation XML, it clearly involves a fair bit of logic.

**Comment by opoudjis** [comment]
Handling document control as a new `<doccontrol>` section appended to the end of the document in Presentation XML.

**Comment by opoudjis** [comment]
PDF implemented, so closing this ticket.
