### ISSUE TITLE
Remove standards identifiers from titles in citations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#74]
As a result of https://github.com/metanorma/metanorma-bipm/issues/69,

* BIPM identifiers will be excluded from bibliographic rendering, since they are our invention.
* As evidenced in guide-ccl-GD-MeP-3-en.adoc, documents cited from other SDOs are prefixed with the document identifier (though with no comma), following the practice of ISO and the Metanorma default:

````
* [[[iso5436,ISO 5436-1:2000]]] ISO 5436-1:2000 Geometrical Product Specifications (GPS) -- Surface texture: Profile method; Measurement standards -- Part 1: Material measures

* [[[iso25178,ISO 25178-70:2014]]] ISO 25178-70:2014 Geometrical product specification (GPS) -- Surface texture: Areal -- Part 70: Material measures
````

Request that you go through all such Metanorma-fetched references in BIPM documents, and remove the document identifier from before the title, as we will be inserting it automatically.

**Comment by manuel489** [comment]
Task is merged, closing.
