### ISSUE TITLE
Add support for document type "rapport"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#8]
A BIPM rapport is a report. The SI brochure Appendix 2 contains one rapport document, the "Principles governing photometry (2019)":
<img width="622" alt="Screen Shot 2020-09-19 at 8 49 53 PM" src="https://user-images.githubusercontent.com/11865/93667577-ac031b80-fab9-11ea-96dc-9ffef572a621.png">

<img width="501" alt="Screen Shot 2020-09-19 at 8 50 05 PM" src="https://user-images.githubusercontent.com/11865/93667582-b3c2c000-fab9-11ea-8a47-adac1a318498.png">

The branding guidelines and logos for the SI system can be downloaded here: https://www.bipm.org/en/si-download-area/graphics-files.html

**Comment by opoudjis** [comment]
As already discussed, need sample document for this.

**Comment by ronaldtse** [comment]
Ping @metanorma/editors can you help create the samples for rapport? Thanks!

**Comment by anermina** [comment]
This rapport has actually already been converted in https://github.com/metanorma/bipm-si-brochure/blob/master/sources/mep-candela-rapport.adoc. We can change document attributes if needed.
In case this task requires something else/more, please let me know.

**Comment by ronaldtse** [comment]
@opoudjis I believe this is active now.

**Comment by opoudjis** [comment]
Nothing noteworthy in the Rapport, except that the Terms and Definitions section needs to be recognised as such. And because BIPM do not act like an SDO in labelling their document sections, their capricious refusal to label "Terms and Definitions" sections as such ("Phometric quantities" in https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-05.pdf) consistently needs to be indulged here.

**Comment by opoudjis** [comment]
The styling of https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-07.pdf is utterly different to that of https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-05.pdf

The default assumption is that this is incoherence and not to be emulated by Metanorma, unless BIPM can provide some coherent guidance on formatting.

**Comment by opoudjis** [comment]
Need to add support to authors in metadata, and not to group authors by affiliation

**Comment by ronaldtse** [comment]
We should utilize the same layout we use for MEPs.

**Comment by Intelligent2013** [comment]
Resulted PDF example:
[mep-candela-rapport.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5465274/mep-candela-rapport.presentation.pdf)
