### ISSUE TITLE
Generate cross-reference between documents in collection PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#80]
Lamentably, there is a cross-reference from the French Brochure to the English Brochure, which is expected to include a page number:

````
<p id="_561f5a75-1260-4f9f-8463-ab9678d567dd">En anglais, m&#xEA;me lorsque la valeur d&#x2019;une grandeur est utilis&#xE9;e comme adjectif, il convient
de laisser une espace entre la valeur num&#xE9;rique et le symbole de l&#x2019;unit&#xE9;. Ce n&#x2019;est que
lorsque l&#x2019;on &#xE9;crit le nom de l&#x2019;unit&#xE9; en toutes lettres que l&#x2019;on applique les r&#xE8;gles
grammaticales ordinaires (voir un exemple en anglais page <eref type="inline" bibitemid="english-doc" citeas="si-brochure-en"><localityStack><locality type="anchor"><referenceFrom>id</referenceFrom></locality></localityStack>si-brochure-en</eref>).</p>
````

````
<note id="id"><name>NOTE  3</name>
<p align="left" id="_ded168ca-7438-4a33-bcdb-a667aac3cb83">a <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>10</mn><mtext>&#xA0;k</mtext><mo>&#x3A9;</mo></math></stem> resistor<br/>
a 35-millimetre film</p>
</note>
````

Now that I have implemented this as a proper Metanorma eref cross-reference (between documents), of type anchor, we need it rendered as if it were an xref, with a page number, but only in a context where the page number can be resolved (so in the parsing of the collection, not the parsing of the standalone French document).

So: `eref[.//locality[@type = 'anchor'][referenceFrom = 'id']]` is identical to `xref[@target = 'id']`, so long as id is present in the document. If it isn't, well, you can only treat it as a broken reference.

[collection.presentation.xml.zip](https://github.com/metanorma/metanorma-bipm/files/5607303/collection.presentation.xml.zip)

**Comment by Intelligent2013** [comment]
Done.
