### ISSUE TITLE
"Normative References" section not showing up in BIPM documents

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#88]
Currently, I'm working on the conversion of JCGM document samples: https://github.com/metanorma/mn-samples-bipm/pull/24

_JCGM_104_2009_e_ contains normative references, and these are not appearing in generated document. (I'm using `brochure` as doctype, but I've tried other ones as well.)

I'm compiling with _metanorma-bipm 0.0.5_

@opoudjis, can you take a look, please?

**Comment by ronaldtse** [comment]
@manuel489 the JCGM documents are more like the ISO formats, so please encode them in an ISO way. Thanks!

**Comment by opoudjis** [comment]
I generated BIPM assuming there would be no normative references or terms & definitions; there was after all no hint of them in the BIPM documents proper.

The fact that BIPM capriciously switch from one format to another depending on committee is yet another in the long list of atrocities forced on us.

**Comment by opoudjis** [comment]
@manuel489 That means it is essential that I know that JCGM documents are JCGM documents. I'm putting the correct metadata into the documents.

**Comment by opoudjis** [comment]
@Intelligent2013 This issue also goes to you.

If `//bibdata/ext/editorialgroup/committee/@acronym = "JCGM"`, render `//terms`, `//definitions`, and `//references[@normative = true]` in the same order as ISO. Attaching relevant files.

[JCGM 104.zip](https://github.com/metanorma/metanorma-bipm/files/5715860/JCGM.104.zip)

Cf. https://www.bipm.org/utils/common/documents/jcgm/JCGM_104_2009_E.pdf

**Comment by opoudjis** [comment]
Documenting that committees in BIPM metadata include inter-organization entities.

**Comment by ronaldtse** [comment]
I strongly suggest we encode JCGM documents using a separate processor. Metanorma BIPM can have two processors - one for BIPM docs, one for JCGM docs, which should really inherit from the Metanorma ISO processor.

**Comment by opoudjis** [comment]
Without a document analysis that demonstrates that is warranted, I'm not doing that.

**Comment by Intelligent2013** [comment]
@ronaldtse JCGM source PDFs (https://www.bipm.org/utils/common/documents/jcgm/JCGM_pack_2012-10.zip) have two designs:

- JCGM_100_2008_E.pdf and JCGM_200_2012.pdf have similar design
  - Arial font
but second one is two-language document with
    - English page, then French page and then
    - two columns layout (left column) with tables with two language cells

- JCGM_101_2008_E.pdf, JCGM_102_2011_E.pdf, JCGM_104_2009_E.pdf, JCGM_106_2012_E.pdf have similar design
  - Times New Roman font

For begin, which design do you prefer - based on Arial or Times New Roman fonts?

**Comment by ronaldtse** [comment]
@Intelligent2013 sorry for the late reply. Let's use the Times New Roman font to be consistent with BIPM practice.

For the JCGM_200_2012 document it is necessary to be a bi-lingual document with sometimes sequential (English then French) and sometimes parallel (English and French side by side). I see there are different cases that need encoding:

### Sequential

This section of English text corresponds to French text, show English first and French next

English | French
-- | -- 
<img width="482" alt="Screen Shot 2021-01-04 at 11 26 00 AM" src="https://user-images.githubusercontent.com/11865/103498409-a15d6e00-4e7f-11eb-8567-c1758978acf6.png"> | <img width="487" alt="Screen Shot 2021-01-04 at 11 26 22 AM" src="https://user-images.githubusercontent.com/11865/103498424-ade1c680-4e7f-11eb-948c-554c84a6e914.png">

### Parallel

#### English text corresponds to French text, placed side by side

Example 1 | Example 2
-- | -- 
<img width="490" alt="Screen Shot 2021-01-04 at 11 27 19 AM" src="https://user-images.githubusercontent.com/11865/103498456-cfdb4900-4e7f-11eb-8bb0-af6c2a6ec487.png"> | <img width="478" alt="Screen Shot 2021-01-04 at 11 28 36 AM" src="https://user-images.githubusercontent.com/11865/103498500-fdc08d80-4e7f-11eb-878f-eeba2f99e0d8.png">



#### Shared element between both languages

e.g. image/table but corresponds to both text, 1 table/image shared by both languages

Example 1 | Example 2
-- | -- 
<img width="472" alt="Screen Shot 2021-01-04 at 11 27 53 AM" src="https://user-images.githubusercontent.com/11865/103498479-e41f4600-4e7f-11eb-9708-f6afc4f3f8ca.png"> | <img width="485" alt="Screen Shot 2021-01-04 at 11 29 34 AM" src="https://user-images.githubusercontent.com/11865/103498547-20eb3d00-4e80-11eb-8cdd-fd1716656f08.png">

**Comment by Intelligent2013** [comment]
@opoudjis 
I've updated iso.international-standard.presentation.core.xsl (https://github.com/metanorma/mn-native-pdf/blob/jcgm/xslt_src/iso.international-standard.presentation.core.xsl) to process JCGM documents. Please note, that ISO process JCGM with `bipm-standard` element (namespace https://www.metanorma.org/ns/bipm), non `iso-standard`. If you need to change this behaviour please inform me.

Here is resulted PDF:
[document.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5800145/document.presentation.pdf)

In source xml there aren't some data:
- there isn't Copyright (July) month in xml, 
- no data for pages ii (+images)
- there isn't standalone string `Joint Committee for Guides in Metrology`
- two sections with number `2.`
  - <title depth="1">2.<tab/>What is measurement uncertainty?</title>
  - <title depth="1">2.<tab/>Normative references</title>
- there isn't localized-string[@key="all_rights_reserved"]
- inline-header="true" missed for clauses, example "3.1"

**Comment by ronaldtse** [comment]
@Intelligent2013 we would want to separate JCGM from the ISO style sheet because it is not by ISO. The JCGM style sheet can import from ISO but the maintenance of them must be kept separate.

**Comment by Intelligent2013** [comment]
@ronaldtse ok, I see. Then I'll extract JCGM addon from ISO xslt into separate jcgm.standard.presentation.xsl.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by Intelligent2013** [comment]
JCGM xslt jcgm.standard.presentation.core.xsl added (https://github.com/metanorma/mn-native-pdf/blob/master/xslt_src/jcgm.standard.presentation.core.xsl).

**Comment by Intelligent2013** [comment]
Here is resulted JCGM PDF: [document.col.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5810427/document.col.presentation.pdf)
At this moment no more actions from me, so closing the ticket.

**Comment by Intelligent2013** [comment]
Here is resulted JCGM PDF: [document.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/5810439/document.presentation.pdf)
