### ISSUE TITLE
Add support for committee "JCGM" for their document types

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#9]
The JCGM is a joint committee of multiple SDOs including BIPM, OIML, ISO, etc. Its secretariat is BIPM so it belongs to this flavor.

All its documents can be downloaded from here:
https://www.bipm.org/en/committees/jc/jcgm/
(link: https://www.bipm.org/utils/common/documents/jcgm/JCGM_pack_2012-10.zip)

<img width="504" alt="Screen Shot 2020-09-20 at 9 49 35 AM" src="https://user-images.githubusercontent.com/11865/93692490-9972fb80-fb26-11ea-994d-582c755b4699.png">
<img width="478" alt="Screen Shot 2020-09-20 at 9 49 43 AM" src="https://user-images.githubusercontent.com/11865/93692492-9d068280-fb26-11ea-8eaf-8ad6a6424fbb.png">

**Comment by ronaldtse** [comment]
I have been in touch with a JCGM leader and will update this later.

**Comment by ronaldtse** [comment]
@metanorma/editors could you help convert the first 10 pages of each of these documents? Let's wait for the LaTeX source for the full content. With some sample data at least we can first develop the layouts. Thanks!

**Comment by ronaldtse** [comment]
Samples to be done metanorma/mn-samples-bipm#20

**Comment by ronaldtse** [comment]
https://github.com/metanorma/mn-samples-bipm/pull/24 is done

The JCGM 100, 101 and 104 are provided.

**Comment by ronaldtse** [comment]
@opoudjis this is ready to go.

**Comment by opoudjis** [comment]
I'm not seeing a compelling reason to give the doctype as `jcgm-guide` as opposed to `guide`. The `guide` doctype is orthogonal to the fact that this is a JCGM document, and the latter is what determines the XSLT stylesheet for PDF.

**Comment by opoudjis** [comment]
Need to introduce a label for cross-references to index.

**Comment by opoudjis** [comment]
Other issues: 

* The identifier is not BIPM ... but JCGM ...
* The normative references appear to be optional; section numbering needs to reflect that

**Comment by opoudjis** [comment]
Request for review of the JCGM documents against their originals. Sending renderings separately.

**Comment by ronaldtse** [comment]
> I'm not seeing a compelling reason to give the doctype as `jcgm-guide` as opposed to `guide`. The `guide` doctype is orthogonal to the fact that this is a JCGM document, and the latter is what determines the XSLT stylesheet for PDF.

But we have BIPM guide vs JCGM guide.

**Comment by opoudjis** [comment]
Review has led to separate ticket, so closing this ticket.
