### ISSUE TITLE
Errors with "CCL-CCTF Frequency Standards Working Group is not a recognised committee"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#94]
```
Document Attributes: CCL-CCTF Frequency Standards Working Group is not a recognised committee
Document Attributes: CCL-CCTF-WGFS is not a recognised committee
```

In bipm-si-brochure, run
```
bundle exec metanorma sources/rec-values/115In_1267THz.adoc
```

**Comment by opoudjis** [comment]
CCL-CCTF-WGFS was not provided as one of the editorial groups for BIPM, as can be seen in https://www.metanorma.com/author/bipm/authoring/ : CCL-CCTF was. Clearly however CCL-CCTF-WGFS is the canonical abbreviation given in https://www.bipm.org/en/committees/cc/cctf/ . Updating accordingly.
