### ISSUE TITLE
Defining rules for BIPM documents

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#95]
While checking .adoc sources, I've noticed some inconsistencies for which we need rules which would be applied to all BIPM documents of the same type.

- Guides and monographies seem to be using author's name + publishing year when cross-referencing some document. However, it is not clear which elements should be italicized and which parentheses should be used and where.
 
Some examples from the original documents are shown below.

Guide_ITS-90_6_RadiationThermometry_2018.pdf:
![image](https://user-images.githubusercontent.com/55683568/103155552-49e54100-47a1-11eb-9e30-8b4338f133f0.png)

Guide-PLTS-2000.pdf (`guide-plts-2000_supp_info.adoc`):
![image](https://user-images.githubusercontent.com/55683568/103155326-2620fb80-479f-11eb-902c-443d890b7143.png)

Monographie_BIPM-6.pdf:
![image](https://user-images.githubusercontent.com/55683568/103172626-04824b80-4855-11eb-9dcd-487cd89c1592.png)

@manuel489 and I encoded these differently. While Manuel renamed cross-references in order to match source documents, I've used standard cross-referencing which provides automatic numbering. Of course, I can adjust all source .adocs, but I need a rule how these should be represented, since all the examples look differently. 

- Following are italicized in some documents, while not in others, or at some places of the same document, but not at others:
	- "per se", (maybe we can generalize this to all Latin terms, such as "et al.", "a priori", etc.);
	- "voir"/"see" (this refers to the main text, not footnotes/notes/examples shown on right margins);
	- letter "e" in triple points of equilibrium H2: "e-H2";
	- letter "d" which refers to differential (e.g. `int x dx`).
	
- Should we use subscripts and superscripts in subscripts/superscripts? 
	- In guide-its90-05: `"H2O"` vs. `"H"_2"O"` in subscripts (both these appear in the same document),
![image](https://user-images.githubusercontent.com/55683568/103246089-8613cf80-4962-11eb-8706-2c9bc5c3d8c3.png)
	- In Rapport 2015-03: `"w,c"^2` in subscripts
![image](https://user-images.githubusercontent.com/55683568/103246121-a93e7f00-4962-11eb-877d-0406638b81c7.png)

**Comment by ronaldtse** [comment]
@anermina @manuel489 in all documents we should replace all current bibliographic formatting with ISO 690 format.

I have confirmed with BIPM that they can utilize the ISO 690 format across all documents.

This means:
1. All of the documents must have a bibliography stated in the ISO 690 format.
2. In-content references are automatically generated references just like in other Metanorma documents

ISO 690 provides 3 types of "in-text citations": Harvard, Numeric and Named Tag systems. In BIPM they use the Numeric system, so the short references should follow (ISO/DIS 690 A.3):

<img width="698" alt="Screen Shot 2021-02-01 at 11 55 44 AM" src="https://user-images.githubusercontent.com/11865/106413193-6ea99400-6484-11eb-82e3-cccee50a5d2d.png">
<img width="699" alt="Screen Shot 2021-02-01 at 11 55 52 AM" src="https://user-images.githubusercontent.com/11865/106413199-723d1b00-6484-11eb-99d4-2bdbf23bb6af.png">


Specific question:

> Should we use subscripts and superscripts in subscripts/superscripts?

Yes.

> Italicization of:
> "per se", (maybe we can generalize this to all Latin terms, such as "et al.", "a priori", etc.);
> "voir"/"see" (this refers to the main text, not footnotes/notes/examples shown on right margins);

These probably should not need any italicization. Ping @opoudjis 

> letter "e" in triple points of equilibrium H2: "e-H2";
> letter "d" which refers to differential (e.g. int x dx).

These should be encoded as in the title of the referenced document (they are math and probably should be encoded as such).

**Comment by opoudjis** [comment]
I'm pretty sure I already italicise "voir"/"see" specifically, since those are automatically inserted in cross-references.

**Comment by ronaldtse** [comment]
I believe this is all done. Thanks guys!
